// approval-scope のテストが共有する fixture (テスト仕様 01 §4)。一時ディレクトリに本物の git repo を作り、変更を実際に
// commit して判定させる。テストファイルを分けて並列に動かすため、共通部分をここに置く。
import { spawnSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, realpathSync, rmSync, writeFileSync } from 'node:fs';
import { devNull, tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { after } from 'node:test';
import assert from 'node:assert/strict';
import { Cli } from '../cli/Cli.js';
import { IGETA_ROOT } from '../core/Paths.js';
import { ApprovalScopeCommand } from './ApprovalScopeCommand.js';
import { spawnGit } from './GitRepo.js';
import type { GitOutput, GitRunner } from './GitRepo.js';

// 利用者の git の設定 (署名・hooksPath・diff.renames など) と、この test を動かす環境の GIT_* (hook の中など) に左右されない
for (const name of Object.keys(process.env)) if (name.startsWith('GIT_')) delete process.env[name];
Object.assign(process.env, {
  GIT_CONFIG_GLOBAL: devNull,
  GIT_CONFIG_NOSYSTEM: '1',
  GIT_AUTHOR_NAME: 'test',
  GIT_AUTHOR_EMAIL: 'test@example.com',
  GIT_COMMITTER_NAME: 'test',
  GIT_COMMITTER_EMAIL: 'test@example.com',
});

const workspaces: string[] = [];

after(() => {
  for (const dir of workspaces) rmSync(dir, { recursive: true, force: true });
});

export function gitIn(cwd: string, ...args: string[]): string {
  const result = spawnSync('git', ['-C', cwd, ...args], { encoding: 'utf8' });
  if (result.status !== 0) throw new Error(`git ${args.join(' ')} が失敗した: ${result.stderr}`);
  return result.stdout.trim();
}

export function tempDir(prefix: string): string {
  const dir = realpathSync(mkdtempSync(join(tmpdir(), prefix)));
  workspaces.push(dir);
  return dir;
}

export class TestRepo {
  readonly root: string;

  private constructor(root: string) {
    this.root = root;
  }

  /** main に files を commit した repo。 */
  static create(files: Readonly<Record<string, string>> = {}): TestRepo {
    const repo = new TestRepo(tempDir('igeta-approval-scope-test-'));
    repo.git('init', '-q', '-b', 'main');
    for (const [rel, content] of Object.entries(files)) repo.write(rel, content);
    repo.git('add', '-A');
    repo.git('commit', '-q', '--allow-empty', '-m', 'base');
    return repo;
  }

  git(...args: string[]): string {
    return gitIn(this.root, ...args);
  }

  write(rel: string, content: string): void {
    const target = join(this.root, rel);
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, content);
  }

  move(from: string, to: string): void {
    mkdirSync(dirname(join(this.root, to)), { recursive: true });
    this.git('mv', from, to);
  }

  /** 今の HEAD から branch を切って移る。 */
  branch(name = 'feature'): void {
    this.git('checkout', '-q', '-b', name);
  }

  checkout(name: string): void {
    this.git('checkout', '-q', name);
  }

  commit(message = 'change'): void {
    this.git('add', '-A');
    this.git('commit', '-q', '-m', message);
  }

  /** 既存のファイルの 1 行目の後ろに 1 行足す (中身は判定に関係しない。変更があったことだけを作る)。 */
  touch(rel: string): void {
    this.write(rel, `${rel}\n変更\n`);
  }
}

/** origin (bare) に main を push した repo。`--ci` の宛先 `origin/main` を持つ。 */
export function withOrigin(files: Readonly<Record<string, string>>): { readonly repo: TestRepo; readonly origin: string } {
  const origin = tempDir('igeta-approval-scope-origin-');
  gitIn(origin, 'init', '-q', '--bare', '-b', 'main');
  const repo = TestRepo.create(files);
  repo.git('remote', 'add', 'origin', origin);
  repo.git('push', '-q', 'origin', 'main');
  return { repo, origin };
}

/** 新しい構成の repo: 人のフォルダ・AI のフォルダ・生成索引・コード・決定 1 のファイル。 */
export const BASE_FILES: Readonly<Record<string, string>> = {
  'docs/person/requirements/01-requirements.md': '# 要件\n',
  'docs/person/design/README.md': [
    '# design',
    '',
    '<!-- AUTOGEN:dir-index:start — generated by scripts/generate-docs-graph.mjs, do not edit by hand -->',
    '',
    '| 文書 |',
    '|---|',
    '| 01 |',
    '',
    '<!-- AUTOGEN:dir-index:end -->',
    '',
  ].join('\n'),
  'docs/client/delivery/01-chapter.md': '# 章\n',
  'docs/ai/specs/shared/01-spec.md': '# 仕様\n',
  'docs/ai/AGENTS.md': '# docs/ai の入口\n',
  'docs/README.md': '# docs\n',
  'docs/dependencies.md': '# 依存\n',
  'src/index.ts': 'export {};\n',
  'src/core/a.ts': 'export {};\n',
  'package.json': '{ "name": "app", "scripts": { "build": "tsc" }, "devDependencies": { "igeta": "1.0.0" } }\n',
  'package-lock.json': '{ "lockfileVersion": 3, "packages": {} }\n',
  '.github/workflows/x.yml': 'name: x\n',
  '.github/actions/a/action.yml': 'name: a\n',
  '.github/CODEOWNERS': 'docs/person/ @owner\n',
  CODEOWNERS: 'docs/person/ @owner\n',
  'docs/CODEOWNERS': 'person/ @owner\n',
  '.igeta.json': '{}\n',
  '.igeta-version': '0.4.0\n',
  'AGENTS.md': '# agents\n',
  'CLAUDE.md': '# claude\n',
  '.claude/settings.json': '{}\n',
};

export interface Run {
  readonly code: number;
  readonly stdout: readonly string[];
  readonly stderr: readonly string[];
}

/** `igeta approval-scope <argv>` を動かす。env は環境変数 (既定は空)、git は git の呼び出しの差し替え。 */
export async function scope(
  argv: readonly string[],
  cwd: string,
  options: { readonly env?: Readonly<Record<string, string | undefined>>; readonly git?: GitRunner } = {},
): Promise<Run> {
  const stdout: string[] = [];
  const stderr: string[] = [];
  const command = new ApprovalScopeCommand({ env: options.env ?? {}, ...(options.git === undefined ? {} : { git: options.git }) });
  const code = await new Cli().register(command).run(['approval-scope', ...argv], {
    cwd,
    igetaRoot: IGETA_ROOT,
    stdout: (line) => stdout.push(line),
    stderr: (line) => stderr.push(line),
  });
  return { code, stdout, stderr };
}

/** 標準出力の理由の行 (`- <パス> (<理由>)`) から、パスと理由を取り出す。 */
export function reasons(run: Run): ReadonlyArray<{ readonly path: string; readonly rule: string }> {
  return run.stdout
    .filter((line) => line.startsWith('- '))
    .map((line) => {
      const cut = line.lastIndexOf(' (');
      return { path: line.slice(2, cut), rule: line.slice(cut + 2, -1) };
    });
}

export const reasonPaths = (run: Run): string[] => reasons(run).map((reason) => reason.path);

/** 適合 (`ai`)・終了コード 0・理由なし。 */
export function assertAi(run: Run, label = ''): void {
  assert.equal(run.code, 0, `${label} ai のはずが終了コード ${run.code}: ${run.stdout.join(' | ')} ${run.stderr.join(' | ')}`);
  assert.equal(run.stdout[0], 'ai', label);
  assert.deepEqual(reasonPaths(run), [], label);
  assert.deepEqual(run.stderr, [], label);
}

/** `human`・終了コード 1。paths を渡せば、理由のパスがその一覧と一致する。 */
export function assertHuman(run: Run, paths?: readonly string[], label = ''): void {
  assert.equal(run.code, 1, `${label} human のはずが終了コード ${run.code}: ${run.stdout.join(' | ')} ${run.stderr.join(' | ')}`);
  assert.equal(run.stdout[0], 'human', label);
  if (paths !== undefined) assert.deepEqual(reasonPaths(run), [...paths].sort(), label);
}

/** 検査不能・終了コード 2。標準出力は空 (human でも ai でもない)。message を渡せば、標準エラーがそれに当たる。 */
export function assertCannotCheck(run: Run, message?: RegExp, label = ''): void {
  assert.equal(run.code, 2, `${label} 検査不能のはずが終了コード ${run.code}: ${run.stdout.join(' | ')}`);
  assert.deepEqual(run.stdout, [], label);
  if (message !== undefined) assert.match(run.stderr.join('\n'), message, label);
}

/** 本物の git を呼び、override が出力を返した呼び出しだけ差し替える (テスト仕様 01 の「git の呼び出しを差し替える」テスト)。 */
export const fakeGit =
  (override: (args: readonly string[]) => GitOutput | undefined): GitRunner =>
  (root, args) =>
    override(args) ?? spawnGit(root, args);
