// 各フォルダの README.md の例外 (ADR-0008 決定 1)。
//
// README.md は、生成器が管理する AUTOGEN 区間 (dir-index・adr-index・tentative-index) の中だけが変わり、
// 区間の中身が再生成の結果と一致するときに限り、人の承認が要るかの判定から除く。再生成の結果は
// 既存の生成器 (docs-graph) を呼んで得る。得られないときは除かない (呼び出し側は `human` 側に倒す)。
//
// 再生成は作業ツリーを書き換えずに、docs/ の Markdown を一時ディレクトリへ写して行う。候補の README は
// 区間の中身を空にして写すので、生成器がその区間を実際に埋め直したときだけ「再生成の結果」が得られる
// (生成器が管理していない README の区間に手で書いた中身は、そのまま残って一致扱いにならない)。

import { cpSync, lstatSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { DocGraphCheck } from '../checks/DocGraphCheck.js';
import { classifyLines } from '../core/LineClassifier.js';

// 生成器が書く区間のマーカー (DocGraphCheck.ts の *_START / *_END と同じ 1 行)。1 文字でも違う区間は
// 管理された区間として扱わない (区間の外の変更になり、例外は使えない)。生成物との一致は
// ReadmeIndexException.test.ts が実際の生成器の出力で固定する。
export const MANAGED_START_LINE =
  /^<!-- AUTOGEN:(dir-index|adr-index|tentative-index):start — generated by scripts\/generate-docs-graph\.mjs, do not edit by hand -->$/;
export const MANAGED_END_LINE = /^<!-- AUTOGEN:(dir-index|adr-index|tentative-index):end -->$/;

/** 生成器が埋め直さなかった区間の目印。中身がこれのまま残った区間は「再生成されなかった」。 */
export const REGION_MASK = '<!-- approval-scope: 再生成の結果と比べるため中身を空にした -->';

interface Region {
  readonly kind: string;
  /** 開始マーカーの行 (0 始まり) */
  readonly start: number;
  /** 終了マーカーの行 */
  readonly end: number;
}

/** 管理された区間の組を返す。入れ子・閉じ忘れ・種類の食い違いがあれば null (区間として読めない)。 */
function parseRegions(lines: readonly string[]): readonly Region[] | null {
  const kinds = classifyLines(lines);
  const regions: Region[] = [];
  let open: { readonly kind: string; readonly start: number } | null = null;
  for (let i = 0; i < lines.length; i += 1) {
    if (kinds[i] !== 'autogen') continue;
    const line = lines[i] ?? '';
    const start = MANAGED_START_LINE.exec(line);
    if (start !== null) {
      if (open !== null) return null;
      open = { kind: start[1] ?? '', start: i };
      continue;
    }
    const end = MANAGED_END_LINE.exec(line);
    if (end !== null) {
      if (open === null || open.kind !== end[1]) return null;
      regions.push({ kind: open.kind, start: open.start, end: i });
      open = null;
    }
  }
  return open === null ? regions : null;
}

const interiorOf = (lines: readonly string[], region: Region): string => lines.slice(region.start + 1, region.end).join('\n');

/** 区間の中身を REGION_MASK 1 行に置き換えた本文。区間の外とマーカーの行はそのまま。 */
function maskInteriors(lines: readonly string[], regions: readonly Region[]): string {
  const masked = [...lines];
  for (const region of [...regions].reverse()) masked.splice(region.start + 1, region.end - region.start - 1, REGION_MASK);
  return masked.join('\n');
}

export interface ReadmeCandidate {
  /** repo のルートからの相対パス (docs/ の下の README.md) */
  readonly path: string;
  readonly before: string;
  readonly after: string;
}

export type ReadmeOutcome = { readonly excluded: true } | { readonly excluded: false; readonly why: string };

interface Pending {
  readonly candidate: ReadmeCandidate;
  readonly afterLines: readonly string[];
  readonly afterRegions: readonly Region[];
}

/** docs/ の Markdown だけを写す (生成器が読むのは .md。シンボリックリンクは辿らない)。 */
function isMarkdownOrDirectory(source: string): boolean {
  const stat = lstatSync(source);
  return stat.isDirectory() || (stat.isFile() && source.endsWith('.md'));
}

async function regenerate(
  root: string,
  igetaRoot: string,
  pending: readonly Pending[],
): Promise<{ readonly texts: ReadonlyMap<string, string> } | { readonly error: string }> {
  const temp = mkdtempSync(join(tmpdir(), 'igeta-approval-scope-'));
  try {
    cpSync(join(root, 'docs'), join(temp, 'docs'), { recursive: true, filter: isMarkdownOrDirectory });
    for (const { candidate, afterLines, afterRegions } of pending) {
      const target = join(temp, candidate.path);
      mkdirSync(dirname(target), { recursive: true });
      writeFileSync(target, maskInteriors(afterLines, afterRegions));
    }
    const violations = await new DocGraphCheck({ write: true }).run({ targetRoot: temp, igetaRoot });
    const first = violations[0];
    if (first !== undefined) {
      return { error: `docs-graph で再生成できなかった: ${first.message.split('\n')[0] ?? ''}` };
    }
    const texts = new Map<string, string>();
    for (const { candidate } of pending) texts.set(candidate.path, readFileSync(join(temp, candidate.path), 'utf8'));
    return { texts };
  } catch (error) {
    return { error: `再生成を実行できなかった: ${error instanceof Error ? error.message : String(error)}` };
  } finally {
    rmSync(temp, { recursive: true, force: true });
  }
}

/**
 * 候補の README ごとに、例外を使えるか (判定から除けるか) を返す。使えない理由は why に書く。
 * 除く条件は全部満たすこと: ① 前後とも管理された区間として読める ② 区間の外 (マーカー行を含む) が前後で同じ
 * ③ 実際に変わっている ④ 後の区間の中身が、生成器が埋め直した結果と一致する。
 */
export async function evaluateReadmeExceptions(
  root: string,
  igetaRoot: string,
  candidates: readonly ReadmeCandidate[],
): Promise<ReadonlyMap<string, ReadmeOutcome>> {
  const outcomes = new Map<string, ReadmeOutcome>();
  const pending: Pending[] = [];

  for (const candidate of candidates) {
    const beforeLines = candidate.before.split('\n');
    const afterLines = candidate.after.split('\n');
    const beforeRegions = parseRegions(beforeLines);
    const afterRegions = parseRegions(afterLines);
    const fail = (why: string): void => {
      outcomes.set(candidate.path, { excluded: false, why });
    };
    if (beforeRegions === null || afterRegions === null) fail('AUTOGEN 区間の組が壊れている');
    else if (candidate.before === candidate.after) fail('内容が変わっていない (権限だけの変更など)');
    else if (afterRegions.length === 0) fail('生成器が管理する AUTOGEN 区間が無い');
    else if (maskInteriors(beforeLines, beforeRegions) !== maskInteriors(afterLines, afterRegions)) {
      fail('AUTOGEN 区間の外が変わっている');
    } else pending.push({ candidate, afterLines, afterRegions });
  }
  if (pending.length === 0) return outcomes;

  const regenerated = await regenerate(root, igetaRoot, pending);
  for (const { candidate, afterLines, afterRegions } of pending) {
    if ('error' in regenerated) {
      outcomes.set(candidate.path, { excluded: false, why: regenerated.error });
      continue;
    }
    const regenLines = (regenerated.texts.get(candidate.path) ?? '').split('\n');
    const regenRegions = parseRegions(regenLines);
    let why: string | null = null;
    if (regenRegions === null || regenRegions.length !== afterRegions.length) why = '再生成の結果の区間が一致しない';
    else {
      for (const [index, region] of afterRegions.entries()) {
        const regen = regenRegions[index];
        if (regen === undefined || regen.kind !== region.kind) why = '再生成の結果の区間が一致しない';
        else if (interiorOf(regenLines, regen) === REGION_MASK) why = `${region.kind} 区間は docs-graph が再生成しない (管理外の README)`;
        else if (interiorOf(regenLines, regen) !== interiorOf(afterLines, region)) {
          why = `${region.kind} 区間の中身が再生成の結果と違う`;
        }
        if (why !== null) break;
      }
    }
    outcomes.set(candidate.path, why === null ? { excluded: true } : { excluded: false, why });
  }
  return outcomes;
}
