import { existsSync } from 'node:fs';
import { readFile, readdir, writeFile } from 'node:fs/promises';
import { basename, dirname, join, relative, resolve, sep } from 'node:path';

import type { Check, CheckContext } from '../core/Check.js';
import type { Violation } from '../core/Report.js';

/**
 * docs/**\/*.md の frontmatter から依存グラフ・ADR 索引・ディレクトリ索引を生成し、
 * schema / 参照整合性 / 本文リンクを検査する。
 *
 * - write: true  … 索引を書き出し、hard error だけを Violation として返す
 * - write 省略   … 何も書かず、drift と hard error を Violation として返す
 *
 * Spec: docs/guides/01-document-taxonomy.md
 */

// 生成物に埋め込まれるマーカー。既存リポの生成物と 1 文字でも違うと全リポが drift になる。
const ADR_INDEX_START =
  '<!-- AUTOGEN:adr-index:start — generated by scripts/generate-docs-graph.mjs, do not edit by hand -->';
const ADR_INDEX_END = '<!-- AUTOGEN:adr-index:end -->';
const DIR_INDEX_START =
  '<!-- AUTOGEN:dir-index:start — generated by scripts/generate-docs-graph.mjs, do not edit by hand -->';
const DIR_INDEX_END = '<!-- AUTOGEN:dir-index:end -->';
const AUTOGENERATED_HEADER =
  '<!-- AUTOGENERATED BY scripts/generate-docs-graph.mjs — DO NOT EDIT BY HAND -->';

const OUTPUT_REL = 'docs/dependencies.md';
const ADR_README_REL = 'docs/adr/README.md';

// 生成日付は毎日変わる。比較対象に含めると索引を生成した翌日に必ず drift 扱いになるため落とす。
const stripGeneratedAt = (text: string): string => text.replace(/^> 自動生成: .*$/m, '> 自動生成:').trim();

// docs-structure.md §13.1 — ADR は独自のライフサイクル語彙を持つ。
const ADR_STATUSES = new Set(['proposed', 'accepted', 'deprecated', 'superseded', 'rejected', 'template']);

// arc42 12 章 (https://arc42.org/overview/)。索引はフォルダ順ではなく章順に並べる。
const ARC42_CHAPTERS: ReadonlyArray<readonly [number, string, string]> = [
  [1, 'Introduction and Goals', '導入と目標'],
  [2, 'Constraints', '制約'],
  [3, 'Context and Scope', 'コンテキストと範囲'],
  [4, 'Solution Strategy', '解決戦略'],
  [5, 'Building Block View', '構成要素'],
  [6, 'Runtime View', '実行時ビュー'],
  [7, 'Deployment View', '配置ビュー'],
  [8, 'Crosscutting Concepts', '横断概念'],
  [9, 'Architecture Decisions', 'アーキテクチャ決定'],
  [10, 'Quality Requirements', '品質要求'],
  [11, 'Risks and Technical Debt', 'リスクと技術的負債'],
  [12, 'Glossary', '用語集'],
];
// arc42 の外側にある文書種別 (章が無いのが正しい)。章未割当の警告対象から外す。
const NON_ARC42_KINDS = new Set([
  'tasks',
  'proposal',
  'guide',
  'implementation-order',
  'document-taxonomy',
  'explanation',
  'runbook',
]);
// 階層の根になれる文書種別 (type / kind のどちらかで判定)。上流も下流も持たなくてよい。
// 要件定義は全設計書の上流、ADR は決定そのもの、guide / runbook / explanation は横断・独立 (taxonomy §1)。
const ROOT_KINDS = new Set([...NON_ARC42_KINDS, 'requirements', 'adr', 'index', 'glossary', 'as-is-overview']);

// 本文 Markdown リンクの実在検査 (frontmatter の参照整合性とは別レイヤ)。
const BODY_LINK_RE = /!?\[[^\]]*\]\(\s*<?([^)<>\s]+)>?(?:\s+"[^"]*")?\s*\)/g;

/** 検査を続行できない規約違反。呼び出し元で Violation に変換する。 */
class DocGraphError extends Error {}

type FrontmatterValue = string | string[];
interface Frontmatter {
  readonly [key: string]: FrontmatterValue | undefined;
}

interface Doc {
  /** targetRoot からの相対パス */
  readonly path: string;
  readonly id: string;
  readonly title: string | undefined;
  readonly type: string | undefined;
  readonly kind: string | undefined;
  readonly status: string | undefined;
  readonly canonical: string | undefined;
  readonly canonicalFor: string | undefined;
  readonly supersededBy: string | undefined;
  readonly accepted: string | undefined;
  readonly proposed: string | undefined;
  readonly adopted: string | undefined;
  readonly dependsOn: readonly string[];
  readonly relatesTo: readonly string[];
  readonly supersedes: readonly string[];
  readonly aliases: readonly string[];
}

interface DocMeta {
  readonly fm: Frontmatter;
  readonly content: string;
  readonly title: string;
}

interface DirIndex {
  readonly readmePath: string;
  /** targetRoot からの相対パス */
  readonly rel: string;
  readonly existing: string | null;
  readonly desired: string;
}

interface DirIndexResult {
  readonly indexes: readonly DirIndex[];
  readonly arc42Warnings: readonly string[];
}

interface LinkProblem {
  /** targetRoot からの相対パス */
  readonly file: string;
  readonly line: number;
  readonly target: string;
}

export interface DocGraphOptions {
  /** true なら索引ファイルを書き出す。false/未指定なら drift 検査のみ */
  readonly write?: boolean;
}

function fmString(fm: Frontmatter, key: string): string | undefined {
  const value = fm[key];
  return typeof value === 'string' ? value : undefined;
}

function fmList(fm: Frontmatter, key: string): readonly string[] {
  const value = fm[key];
  return Array.isArray(value) ? value : [];
}

function parseFrontmatter(content: string): Frontmatter | null {
  if (!content.startsWith('---\n')) return null;
  const end = content.indexOf('\n---\n', 4);
  if (end < 0) return null;
  const yaml = content.slice(4, end);
  const fm: Record<string, FrontmatterValue> = {};
  let currentKey: string | null = null;
  for (const line of yaml.split('\n')) {
    if (!line.trim()) continue;
    if (line.startsWith('  - ') && currentKey !== null) {
      const previous = fm[currentKey];
      const list = Array.isArray(previous) ? previous : [];
      list.push(line.slice(4).replace(/\s+#.*$/, '').trim());
      fm[currentKey] = list;
      continue;
    }
    // 数字を含むキー (arc42) も拾う。[a-z_]+ だけだと arc42 が無言で落ちる
    const m = line.match(/^([a-z_][a-z0-9_]*):\s*(.*)$/);
    if (!m) continue;
    const key = m[1];
    const raw = m[2];
    if (key === undefined || raw === undefined) continue;
    currentKey = key;
    // strip inline comments (e.g. "id: foo   # note")
    const value = raw.replace(/\s+#.*$/, '').trim();
    if (value === '' || value === '[]') {
      fm[key] = value === '[]' ? [] : '';
    } else if (value.startsWith('[') && value.endsWith(']')) {
      fm[key] = value
        .slice(1, -1)
        .split(',')
        .map((s) => s.trim())
        .filter(Boolean);
    } else {
      fm[key] = value;
    }
  }
  return fm;
}

function toDoc(fm: Frontmatter, path: string, id: string): Doc {
  return {
    path,
    id,
    title: fmString(fm, 'title'),
    type: fmString(fm, 'type'),
    kind: fmString(fm, 'kind'),
    status: fmString(fm, 'status'),
    canonical: fmString(fm, 'canonical'),
    canonicalFor: fmString(fm, 'canonical_for'),
    supersededBy: fmString(fm, 'superseded_by'),
    accepted: fmString(fm, 'accepted'),
    proposed: fmString(fm, 'proposed'),
    adopted: fmString(fm, 'adopted'),
    dependsOn: fmList(fm, 'depends_on'),
    relatesTo: fmList(fm, 'relates_to'),
    supersedes: fmList(fm, 'supersedes'),
    aliases: fmList(fm, 'aliases'),
  };
}

function escapeId(s: string): string {
  return s.replace(/[^a-zA-Z0-9_-]/g, '_');
}

function nodeLabel(doc: Doc): string {
  const status = doc.status && doc.status !== 'active' ? ` (${doc.status})` : '';
  return `${String(doc.title)}${status}`;
}

function indexById(docs: readonly Doc[]): Map<string, Doc> {
  const byId = new Map<string, Doc>();
  const dupes: string[] = [];
  for (const d of docs) {
    if (!d.id) continue;
    const seen = byId.get(d.id);
    if (seen !== undefined) dupes.push(`  - id="${d.id}": ${[seen.path, d.path].join(' / ')}`);
    else byId.set(d.id, d);
  }
  if (dupes.length > 0) {
    throw new DocGraphError(
      `[docs-graph] frontmatter id 重複検出:\n${dupes.join('\n')}\n\n対処: いずれかの doc を rename or supersede し、id を一意化してください。`,
    );
  }
  return byId;
}

/**
 * `aliases:` (rename 後の link 救済) の索引。retired id を指す参照が恒久 warning に
 * なるのを防ぐ。alias は byId には入れない — グラフのノード/エッジは現存 doc だけで
 * 構成し、自己ループを作らないため。
 */
function indexAliases(docs: readonly Doc[], byId: ReadonlyMap<string, Doc>): Map<string, Doc> {
  const byAlias = new Map<string, Doc>();
  const conflicts: string[] = [];
  for (const d of docs) {
    for (const a of d.aliases) {
      // alias が現存 id を覆い隠すと、本物の dangling ref が見えなくなる
      const collided = byAlias.get(a);
      if (byId.has(a)) conflicts.push(`  - alias="${a}" は現存 doc の id と衝突 (${d.path})`);
      else if (collided !== undefined) conflicts.push(`  - alias="${a}" が重複: ${collided.path} / ${d.path}`);
      else byAlias.set(a, d);
    }
  }
  if (conflicts.length > 0) {
    throw new DocGraphError(
      `[docs-graph] aliases の衝突検出:\n${conflicts.join('\n')}\n\n` +
        `対処: alias は「もう存在しない旧 id」にのみ使い、現存 id と重複させないでください。`,
    );
  }
  return byAlias;
}

/**
 * ADR 番号の一意性。indexById() は id の完全一致しか見ないため `0029-a.md` と
 * `0029-b.md` を素通りさせる。ADR 番号は決定の一次識別子なので id 重複と同格に扱う。
 */
function assertUniqueAdrNumbers(docs: readonly Doc[]): void {
  const byNumber = new Map<string, string[]>();
  for (const d of docs) {
    // frontmatter id ではなく **ファイル名** が索引・相互リンク・人間の呼称の実体
    const m = basename(d.path).match(/^(\d{4})-/);
    const n = m?.[1];
    if (n === undefined || !d.path.includes('/adr/')) continue;
    const paths = byNumber.get(n) ?? [];
    paths.push(d.path);
    byNumber.set(n, paths);
  }
  const dupes = [...byNumber.entries()].filter(([, paths]) => paths.length > 1);
  if (dupes.length > 0) {
    const lines = dupes.map(([n, paths]) => `  - ADR-${n}: ${paths.join(' / ')}`).join('\n');
    throw new DocGraphError(
      `[docs-graph] ADR 番号の重複検出:\n${lines}\n\n` +
        `対処: 後から採番された方を空き番号へ rename し、frontmatter id と\n` +
        `被参照 (docs/ .claude/ 内の grep) をセットで更新してください。\n` +
        `採番前の空き確認は grep -rn "<番号>-" .claude/ docs/ で行うこと\n` +
        `(ls と git log --all は未 commit の予約を検出できない)。`,
    );
  }
}

/**
 * schema (§13.1) + 参照整合性 (§13.7)。ADR は strict (違反は error)、その他は warn。
 */
function validate(
  docs: readonly Doc[],
  byId: ReadonlyMap<string, Doc>,
  byAlias: ReadonlyMap<string, Doc>,
): { errors: string[]; warnings: string[] } {
  const errors: string[] = [];
  const warnings: string[] = [];
  // ADR *決定* doc は番号付き id (adr-NNNN-…) を持つ。ADR 索引などは決定ではない。
  const isAdrDecision = (d: Doc): boolean => /^adr-\d{4}/.test(d.id);

  for (const d of docs) {
    if (!isAdrDecision(d)) continue;
    const tag = `${d.id} (${d.path})`;
    for (const [key, value] of [
      ['id', d.id],
      ['title', d.title],
      ['type', d.type],
      ['status', d.status],
    ] as const) {
      if (!value) errors.push(`[schema] ${tag}: 必須 frontmatter \`${key}\` が無い`);
    }
    if (d.status !== undefined && d.status !== '' && !ADR_STATUSES.has(d.status)) {
      errors.push(`[schema] ${tag}: status="${d.status}" は許可外 (adr: ${[...ADR_STATUSES].join('|')})`);
    }
    if (d.canonical === 'false' && !d.canonicalFor) {
      errors.push(`[schema] ${tag}: canonical:false だが canonical_for が無い`);
    }
  }

  // 参照整合性: 参照先 id は必ず解決できること。
  // 参照元が ADR、または参照先が adr-* id のときは hard error (ADR は append-only 契約)。
  for (const d of docs) {
    const refs: Array<readonly [string, string]> = [];
    for (const t of d.dependsOn) refs.push(['depends_on', t]);
    for (const t of d.relatesTo) refs.push(['relates_to', t]);
    for (const t of d.supersedes) refs.push(['supersedes', t]);
    if (d.supersededBy !== undefined && d.supersededBy !== '') refs.push(['superseded_by', d.supersededBy]);
    if (d.canonicalFor !== undefined && d.canonicalFor !== '') refs.push(['canonical_for', d.canonicalFor]);
    for (const [field, target] of refs) {
      // retired id は aliases: で救済済みなら解決とみなす (typo は救済されない)
      if (byId.has(target) || byAlias.has(target)) continue;
      const msg = `[ref] ${d.id} (${d.path}) .${field} → "${target}" が解決できない`;
      const hard = d.type === 'adr' || /^adr-\d{4}/.test(target);
      (hard ? errors : warnings).push(msg);
    }
  }

  return { errors, warnings };
}

/**
 * 階層検査。索引は `depends_on` (上流 → 下流) の木として出すので、木に繋がらない文書は
 * 「索引に足せば何本でも増やせる」状態に戻ってしまう。よって根になれる種別 (ROOT_KINDS) 以外は
 * 上流を 1 件以上持つか、他の文書の上流であること。`depends_on` の循環も木にならないので落とす。
 */
/** id (現存 id か aliases の旧 id) → 現存 doc。validate / checkHierarchy / 索引で同じ解決規則を使う。 */
type Resolve = (id: string) => Doc | undefined;

function makeResolve(byId: ReadonlyMap<string, Doc>, byAlias: ReadonlyMap<string, Doc>): Resolve {
  return (id) => byId.get(id) ?? byAlias.get(id);
}

/**
 * 階層の辺 (下流 id → 上流 id の集合)。`depends_on` と `superseded_by` は自分の上流、
 * `supersedes` は相手 (旧) の上流が自分。索引の木と循環検査はこの 1 つの辺集合を共有する
 * (木が描くものと検査が落とすものがずれないようにするため)。
 */
function buildUpstreamMap(docs: readonly Doc[], resolve: Resolve): Map<string, Set<string>> {
  const upstream = new Map<string, Set<string>>(docs.map((d) => [d.id, new Set<string>()]));
  const add = (downstream: string, up: string): void => {
    if (downstream === up) return;
    upstream.get(downstream)?.add(up);
  };
  for (const d of docs) {
    for (const up of d.dependsOn) {
      const target = resolve(up);
      if (target !== undefined) add(d.id, target.id);
    }
    if (d.supersededBy !== undefined) {
      const target = resolve(d.supersededBy);
      if (target !== undefined) add(d.id, target.id);
    }
    for (const old of d.supersedes) {
      const target = resolve(old);
      if (target !== undefined) add(target.id, d.id);
    }
  }
  return upstream;
}

function checkHierarchy(
  docs: readonly Doc[],
  upstream: ReadonlyMap<string, ReadonlySet<string>>,
  idlessFiles: readonly string[],
): string[] {
  const errors: string[] = [];
  // id の無い文書はグラフに載らず、索引にだけ現れる = 門を素通りする。ここで落とす。
  for (const path of idlessFiles) {
    errors.push(`[graph] ${path} に frontmatter id が無い (階層に置けない。id と depends_on を書くこと)`);
  }
  const hasDownstream = new Set<string>();
  for (const ups of upstream.values()) for (const up of ups) hasDownstream.add(up);
  for (const d of docs) {
    if (basename(d.path).toLowerCase() === 'readme.md') continue;
    if (ROOT_KINDS.has(d.type ?? '') || ROOT_KINDS.has(d.kind ?? '')) continue;
    if ((upstream.get(d.id)?.size ?? 0) > 0) continue;
    if (hasDownstream.has(d.id)) continue;
    errors.push(
      `[graph] ${d.id} (${d.path}) が階層に無い: depends_on に上流を 1 件以上書くか、他の文書の depends_on から参照されること (索引への追加は登録にならない)`,
    );
  }

  // 循環 (DFS 3 色)。depends_on と supersedes を混ぜた循環も同じ辺集合で検出する
  const state = new Map<string, 'visiting' | 'done'>();
  const stack: string[] = [];
  const visit = (id: string): void => {
    state.set(id, 'visiting');
    stack.push(id);
    for (const up of upstream.get(id) ?? []) {
      const s = state.get(up);
      if (s === 'visiting') {
        errors.push(`[graph] 階層が循環 (depends_on / supersedes): ${[...stack.slice(stack.indexOf(up)), up].join(' → ')}`);
      } else if (s === undefined) {
        visit(up);
      }
    }
    stack.pop();
    state.set(id, 'done');
  };
  for (const d of docs) if (!state.has(d.id)) visit(d.id);
  return errors;
}

function buildMermaid(docs: readonly Doc[], byId: ReadonlyMap<string, Doc>): string {
  const lines: string[] = [];
  lines.push('```mermaid');
  lines.push('graph LR');
  lines.push('  classDef standard fill:#fde68a,stroke:#92400e,color:#111');
  lines.push('  classDef architecture fill:#bfdbfe,stroke:#1e3a8a,color:#111');
  lines.push('  classDef strategy fill:#fbcfe8,stroke:#9d174d,color:#111');
  lines.push('  classDef prd fill:#bbf7d0,stroke:#065f46,color:#111');
  lines.push('  classDef business fill:#a7f3d0,stroke:#064e3b,color:#111');
  lines.push('  classDef adr fill:#c7d2fe,stroke:#3730a3,color:#111');
  lines.push('  classDef runbook fill:#fecaca,stroke:#7f1d1d,color:#111');
  lines.push('  classDef guide fill:#e9d5ff,stroke:#581c87,color:#111');
  lines.push('  classDef design fill:#ddd6fe,stroke:#6d28d9,color:#111');

  for (const d of docs) {
    const id = escapeId(d.id);
    const label = nodeLabel(d).replace(/"/g, "'");
    lines.push(`  ${id}["${label}"]`);
    if (d.type !== undefined && d.type !== '') lines.push(`  class ${id} ${escapeId(d.type)}`);
  }

  // depends_on edges (solid arrow): upstream --> downstream
  for (const d of docs) {
    for (const up of d.dependsOn) {
      if (!byId.has(up)) continue;
      lines.push(`  ${escapeId(up)} ==> ${escapeId(d.id)}`);
    }
  }
  // relates_to edges (dotted, undirected — render one direction to avoid dup)
  const seen = new Set<string>();
  for (const d of docs) {
    for (const rel of d.relatesTo) {
      if (!byId.has(rel)) continue;
      const key = [d.id, rel].sort().join('|');
      if (seen.has(key)) continue;
      seen.add(key);
      lines.push(`  ${escapeId(d.id)} -.- ${escapeId(rel)}`);
    }
  }
  // supersede edges
  for (const d of docs) {
    for (const old of d.supersedes) {
      if (!byId.has(old)) continue;
      lines.push(`  ${escapeId(old)} -. supersedes .-> ${escapeId(d.id)}`);
    }
  }

  lines.push('```');
  return lines.join('\n');
}

function buildSupersedeTable(docs: readonly Doc[]): string | null {
  const rows = docs
    .filter((d) => d.supersededBy !== undefined && d.supersededBy !== '')
    .map((d) => `| ${d.id} | ${String(d.supersededBy)} | ${String(d.status)} |`);
  if (rows.length === 0) return null;
  return ['| 旧 ID | 新 ID | 旧 Status |', '|---|---|---|', ...rows].join('\n');
}

function buildOrphans(docs: readonly Doc[]): string | null {
  const referenced = new Set<string>();
  for (const d of docs) {
    for (const r of d.relatesTo) referenced.add(r);
    for (const r of d.dependsOn) referenced.add(r);
    for (const r of d.supersedes) referenced.add(r);
    if (d.supersededBy !== undefined && d.supersededBy !== '') referenced.add(d.supersededBy);
  }
  const orphans = docs.filter(
    (d) => !referenced.has(d.id) && d.relatesTo.length === 0 && d.dependsOn.length === 0,
  );
  if (orphans.length === 0) return null;
  return [
    '| ID | Type | Path |',
    '|---|---|---|',
    ...orphans.map((d) => `| ${d.id} | ${d.type || '?'} | [\`${d.path}\`](${d.path.replace(/^docs\//, '')}) |`),
  ].join('\n');
}

function buildIndex(docs: readonly Doc[]): string {
  const grouped = new Map<string, Doc[]>();
  for (const d of docs) {
    const t = d.type || 'other';
    const list = grouped.get(t) ?? [];
    list.push(d);
    grouped.set(t, list);
  }
  const order = [
    'standard',
    'strategy',
    'architecture',
    'adr',
    'design',
    'prd',
    'guide',
    'runbook',
    'explanation',
    'business',
    'other',
  ];
  const lines: string[] = [];
  for (const t of order) {
    const list = grouped.get(t);
    if (list === undefined || list.length === 0) continue;
    list.sort((a, b) => a.id.localeCompare(b.id));
    lines.push(`### ${t}`);
    lines.push('');
    for (const d of list) {
      const status = d.status && d.status !== 'active' ? ` _(${d.status})_` : '';
      lines.push(`- **${d.id}**${status} — [${String(d.title)}](${d.path.replace(/^docs\//, '')})`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

/** 「未解決参照 (warn)」節。非 ADR の dangling ref を可視化したまま残す。 */
function buildUnresolvedSection(warnings: readonly string[]): string | null {
  const refWarns = warnings.filter((w) => w.startsWith('[ref]'));
  if (refWarns.length === 0) return null;
  return [
    '## ⚠️ 未解決参照 (warn — Phase 1 で error 昇格予定)',
    '',
    'frontmatter の参照先 id が存在しない箇所。ADR 起因は CI block (error)、それ以外は警告として可視化する。',
    '',
    ...refWarns.map((w) => `- ${w.replace(/^\[ref\] /, '')}`),
  ].join('\n');
}

function adrNumber(id: string): string | null {
  return id.match(/adr-(\d{4})/)?.[1] ?? null;
}

function buildAdrIndexTable(docs: readonly Doc[]): string {
  const adrs = docs
    .filter((d) => d.type === 'adr' && adrNumber(d.id) !== null && d.status !== 'template')
    .sort((a, b) => (adrNumber(a.id) ?? '').localeCompare(adrNumber(b.id) ?? ''));
  const lines = ['| # | タイトル | Status | proposed | accepted |', '|---|---|---|---|---|'];
  for (const d of adrs) {
    const n = adrNumber(d.id) ?? '';
    const file = basename(d.path);
    const accepted = !d.accepted || d.accepted === 'null' ? '—' : d.accepted;
    const proposed = d.proposed || d.adopted || '—';
    // escape pipe chars in titles so the table doesn't break
    const title = String(d.title).replace(/\|/g, '\\|');
    lines.push(`| [${n}](${file}) | ${title} | ${String(d.status)} | ${proposed} | ${accepted} |`);
  }
  return lines.join('\n');
}

function spliceAdrReadme(existing: string, table: string): string {
  const startIdx = existing.indexOf(ADR_INDEX_START);
  const endIdx = existing.indexOf(ADR_INDEX_END);
  if (startIdx < 0 || endIdx < 0 || endIdx < startIdx) {
    throw new DocGraphError(
      `[docs-graph] ${ADR_README_REL} に AUTOGEN マーカーが無い。\n` +
        `  ${ADR_INDEX_START}\n  ...\n  ${ADR_INDEX_END}\n` +
        `を ADR 一覧表の前後に置いてください。`,
    );
  }
  const before = existing.slice(0, startIdx + ADR_INDEX_START.length);
  const after = existing.slice(endIdx);
  return `${before}\n\n${table}\n\n${after}`;
}

function firstHeading(content: string): string | null {
  return content.match(/^#\s+(.+)$/m)?.[1]?.trim() ?? null;
}

function cell(v: string | string[] | undefined): string {
  return String(v ?? '—')
    .replace(/\|/g, '\\|')
    .replace(/\s*\n\s*/g, ' ');
}

/**
 * 索引の「説明」列。文書は冒頭の TL;DR (how-to は When to use)、ディレクトリ README は
 * 「このディレクトリの目的」から取る。一覧性が命なので装飾は剥がし、長ければ切る。
 */
function summaryOf(content: string | undefined): string {
  if (!content) return '';
  const m =
    content.match(/^>\s*\*\*(?:TL;DR|When to use)\*\*:\s*(.+)$/m) ??
    content.match(/^>\s*このディレクトリの目的:\s*(.+)$/m);
  const raw = m?.[1];
  if (raw === undefined) return '';
  const plain = raw
    .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')
    .replace(/\*\*([^*]*)\*\*/g, '$1')
    .replace(/`([^`]*)`/g, '$1')
    .replace(/<[^>]+>/g, '')
    .trim();
  return plain.length > 120 ? `${plain.slice(0, 119)}…` : plain;
}

/**
 * 本文中の相対リンクを行番号付きで拾う。コードフェンス / インラインコード / AUTOGEN 生成区間は
 * 「人が書いた本文」ではないので対象外。
 */
function collectBodyLinks(content: string): Array<{ line: number; target: string }> {
  const out: Array<{ line: number; target: string }> = [];
  let fence: string | null = null;
  let inAutogen = false;
  const lines = content.split('\n');
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (line === undefined) continue;
    const f = line.match(/^\s{0,3}(`{3,}|~{3,})/);
    if (f) {
      const marker = f[1]?.[0];
      if (marker !== undefined) {
        if (fence === null) fence = marker;
        else if (marker === fence) fence = null;
      }
      continue;
    }
    if (fence !== null) continue;
    if (/<!--\s*AUTOGEN[A-Za-z:-]*:start/.test(line)) {
      inAutogen = true;
      continue;
    }
    if (/<!--\s*AUTOGEN[A-Za-z:-]*:end/.test(line)) {
      inAutogen = false;
      continue;
    }
    if (inAutogen) continue;
    const text = line.replace(/`[^`]*`/g, (m) => ' '.repeat(m.length));
    for (const m of text.matchAll(BODY_LINK_RE)) {
      const target = m[1];
      if (target !== undefined) out.push({ line: i + 1, target });
    }
  }
  return out;
}

export class DocGraphCheck implements Check {
  readonly name = 'docs-graph';

  readonly #write: boolean;
  /** 直近の run() が出した非ブロッキング警告 (元コードの console.warn 相当) */
  #warnings: string[] = [];

  constructor(options: DocGraphOptions = {}) {
    this.#write = options.write === true;
  }

  get warnings(): readonly string[] {
    return this.#warnings;
  }

  async run(ctx: CheckContext): Promise<readonly Violation[]> {
    this.#warnings = [];
    const docsDir = join(ctx.targetRoot, 'docs');
    if (!existsSync(docsDir)) {
      return [{ severity: 'cannot-check', message: `[docs-graph] ${ctx.targetRoot} に docs/ が無い` }];
    }
    try {
      return await new DocGraph(ctx.targetRoot, this.#write, this.#warnings).run();
    } catch (err) {
      if (err instanceof DocGraphError) return [{ severity: 'violation', message: err.message }];
      const message = err instanceof Error ? err.message : String(err);
      return [{ severity: 'cannot-check', message: `[docs-graph] 検査に失敗: ${message}` }];
    }
  }
}

/** 1 回分の実行。targetRoot 由来のパスを抱えて元スクリプトの main() を再現する。 */
class DocGraph {
  readonly #root: string;
  readonly #docsDir: string;
  readonly #output: string;
  readonly #adrReadme: string;
  readonly #write: boolean;
  readonly #warnings: string[];

  constructor(root: string, write: boolean, warnings: string[]) {
    this.#root = root;
    this.#docsDir = join(root, 'docs');
    this.#output = join(this.#docsDir, 'dependencies.md');
    this.#adrReadme = join(this.#docsDir, 'adr', 'README.md');
    this.#write = write;
    this.#warnings = warnings;
  }

  async run(): Promise<readonly Violation[]> {
    const allFiles = await this.#walk(this.#docsDir);
    const docs: Doc[] = [];
    const idlessFiles: string[] = [];
    for (const f of allFiles) {
      if (f === this.#output) continue;
      const content = await readFile(f, 'utf8');
      const fm = parseFrontmatter(content);
      const id = fm === null ? undefined : fmString(fm, 'id');
      if (fm === null || id === undefined || id === '') {
        // README (索引の stub) と生成物は文書ではない。それ以外の id 無しは階層検査で落とす
        if (basename(f).toLowerCase() !== 'readme.md' && !content.startsWith('<!-- AUTOGENERATED')) {
          idlessFiles.push(relative(this.#root, f));
        }
        continue;
      }
      docs.push(toDoc(fm, relative(this.#root, f), id));
    }
    docs.sort((a, b) => a.id.localeCompare(b.id));

    const byId = indexById(docs); // throws on duplicate id
    assertUniqueAdrNumbers(docs); // throws on duplicate ADR number (id 一致でなくても検出)
    const byAlias = indexAliases(docs, byId); // throws on alias/id collision
    const resolve = makeResolve(byId, byAlias);
    const { errors, warnings } = validate(docs, byId, byAlias);
    const upstream = buildUpstreamMap(docs, resolve);
    const hierarchyErrors = checkHierarchy(docs, upstream, idlessFiles.sort());

    const depsOut = this.#buildDependencies(docs, byId, warnings);

    // ---- ADR README index ----
    const adrTable = buildAdrIndexTable(docs);
    // ADR が 1 本も無いツリーでは ADR 索引を作らない。ADR があるのに README が無ければ落とす。
    const hasAdrs = docs.some((d) => d.type === 'adr');
    if (hasAdrs && !existsSync(this.#adrReadme)) {
      throw new DocGraphError(
        `[docs-graph] ${ADR_README_REL} が無い (ADR があるツリーでは ADR 索引が必須). Run: --write`,
      );
    }
    const adrExisting = await readFile(this.#adrReadme, 'utf8').catch(() => null);
    const adrOut = adrExisting === null ? null : spliceAdrReadme(adrExisting, adrTable);
    const adrOverride: Array<[string, string]> = adrOut === null ? [] : [[this.#adrReadme, adrOut]];

    // ---- per-directory README indexes ----
    // 2 パス: pass 2 が pass 1 の生成物 (新規 stub の title / ADR splice) を見ることで
    // 出力が不動点になり、--write 直後の --check が通る。
    const graph = { resolve, upstream };
    const pass1 = await this.#buildDirIndexes(allFiles, new Map(adrOverride), graph);
    const ov = new Map<string, string>([...adrOverride, ...pass1.indexes.map((di): [string, string] => [di.readmePath, di.desired])]);
    const pass2 = await this.#buildDirIndexes(allFiles, ov, graph);
    const dirIndexes = pass2.indexes.map((di) => ({
      ...di,
      existing: di.readmePath === this.#adrReadme ? adrOut : di.existing,
    }));

    warnings.push(...pass2.arc42Warnings);
    this.#warnings.push(...warnings);

    if (this.#write) {
      return this.#runWrite(depsOut, adrOut, dirIndexes, errors, hierarchyErrors);
    }
    return this.#runCheck(allFiles, depsOut, adrExisting, adrOut, dirIndexes, errors, hierarchyErrors);
  }

  async #runWrite(
    depsOut: string,
    adrOut: string | null,
    dirIndexes: readonly DirIndex[],
    errors: readonly string[],
    hierarchyErrors: readonly string[],
  ): Promise<readonly Violation[]> {
    if (errors.length > 0) return errors.map((message) => ({ severity: 'violation', message }));
    await writeFile(this.#output, `${depsOut}\n`, 'utf8');
    if (adrOut !== null) await writeFile(this.#adrReadme, adrOut, 'utf8');
    for (const di of dirIndexes) {
      if (di.existing === null || di.existing !== di.desired) await writeFile(di.readmePath, di.desired, 'utf8');
    }
    // 本文リンク検査と階層検査は「書いた後に」見る (索引 README を作る前に落とすと、
    // 生成器が自分で直せるリンク切れで deadlock するため)。--write では非ブロッキング。
    const linkProblems = await this.#checkBodyLinks(await this.#walk(this.#docsDir));
    for (const p of linkProblems) {
      this.#warnings.push(`[link] ${p.file}:${p.line} → ${p.target} (解決先が存在しない。--check では ERROR)`);
    }
    for (const e of hierarchyErrors) this.#warnings.push(`${e} (--check では ERROR)`);
    return [];
  }

  async #runCheck(
    allFiles: readonly string[],
    depsOut: string,
    adrExisting: string | null,
    adrOut: string | null,
    dirIndexes: readonly DirIndex[],
    errors: readonly string[],
    hierarchyErrors: readonly string[],
  ): Promise<readonly Violation[]> {
    const drift: Violation[] = [];
    const existingDeps = await readFile(this.#output, 'utf8').catch(() => '');
    if (stripGeneratedAt(existingDeps) !== stripGeneratedAt(depsOut)) {
      drift.push({ severity: 'violation', message: '[docs-graph] 依存グラフが out of date. Run: --write', file: OUTPUT_REL });
    }
    if (adrOut !== null && adrExisting !== null && adrExisting.trim() !== adrOut.trim()) {
      drift.push({ severity: 'violation', message: '[docs-graph] ADR 索引が out of date. Run: --write', file: ADR_README_REL });
    }
    for (const di of dirIndexes) {
      if (di.readmePath === this.#adrReadme && adrOut !== null && adrExisting !== null) {
        if (adrOut.trim() !== di.desired.trim() && adrExisting.trim() !== di.desired.trim()) {
          drift.push({ severity: 'violation', message: '[docs-graph] 索引が out of date. Run: --write', file: di.rel });
        }
        continue;
      }
      if (di.existing === null) {
        drift.push({
          severity: 'violation',
          message: '[docs-graph] ディレクトリ README + 索引が無い. Run: --write',
          file: di.rel,
        });
      } else if (di.existing.trim() !== di.desired.trim()) {
        drift.push({ severity: 'violation', message: '[docs-graph] 索引が out of date. Run: --write', file: di.rel });
      }
    }

    const linkViolations: Violation[] = (await this.#checkBodyLinks(allFiles)).map((p) => ({
      severity: 'violation',
      message: `[link] → ${p.target} (解決先が存在しない)`,
      file: p.file,
      line: p.line,
    }));
    const hardErrors: Violation[] = [...errors, ...hierarchyErrors].map((message) => ({ severity: 'violation', message }));
    return [...drift, ...hardErrors, ...linkViolations];
  }

  #buildDependencies(docs: readonly Doc[], byId: ReadonlyMap<string, Doc>, warnings: readonly string[]): string {
    const mermaid = buildMermaid(docs, byId);
    const supersede = buildSupersedeTable(docs);
    const orphans = buildOrphans(docs);
    const index = buildIndex(docs);
    const unresolved = buildUnresolvedSection(warnings);
    const now = new Date().toISOString().split('T')[0] ?? '';
    return [
      AUTOGENERATED_HEADER,
      '',
      '# Docs 依存関係グラフ',
      '',
      `> 自動生成: ${now} (UTC) / ソース: 各 \`docs/**/*.md\` の frontmatter`,
      `> 規約: docs/guides/01-document-taxonomy.md 参照`,
      `> 再生成: \`node scripts/generate-docs-graph.mjs --write\``,
      '',
      '## 凡例',
      '',
      '- **太矢印 `==>`**: `depends_on` (上流 → 下流、上流が変わったら下流レビュー必須)',
      '- **点線 `-.-`**: `relates_to` (双方向、緩い結び)',
      '- **点線矢印 `-. supersedes .->`**: 旧 → 新 (ADR の置き換え)',
      '- ノード色は `type` を表す (standard / architecture / strategy / prd / business / adr / runbook / guide / design)',
      '',
      '## グラフ',
      '',
      mermaid,
      '',
      '## ドキュメント一覧 (type 別)',
      '',
      index,
      supersede ? `## Supersede チェーン\n\n${supersede}\n` : '',
      unresolved ? `${unresolved}\n` : '',
      orphans
        ? `## 孤立ドキュメント (誰からも参照されていない)\n\n${orphans}\n`
        : '## 孤立ドキュメント\n\n_該当なし_\n',
    ]
      .filter(Boolean)
      .join('\n');
  }

  async #walk(dir: string): Promise<string[]> {
    const entries = await readdir(dir, { withFileTypes: true });
    const files = await Promise.all(
      entries.map(async (e): Promise<string[]> => {
        const p = join(dir, e.name);
        if (e.isDirectory()) return this.#walk(p);
        if (e.isFile() && p.endsWith('.md')) return [p];
        return [];
      }),
    );
    return files.flat();
  }

  /** 解決できない本文リンクを返す (空配列 = 緑)。 */
  async #checkBodyLinks(files: readonly string[]): Promise<LinkProblem[]> {
    const problems: LinkProblem[] = [];
    for (const f of [...files].sort()) {
      const content = await readFile(f, 'utf8').catch(() => null);
      if (content === null) continue;
      if (content.startsWith('<!-- AUTOGENERATED')) continue; // ファイル全体が生成物
      for (const { line, target } of collectBodyLinks(content)) {
        if (/^[a-z][a-z0-9+.-]*:/i.test(target)) continue; // http(s): / mailto: など外部
        if (target.startsWith('#')) continue; // 同一ファイル内アンカー
        const pathPart = target.split('#')[0];
        if (pathPart === undefined || pathPart === '') continue;
        const abs = target.startsWith('/')
          ? join(this.#root, decodeURIComponent(pathPart))
          : resolve(dirname(f), decodeURIComponent(pathPart));
        if (!existsSync(abs)) problems.push({ file: relative(this.#root, f), line, target });
      }
    }
    return problems;
  }

  #spliceDirReadme(dir: string, existing: string | null, table: string): string {
    const block = `${DIR_INDEX_START}\n\n${table}\n\n${DIR_INDEX_END}`;
    if (existing === null) {
      const slug = relative(this.#docsDir, dir).replace(/[\\/]/g, '-') || 'docs';
      return [
        '---',
        `id: ${slug}-index`,
        `title: ${basename(dir)} — 索引`,
        'type: index',
        'status: active',
        'owners: [eng]',
        '---',
        '',
        `# ${basename(dir)}`,
        '',
        '> このディレクトリの目的: (要記入)',
        '',
        '## 索引',
        '',
        block,
        '',
      ].join('\n');
    }
    const st = existing.indexOf(DIR_INDEX_START);
    const en = existing.indexOf(DIR_INDEX_END);
    if (st >= 0 && en > st) {
      return `${existing.slice(0, st)}${block}${existing.slice(en + DIR_INDEX_END.length)}`;
    }
    return `${existing.trimEnd()}\n\n## 索引\n\n${block}\n`;
  }

  /**
   * arc42 章別の索引。docs/ と docs/design/ の README はフォルダ順ではなくこの形で出す。
   * 1 章 = 1 行。章に文書が無ければ「未作成」と書き、穴がそのまま TODO に見えるようにする。
   */
  #buildArc42Table(
    from: string,
    entries: readonly string[],
    meta: ReadonlyMap<string, DocMeta>,
    arc42Warnings: string[],
    elsewhereDocs: readonly string[],
  ): string {
    const byChapter = new Map<number, string[]>(ARC42_CHAPTERS.map(([n]) => [n, []]));
    const outside: string[] = [];
    const unassigned: string[] = [];
    for (const f of entries) {
      const entry = meta.get(f);
      if (entry === undefined) continue;
      const link = `[${cell(entry.title)}](${relative(from, f).split(sep).join('/')})`;
      // 生成物 (dependencies.md 等) は設計書ではないので章を持たない。警告もしない。
      if (entry.content.startsWith('<!-- AUTOGENERATED')) {
        outside.push(link);
        continue;
      }
      const rawChapter = entry.fm['arc42'];
      const chapter = rawChapter === undefined ? null : Number(rawChapter);
      const bucket = chapter === null ? undefined : byChapter.get(chapter);
      if (bucket !== undefined) bucket.push(link);
      else if (chapter !== null) unassigned.push(link);
      else if (NON_ARC42_KINDS.has(fmString(entry.fm, 'kind') ?? '')) outside.push(link);
      else {
        unassigned.push(link);
        arc42Warnings.push(
          `${relative(this.#root, f)} に frontmatter arc42 が無い (章未割当。kind: ${entry.fm['kind'] ?? '—'})`,
        );
      }
    }
    // このディレクトリ配下に無い章でも、他所に実在することがある。その場合は「未作成」ではなく
    // 実在する側のディレクトリ README へのリンクを 1 個出す。本当に 1 本も無い章だけ _未作成_。
    const elsewhereByChapter = new Map<number, Set<string>>(ARC42_CHAPTERS.map(([n]) => [n, new Set<string>()]));
    for (const f of elsewhereDocs) {
      const entry = meta.get(f);
      if (entry === undefined || entry.content.startsWith('<!-- AUTOGENERATED')) continue;
      const rawChapter = entry.fm['arc42'];
      if (rawChapter === undefined) continue;
      const bucket = elsewhereByChapter.get(Number(rawChapter));
      if (bucket === undefined) continue;
      const dir = dirname(f);
      const rel = relative(from, join(dir, 'README.md')).split(sep).join('/');
      const label = `${relative(this.#docsDir, dir).split(sep).join('/') || 'docs'}/`;
      bucket.add(`→ [${label}](${rel})`);
    }
    const rows = ARC42_CHAPTERS.map(([n, en, ja]) => {
      const docs = byChapter.get(n) ?? [];
      const other = [...(elsewhereByChapter.get(n) ?? [])].sort();
      const cellText = [...docs, ...other].join(' · ') || '_未作成_';
      return `| **§${n} ${en}** (${ja}) | ${cellText} |`;
    });
    if (outside.length) {
      rows.push(
        `| arc42 章外 (tutorial / guide / explanation / proposal / runbook / tasks) | ${outside.join(' · ')} |`,
      );
    }
    if (unassigned.length) rows.push(`| **章未割当** (frontmatter に arc42 が無い) | ${unassigned.join(' · ')} |`);
    return ['| arc42 章 | 文書 |', '|---|---|', ...rows].join('\n');
  }

  /**
   * ディレクトリごとの README 索引。overrides は「ディスクではなくこの内容を使う」指定で、
   * ADR splice 後の README と前パスの生成物を渡すことで 1 回の --write が不動点になる。
   */
  async #buildDirIndexes(
    allFilesRaw: readonly string[],
    overrides: ReadonlyMap<string, string>,
    graph: { readonly resolve: Resolve; readonly upstream: ReadonlyMap<string, ReadonlySet<string>> },
  ): Promise<DirIndexResult> {
    const meta = new Map<string, DocMeta>();
    for (const f of new Set([...allFilesRaw, ...overrides.keys()])) {
      const content = overrides.get(f) ?? (await readFile(f, 'utf8').catch(() => null));
      if (content === null) continue;
      const fm = parseFrontmatter(content) ?? {};
      meta.set(f, { fm, content, title: fmString(fm, 'title') || firstHeading(content) || basename(f, '.md') });
    }
    const isReadme = (f: string): boolean => basename(f).toLowerCase() === 'readme.md';
    // dependencies.md は本スクリプトの生成物。索引に載せると「1 回目の --write ではまだ
    // 存在せず 2 回目で行が増える」= --write 直後の --check が落ちる不動点崩れになる。
    const allFiles = allFilesRaw.filter((f) => f !== this.#output);
    const own = new Map<string, string[]>(); // dir -> own non-README md files
    const children = new Map<string, Set<string>>(); // dir -> Set(child dirs)
    for (const f of allFiles) {
      if (!isReadme(f)) {
        const list = own.get(dirname(f)) ?? [];
        list.push(f);
        own.set(dirname(f), list);
      }
      let d = dirname(f);
      while (d !== this.#docsDir) {
        const parent = dirname(d);
        const set = children.get(parent) ?? new Set<string>();
        set.add(d);
        children.set(parent, set);
        d = parent;
      }
    }
    // README 索引を持つ条件: docs ルート / 直下に doc がある / doc を持つ子孫ディレクトリがある
    // (例: design/detail は domain/ しか持たないが、親の索引からリンクされるので README が要る)
    const indexed = (d: string): boolean =>
      d === this.#docsDir ||
      (own.get(d) ?? []).length > 0 ||
      [...(children.get(d) ?? [])].some((c) => indexed(c));
    const descendantRows = (from: string, d: string): string[] => {
      const rows: string[] = [];
      for (const c of [...(children.get(d) ?? [])].sort()) {
        if (indexed(c)) {
          const relDir = relative(from, c);
          const readme = meta.get(join(c, 'README.md'));
          const t = readme?.title ?? `${basename(c)} — 索引`;
          const summary = summaryOf(readme?.content);
          rows.push(`- [${relDir}/](${relDir}/README.md) — **${cell(t)}**${summary ? ` — ${cell(summary)}` : ''}`);
        } else {
          rows.push(...descendantRows(from, c)); // pass-through dir: list its indexed descendants
        }
      }
      return rows;
    };
    /**
     * ディレクトリ直下の文書を階層の木で出す (親 = 上流)。辺は checkHierarchy と同じ
     * graph.upstream (depends_on / superseded_by / supersedes) を使う。
     * 同じディレクトリ内の上流の下にぶら下げ、ディレクトリ外の depends_on は「← 上流」で示す。
     * 親が複数ある文書は最初の親の下に 1 回だけ出し、他の親の下では「上に記載」と書く
     * (菱形で部分木が指数的に増えるのを防ぐ)。循環は検査側で落とすが、索引からは消さない。
     */
    const treeRows = (dir: string, entries: readonly string[]): string[] => {
      const fmOf = (f: string): Frontmatter => meta.get(f)?.fm ?? {};
      const idOf = (f: string): string | undefined => fmString(fmOf(f), 'id');
      const inDir = new Map<string, string>(); // 現存 id → このディレクトリのファイル
      for (const f of entries) {
        const id = idOf(f);
        if (id !== undefined && id !== '') inDir.set(id, f);
      }
      const kids = new Map<string, string[]>();
      const hasParent = new Set<string>();
      for (const f of entries) {
        const id = idOf(f);
        if (id === undefined) continue;
        for (const up of graph.upstream.get(id) ?? []) {
          const p = inDir.get(up);
          if (p === undefined || p === f) continue;
          const list = kids.get(p) ?? [];
          if (!list.includes(f)) list.push(f);
          kids.set(p, list);
          hasParent.add(f);
        }
      }
      const label = (f: string): string => {
        const entry = meta.get(f);
        const fm = fmOf(f);
        const type = fmString(fm, 'type');
        const status = fmString(fm, 'status');
        const summary = summaryOf(entry?.content);
        const outside = fmList(fm, 'depends_on')
          .map((up) => ({ up, target: graph.resolve(up) }))
          .filter(({ target }) => target === undefined || !inDir.has(target.id))
          .map(({ up, target }) =>
            target === undefined
              ? `${up} (未解決)`
              : `[${target.id}](${relative(dir, join(this.#root, target.path)).split(sep).join('/')})`,
          );
        return [
          `[${basename(f)}](${basename(f)}) — **${cell(entry?.title)}**`,
          type ? ` \`${cell(type)}\`` : '',
          status && status !== 'active' ? ` _(${cell(status)})_` : '',
          summary ? ` — ${cell(summary)}` : '',
          outside.length > 0 ? ` ← 上流: ${outside.join(', ')}` : '',
        ].join('');
      };
      const rendered = new Set<string>();
      const render = (f: string, depth: number): string[] => {
        const indent = '  '.repeat(depth);
        if (rendered.has(f)) return [`${indent}- [${basename(f)}](${basename(f)}) (上に記載)`];
        rendered.add(f);
        const out = [`${indent}- ${label(f)}`];
        for (const c of kids.get(f) ?? []) out.push(...render(c, depth + 1));
        return out;
      };
      const rows: string[] = [];
      for (const f of entries) if (!hasParent.has(f)) rows.push(...render(f, 0));
      // 循環だけで構成される文書は根が無い。索引から消さず根として出す
      for (const f of entries) if (!rendered.has(f)) rows.push(...render(f, 0));
      return rows;
    };
    const TREE_LEGEND =
      '> 階層は frontmatter `depends_on` から生成 (親 = 上流、子 = その下流)。「← 上流」は他ディレクトリの上流。' +
      '上流も下流も無い文書は `docs-check` で落ちる (一覧に足すだけでは登録にならない)。';
    // 章別索引を出すディレクトリ。docs/design/ はツリーに在るときだけ対象にする
    // (無いのに README だけ作ると空フォルダが生える)。
    const chapterDirs = [this.#docsDir, join(this.#docsDir, 'design')].filter(
      (d) => d === this.#docsDir || existsSync(d),
    );
    const descendantDocs = (d: string): string[] =>
      allFiles.filter((f) => !isReadme(f) && f.startsWith(d + sep));
    const results: DirIndex[] = [];
    const arc42Warnings: string[] = [];
    const allDirs = new Set([this.#docsDir, ...chapterDirs, ...own.keys(), ...children.keys()]);
    for (const dir of [...allDirs].sort((a, b) => a.localeCompare(b))) {
      const isChapterDir = chapterDirs.includes(dir);
      if (!indexed(dir) && !isChapterDir) continue;
      const readmePath = join(dir, 'README.md');
      const isAdrDir = dir === join(this.#docsDir, 'adr');
      const rows = descendantRows(dir, dir);
      const entries = (own.get(dir) ?? [])
        // docs/adr: 番号付き ADR は上の ADR 索引表に載っているので二重に出さない
        .filter((f) => {
          if (!isAdrDir) return true;
          const fm = meta.get(f)?.fm;
          if (fm === undefined) return true;
          return !(
            fmString(fm, 'type') === 'adr' &&
            adrNumber(fmString(fm, 'id') ?? '') !== null &&
            fmString(fm, 'status') !== 'template'
          );
        })
        // 拡張子を外して比べる。"catalog-pricing.md" < "catalog.md" ('-' < '.') になり、
        // 分割元が分割先の後ろに沈むため
        .sort((a, b) => basename(a, '.md').localeCompare(basename(b, '.md')));
      const docRows = treeRows(dir, entries.filter((f) => meta.has(f)));
      if (docRows.length > 0) rows.unshift(TREE_LEGEND, ''); // 凡例は文書の行があるときだけ
      rows.push(...docRows);
      // 章別索引は arc42 を持つ文書が配下に 1 本でもあるときだけ。
      // 0 本で 12 章の _未作成_ を並べても情報が無い
      const hasChapterDocs = descendantDocs(dir).some((f) => meta.get(f)?.fm['arc42'] !== undefined);
      const table =
        isChapterDir && hasChapterDocs
          ? this.#buildArc42Table(
              dir,
              descendantDocs(dir).sort(),
              meta,
              arc42Warnings,
              allFiles.filter((f) => !isReadme(f) && !f.startsWith(dir + sep)).sort(),
            )
          : rows.join('\n');
      if (!isChapterDir && rows.length === 0) continue;
      // `existing` は常にディスクの実体を見る。overrides (pass1 の desired) を existing に使うと
      // pass2 で existing === desired となり --write が索引を書かず --check も drift を見逃す。
      const existing = await readFile(readmePath, 'utf8').catch(() => null);
      results.push({
        readmePath,
        rel: relative(this.#root, readmePath),
        existing,
        desired: this.#spliceDirReadme(dir, existing, table),
      });
    }
    return { indexes: results, arc42Warnings };
  }
}
