// node --test dist/checks/DocGraphCheck.v4.test.js
// 新しい構成 (docs/person・ai・client) の repo での、索引と参照の検査 (DocGraphCheck の v4 対応)。
// 旧い構成 (docs/adr/ に ADR 索引) の挙動が変わらないことも、同じ検査で並べて確かめる。
// 一時ディレクトリに 3 区分・複数のまとまり・複数の年の ADR を持つ構成を作る。
// 文書のつながり (テスト仕様 04 の G1〜G8) の行は、`[TST-nnn]` で始まる名前の it が持つ。
import { existsSync, globSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, posix } from 'node:path';
import { after, beforeEach, describe, it } from 'node:test';
import assert from 'node:assert/strict';

import { DocsCheckCommand, DocsGraphCommand } from '../cli/commands/checkCommands.js';
import { ExitCode } from '../core/ExitCode.js';
import { IGETA_ROOT } from '../core/Paths.js';
import type { Violation } from '../core/Report.js';
import { DocGraphCheck } from './DocGraphCheck.js';

const workspaces: string[] = [];

after(() => {
  for (const dir of workspaces) rmSync(dir, { recursive: true, force: true });
});

function makeRoot(): string {
  const root = mkdtempSync(join(tmpdir(), 'igeta-graph-v4-'));
  workspaces.push(root);
  return root;
}

function write(root: string, relPath: string, lines: readonly string[]): void {
  const target = join(root, relPath);
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, `${lines.join('\n')}\n`);
}

interface DocOptions {
  readonly type?: string;
  readonly arc42?: number;
  readonly status?: string;
  readonly dependsOn?: readonly string[];
  readonly relatesTo?: readonly string[];
  readonly context?: string;
  readonly body?: readonly string[];
}

/** 索引と参照の検査が読む frontmatter と、本文の行 */
function doc(id: string, kind: string, options: DocOptions = {}): string[] {
  const { type = 'design', arc42, status = 'active', dependsOn = [], relatesTo = [], context, body = [] } = options;
  return [
    '---',
    `id: ${id}`,
    `title: ${id} の題名`,
    `type: ${type}`,
    `kind: ${kind}`,
    ...(arc42 === undefined ? [] : [`arc42: ${arc42}`]),
    ...(context === undefined ? [] : [`context: ${context}`]),
    `status: ${status}`,
    'owners: [eng]',
    `depends_on: [${dependsOn.join(', ')}]`,
    `relates_to: [${relatesTo.join(', ')}]`,
    '---',
    '',
    `# ${id}`,
    '',
    ...body,
  ];
}

function adr(number: string, slug: string, status: string, extra: readonly string[] = []): string[] {
  return doc(`adr-${number}-${slug}`, 'adr', { type: 'adr', arc42: 9, status, body: extra });
}

/** ADR 索引と、ディレクトリ索引の 2 区間を持つ decisions/README.md (雛形と同じ形) */
const DECISIONS_README: readonly string[] = [
  '---',
  'id: decisions-index',
  'title: decisions — 索引',
  'type: index',
  'status: active',
  'owners: [eng]',
  '---',
  '',
  '# decisions',
  '',
  '> このディレクトリの目的: 決定の記録。',
  '',
  '## 索引',
  '',
  '<!-- AUTOGEN:adr-index:start — generated by scripts/generate-docs-graph.mjs, do not edit by hand -->',
  '<!-- AUTOGEN:adr-index:end -->',
  '',
  '<!-- AUTOGEN:dir-index:start — generated by scripts/generate-docs-graph.mjs, do not edit by hand -->',
  '<!-- AUTOGEN:dir-index:end -->',
];

/** 決まりの表 (最後の列が 状態)。決まりの行は、最初のセルが ID の形だけの行 */
function decisionTable(rows: ReadonlyArray<readonly [id: string, text: string, state: string]>): string[] {
  return ['| ID | 決まり | 状態 |', '|---|---|---|', ...rows.map(([id, text, state]) => `| ${id} | ${text} | ${state} |`)];
}

/** 要件の文書。accepted・amended の ADR は、要件の決まりの行が `ADR-NNNN` の形で引く (G4) */
function writeRequirements(root: string, citedAdrs: readonly string[]): void {
  write(
    root,
    'docs/person/requirements/01-requirements.md',
    doc('requirements', 'requirements', {
      arc42: 1,
      body: decisionTable(citedAdrs.map((number, index) => [`REQ-${String(index + 1).padStart(3, '0')}`, `ADR-${number} の決定を反映する`, '決定'])),
    }),
  );
}

/** tentative-index の区間を持つ決定台帳 (雛形と同じ形。DEC・OPEN の表は、状態の列が無いので決まりの表ではない) */
const DECISION_LOG: readonly string[] = [
  '---',
  'id: decisions',
  'title: 決定台帳',
  'type: decision-log',
  'kind: decision-log',
  'status: active',
  'owners: [eng]',
  'depends_on: []',
  'relates_to: [map]',
  '---',
  '',
  '# 決定台帳',
  '',
  '## 1. 決定 (DEC)',
  '',
  '| ID | 日付 | 決定 |',
  '|---|---|---|',
  '| DEC-001 | 2026-10-02 | 決めたこと |',
  '',
  '## 3. 仮・未決の一覧 (自動生成)',
  '',
  '<!-- AUTOGEN:tentative-index:start — generated by scripts/generate-docs-graph.mjs, do not edit by hand -->',
  '<!-- AUTOGEN:tentative-index:end -->',
];

/** 3 区分・まとまり 2 つ・年 2 つの ADR を持つ、正しい構成 */
function writeValidTree(root: string): void {
  writeRequirements(root, ['0001', '0002']);
  write(root, 'docs/person/design/shared/00-map.md', doc('map', 'map'));
  write(
    root,
    'docs/person/design/reservation/00-map.md',
    doc('reservation-map', 'context-map', { dependsOn: ['map'], context: 'reservation' }),
  );
  write(
    root,
    'docs/person/design/payment/00-map.md',
    doc('payment-map', 'context-map', { dependsOn: ['map'], context: 'payment' }),
  );
  write(root, 'docs/person/decisions/README.md', DECISIONS_README);
  write(root, 'docs/person/decisions/2025/0001-use-postgres.md', adr('0001', 'use-postgres', 'accepted'));
  write(root, 'docs/person/decisions/2026/0002-queue.md', adr('0002', 'queue', 'amended'));
  write(root, 'docs/person/decisions/2026/0003-cache.md', adr('0003', 'cache', 'proposed'));
  write(
    root,
    'docs/ai/specs/reservation/api/01-reserve.md',
    doc('reservation-api', 'api-spec', { arc42: 5, dependsOn: ['reservation-map'], context: 'reservation' }),
  );
  write(root, 'docs/ai/handbook/how-to/01-setup.md', doc('setup', 'guide', { type: 'guide' }));
  write(root, 'docs/client/delivery/spec-v1/01-overview.md', doc('delivery-overview', 'delivery-chapter', { dependsOn: ['requirements'] }));
}

interface RunResult {
  readonly violations: readonly Violation[];
  readonly warnings: readonly string[];
  readonly detail: string;
}

async function run(root: string, mode: 'write' | 'check'): Promise<RunResult> {
  const check = new DocGraphCheck(mode === 'write' ? { write: true } : {});
  const violations = await check.run({ targetRoot: root, igetaRoot: IGETA_ROOT });
  return {
    violations,
    warnings: check.warnings,
    detail: [...violations.map((violation) => `${violation.file ?? ''} ${violation.message}`), ...check.warnings].join('\n'),
  };
}

/** 新規の木は、1 回目の write が README を作り、それが 2 回目のグラフの節点になるので、2 回で収束する */
async function converge(root: string): Promise<void> {
  assert.deepEqual((await run(root, 'write')).violations, []);
  assert.deepEqual((await run(root, 'write')).violations, []);
}

const read = (root: string, relPath: string): string => readFileSync(join(root, relPath), 'utf8');

/** 文書の中で、prefix で始まる最初の行の行番号 (1 始まり)。無ければ 0 */
const lineOf = (root: string, relPath: string, prefix: string): number =>
  read(root, relPath).split('\n').findIndex((line) => line.startsWith(prefix)) + 1;

describe('DocGraphCheck v4: ADR 索引は docs/person/decisions/README.md に出す', () => {
  let root: string;
  beforeEach(async () => {
    root = makeRoot();
    writeValidTree(root);
    await converge(root);
  });

  it('[TST-104] ADR の表は decisions/README.md に、仮・未決の行は決定台帳に、パスの順で出る。0 件なら _該当なし_', async () => {
    // G5: 年をまたぐ ADR が、decisions/ からの相対パスのリンクで 1 つの表に並ぶ。docs/adr/ は作らない
    const readme = read(root, 'docs/person/decisions/README.md');
    assert.match(readme, /\| \[0001\]\(2025\/0001-use-postgres\.md\) \| adr-0001-use-postgres の題名 \| accepted \|/);
    assert.match(readme, /\| \[0002\]\(2026\/0002-queue\.md\) \| adr-0002-queue の題名 \| amended \|/);
    assert.match(readme, /\| \[0003\]\(2026\/0003-cache\.md\) \| adr-0003-cache の題名 \| proposed \|/);
    assert.ok(readme.indexOf('[0001]') < readme.indexOf('[0002]') && readme.indexOf('[0002]') < readme.indexOf('[0003]'));
    assert.equal(existsSync(join(root, 'docs', 'adr')), false, 'docs/adr/ を勝手に作っている');

    // G6: 仮の行と未決の行を持つ人の文書 2 本。台帳の一覧は、docs/ からのパスの順 (design/ が requirements/ より前)
    const bookingPath = 'docs/person/design/reservation/flows/01-booking.md';
    const requirementsPath = 'docs/person/requirements/01-requirements.md';
    const writeLog = (state102: string, state003: string): void => {
      write(root, 'docs/person/decisions/01-decisions.md', DECISION_LOG);
      write(
        root,
        bookingPath,
        doc('reservation-booking', 'business-flow', {
          context: 'reservation',
          dependsOn: ['reservation-map'],
          body: decisionTable([
            ['BF-101', '予約を確定する', '決定'],
            ['BF-102', 'キャンセル料は 0 円', state102],
          ]),
        }),
      );
      write(
        root,
        requirementsPath,
        doc('requirements', 'requirements', {
          arc42: 1,
          body: decisionTable([
            ['REQ-001', 'ADR-0001 の決定を反映する', '決定'],
            ['REQ-002', 'ADR-0002 の決定を反映する', '決定'],
            ['REQ-003', '予約は 15 分で失効する', state003],
          ]),
        }),
      );
    };
    writeLog('未決', '仮');
    await converge(root);
    const log = read(root, 'docs/person/decisions/01-decisions.md');
    const region = log.slice(log.indexOf('AUTOGEN:tentative-index:start'), log.indexOf('AUTOGEN:tentative-index:end'));
    assert.deepEqual(
      region.split('\n').filter((line) => line.startsWith('|')),
      [
        '| 対象 ID | 状態 | 場所 | 決まり |',
        '|---|---|---|---|',
        `| reservation-booking/BF-102 | 未決 | [${bookingPath}:${lineOf(root, bookingPath, '| BF-102')}](../design/reservation/flows/01-booking.md#L${lineOf(root, bookingPath, '| BF-102')}) | キャンセル料は 0 円 |`,
        `| requirements/REQ-003 | 仮 | [${requirementsPath}:${lineOf(root, requirementsPath, '| REQ-003')}](../requirements/01-requirements.md#L${lineOf(root, requirementsPath, '| REQ-003')}) | 予約は 15 分で失効する |`,
      ],
    );
    assert.deepEqual((await run(root, 'check')).violations, []);

    // 仮・未決が 0 件になれば、_該当なし_
    writeLog('決定', '決定');
    await converge(root);
    const emptied = read(root, 'docs/person/decisions/01-decisions.md');
    assert.match(emptied.slice(emptied.indexOf('AUTOGEN:tentative-index:start')), /-->\n\n_該当なし_\n\n<!-- AUTOGEN:tentative-index:end/);
    assert.deepEqual((await run(root, 'check')).violations, []);
  });

  it('書いた直後の木は、check で違反も警告も出ない (索引・年のフォルダの README・依存グラフが収束している)', async () => {
    const result = await run(root, 'check');
    assert.deepEqual(result.violations, [], result.detail);
    assert.deepEqual(result.warnings, []);
  });

  it('decisions/README.md の ADR 索引とディレクトリ索引は共存する。ADR を足して write しても、古い ADR 索引に戻らない', async () => {
    const before = read(root, 'docs/person/decisions/README.md');
    assert.match(before, /AUTOGEN:dir-index:start[\s\S]*\[2025\/\]\(2025\/README\.md\)[\s\S]*\[2026\/\]\(2026\/README\.md\)[\s\S]*AUTOGEN:dir-index:end/);
    write(root, 'docs/person/decisions/2026/0004-search.md', adr('0004', 'search', 'accepted'));
    writeRequirements(root, ['0001', '0002', '0004']);
    await converge(root);
    const after = read(root, 'docs/person/decisions/README.md');
    assert.match(after, /\| \[0004\]\(2026\/0004-search\.md\) \| adr-0004-search の題名 \| accepted \|/);
    assert.match(after, /AUTOGEN:dir-index:start[\s\S]*\[2026\/\]\(2026\/README\.md\)/);
    // 年のフォルダの README にも、その年の ADR が出る
    assert.match(read(root, 'docs/person/decisions/2026/README.md'), /\[0004-search\.md\]\(0004-search\.md\)/);
    const result = await run(root, 'check');
    assert.deepEqual(result.violations, [], result.detail);
  });

  it('ADR のタイトルを直して再生成しないと、check は ADR 索引が古いと落ちる (file は新しい場所)', async () => {
    write(
      root,
      'docs/person/decisions/2025/0001-use-postgres.md',
      doc('adr-0001-use-postgres', 'adr', { type: 'adr', arc42: 9, status: 'accepted' }).map((line) =>
        line.startsWith('title:') ? 'title: ADR-0001 PostgreSQL を使う (改題)' : line,
      ),
    );
    const result = await run(root, 'check');
    assert.ok(
      result.violations.some(
        (violation) => violation.file === 'docs/person/decisions/README.md' && /ADR 索引が out of date/.test(violation.message),
      ),
      result.detail,
    );
    assert.ok(!result.violations.some((violation) => violation.file === 'docs/adr/README.md'));
  });

  it('[TST-307] ADR があるのに decisions/README.md が無い・adr-index の区間が無いと、新しい場所を名指しして落ちる', async () => {
    const cases: ReadonlyArray<{ readonly name: string; readonly prepare: () => void; readonly message: RegExp }> = [
      {
        name: 'README.md が無い (docs/adr/README.md は求めない)',
        prepare: () => rmSync(join(root, 'docs', 'person', 'decisions', 'README.md')),
        message: /docs\/person\/decisions\/README\.md が無い/,
      },
      {
        name: 'adr-index の区間が無い',
        prepare: () => write(root, 'docs/person/decisions/README.md', DECISIONS_README.filter((line) => !line.includes('adr-index'))),
        message: /docs\/person\/decisions\/README\.md に AUTOGEN マーカーが無い/,
      },
    ];
    for (const { name, prepare, message } of cases) {
      prepare();
      for (const mode of ['write', 'check'] as const) {
        const result = await run(root, mode);
        assert.equal(result.violations.length, 1, `${name} (${mode}): ${result.detail}`);
        assert.match(result.violations[0]?.message ?? '', message, `${name} (${mode})`);
        assert.doesNotMatch(result.violations[0]?.message ?? '', /docs\/adr\/README\.md/, `${name} (${mode})`);
      }
    }
  });

  it('ADR が 1 本も無い新しい構成は、decisions/README.md を求めず、docs/adr/ も作らない', async () => {
    const empty = makeRoot();
    write(empty, 'docs/person/requirements/01-requirements.md', doc('requirements', 'requirements', { arc42: 1 }));
    write(empty, 'docs/ai/handbook/how-to/01-setup.md', doc('setup', 'guide', { type: 'guide' }));
    await converge(empty);
    assert.equal(existsSync(join(empty, 'docs', 'adr')), false);
    assert.equal(existsSync(join(empty, 'docs', 'person', 'decisions')), false);
    const result = await run(empty, 'check');
    assert.deepEqual(result.violations, [], result.detail);
  });

  it('年のフォルダをまたいで同じ番号の ADR があれば、番号の重複で落ちる', async () => {
    write(root, 'docs/person/decisions/2025/0002-other.md', adr('0005', 'other', 'accepted'));
    const result = await run(root, 'check');
    assert.equal(result.violations.length, 1, result.detail);
    const message = result.violations[0]?.message ?? '';
    assert.match(message, /ADR 番号の重複検出:\n {2}- ADR-0002: /);
    assert.ok(message.includes('docs/person/decisions/2025/0002-other.md') && message.includes('docs/person/decisions/2026/0002-queue.md'), message);
  });

  it('新しい構成では ADR の status に amended が使える。語彙の外の値は落ちる', async () => {
    write(root, 'docs/person/decisions/2026/0003-cache.md', adr('0003', 'cache', 'adopted'));
    const result = await run(root, 'write');
    assert.equal(result.violations.length, 1, result.detail);
    assert.match(result.violations[0]?.message ?? '', /status="adopted" は許可外 \(adr: .*amended/);
  });
});

describe('DocGraphCheck: 旧い構成の ADR 索引は変えない', () => {
  function writeLegacyTree(root: string): void {
    write(root, 'docs/product/requirements.md', doc('requirements', 'requirements', { arc42: 1 }));
    write(root, 'docs/adr/0001-x.md', adr('0001', 'x', 'accepted'));
    write(root, 'docs/adr/README.md', [
      '---', 'id: adr-index', 'title: ADR — 索引', 'type: index', 'status: active', 'owners: [eng]', '---', '',
      '# adr', '', '## 索引', '',
      '<!-- AUTOGEN:adr-index:start — generated by scripts/generate-docs-graph.mjs, do not edit by hand -->',
      '<!-- AUTOGEN:adr-index:end -->',
    ]);
  }

  it('docs/adr/README.md に、ファイル名のリンクで索引を出し、docs/person/ は作らない', async () => {
    const root = makeRoot();
    writeLegacyTree(root);
    await converge(root);
    assert.match(read(root, 'docs/adr/README.md'), /\| \[0001\]\(0001-x\.md\) \| adr-0001-x の題名 \| accepted \|/);
    assert.equal(existsSync(join(root, 'docs', 'person')), false);
    assert.deepEqual((await run(root, 'check')).violations, []);
  });

  it('ADR があるのに docs/adr/README.md が無ければ、これまでの文言で落ちる', async () => {
    const root = makeRoot();
    writeLegacyTree(root);
    rmSync(join(root, 'docs', 'adr', 'README.md'));
    const result = await run(root, 'check');
    assert.equal(result.violations.length, 1, result.detail);
    assert.equal(result.violations[0]?.message, '[docs-graph] docs/adr/README.md が無い (ADR があるツリーでは ADR 索引が必須). Run: --write');
  });

  it('amended は旧い構成の語彙に無く、これまでどおり許可外', async () => {
    const root = makeRoot();
    writeLegacyTree(root);
    write(root, 'docs/adr/0002-y.md', adr('0002', 'y', 'amended'));
    const result = await run(root, 'write');
    assert.equal(result.violations.length, 1, result.detail);
    assert.match(result.violations[0]?.message ?? '', /status="amended" は許可外 \(adr: proposed\|accepted\|deprecated\|superseded\|rejected\|template\)/);
  });

  it('旧い構成の docs/adr/ の番号の重複は、これまでどおり落ちる', async () => {
    const root = makeRoot();
    writeLegacyTree(root);
    write(root, 'docs/adr/0001-other.md', adr('0009', 'other', 'accepted'));
    const result = await run(root, 'check');
    assert.equal(result.violations.length, 1, result.detail);
    assert.match(result.violations[0]?.message ?? '', /ADR 番号の重複検出[\s\S]*ADR-0001/);
  });
});

// ---------------------------------------------------------------------------
// 文書のつながり (テスト仕様 04 の G1〜G4・G6〜G8)
// ---------------------------------------------------------------------------

type Role = 'person' | 'ai' | 'client';
/** 参照の書き方 (G2)。(a) depends_on・relates_to (b) リンク・画像 (c) 参照の形の定義 (d) 修飾 ID */
type How = 'depends_on' | 'relates_to' | 'link' | 'image' | 'definition' | 'qualified-id';

interface RoleDoc {
  readonly id: string;
  /** repo 直下からのパス */
  readonly path: string;
  readonly kind: string;
  readonly type: string;
}

/** 役割ごとの、参照する側 (src) と参照される側 (dst)。どれも置き場所の型どおりで、依存の木の根になれる kind */
const ROLE_DOCS: Readonly<Record<Role, { readonly src: RoleDoc; readonly dst: RoleDoc }>> = {
  person: {
    src: { id: 'person-src', path: 'docs/person/requirements/01-src.md', kind: 'requirements', type: 'design' },
    dst: { id: 'person-dst', path: 'docs/person/requirements/02-dst.md', kind: 'requirements', type: 'design' },
  },
  ai: {
    src: { id: 'ai-src', path: 'docs/ai/handbook/how-to/01-src.md', kind: 'guide', type: 'guide' },
    dst: { id: 'ai-dst', path: 'docs/ai/handbook/how-to/02-dst.md', kind: 'guide', type: 'guide' },
  },
  client: {
    src: { id: 'client-src', path: 'docs/client/delivery/spec-v1/01-src.md', kind: 'delivery-chapter', type: 'design' },
    dst: { id: 'client-dst', path: 'docs/client/delivery/spec-v1/02-dst.md', kind: 'delivery-chapter', type: 'design' },
  },
};

const ALL_HOWS: readonly How[] = ['depends_on', 'relates_to', 'link', 'image', 'definition', 'qualified-id'];

const linkFrom = (from: RoleDoc, to: RoleDoc): string => posix.relative(posix.dirname(from.path), to.path);

/** from が、targets を hows の書き方で全部指す文書。extraBody は本文の最後に足す行 */
function refDoc(from: RoleDoc, targets: readonly RoleDoc[], hows: readonly How[], extraBody: readonly string[] = []): string[] {
  const body: string[] = [];
  for (const target of targets) {
    const href = linkFrom(from, target);
    if (hows.includes('link')) body.push(`[${target.id}](${href})`, '');
    if (hows.includes('image')) body.push(`![${target.id}](${href})`, '');
    if (hows.includes('definition')) body.push(`[${target.id}][ref-${target.id}]`, '', `[ref-${target.id}]: ${href}`, '');
    if (hows.includes('qualified-id')) body.push(`${target.id}/REQ-001 を見る`, '');
  }
  return doc(from.id, from.kind, {
    type: from.type,
    dependsOn: hows.includes('depends_on') ? targets.map((target) => target.id) : [],
    relatesTo: hows.includes('relates_to') ? targets.map((target) => target.id) : [],
    body: [...body, ...extraBody],
  });
}

const plainDoc = (target: RoleDoc): string[] => doc(target.id, target.kind, { type: target.type });

/** 人の地図と、ADR 索引つきの decisions/README.md。文書のつながりの検査の土台 */
function writeBase(root: string): void {
  write(root, 'docs/person/design/shared/00-map.md', doc('map', 'map'));
  write(root, 'docs/person/decisions/README.md', DECISIONS_README);
}

const tagged = (result: RunResult, tag: string): readonly Violation[] =>
  result.violations.filter((violation) => violation.message.startsWith(`[${tag}]`));

/** 木を書き、索引を収束させて、検査 (docs-check の索引と参照の部分) の結果を返す */
async function checkedAfterConverge(root: string): Promise<RunResult> {
  await converge(root);
  return run(root, 'check');
}

async function runCommand(
  command: DocsGraphCommand | DocsCheckCommand,
  root: string,
): Promise<{ code: ExitCode; stdout: string[]; stderr: string[] }> {
  const stdout: string[] = [];
  const stderr: string[] = [];
  const code = await command.run(['--root', root], {
    cwd: root,
    igetaRoot: IGETA_ROOT,
    stdout: (line) => stdout.push(line),
    stderr: (line) => stderr.push(line),
  });
  return { code, stdout, stderr: stderr.flatMap((line) => line.split('\n')) };
}

describe('DocGraphCheck v4: 文書のつながり (依存の向き・届く・ADR の引用・索引の書き方)', () => {
  it('[TST-101] person は person だけ・ai は person と ai・client は 3 つとも、4 種の参照で指してよい。コードフェンス・生成区間・インラインコードの中のリンクと脚注の定義、パスの一部に見える修飾 ID は数えない', async () => {
    const root = makeRoot();
    const { person, ai, client } = ROLE_DOCS;
    const aiLink = `[ai の手引き](${linkFrom(person.src, ai.dst)})`;
    // 数えないもの: コードフェンス・生成区間・インラインコードの中のリンクと、脚注の定義 (`[^名前]:`。参照の形の定義ではない)。
    // 修飾 ID に数えないもの: 直前が `/` (パスの一部)・英数字・`-` (G2 の (d))
    const hidden = [
      '```markdown',
      aiLink,
      '```',
      '',
      '<!-- AUTOGEN:note:start -->',
      aiLink,
      '<!-- AUTOGEN:note:end -->',
      '',
      `コードの例: \`${aiLink}\``,
      '',
      '文の最後に脚注を付ける。[^1]',
      '',
      `[^1]: ${linkFrom(person.src, ai.dst)}`,
      '',
      `パス: docs/ai/handbook/how-to/${ai.dst.id}/REQ-001`,
      `英数字の後ろ: 9${ai.dst.id}/REQ-001`,
      `ハイフンの後ろ: (-${ai.dst.id}/REQ-001)`,
    ];
    write(root, person.src.path, refDoc(person.src, [person.dst], ALL_HOWS, hidden));
    write(root, ai.src.path, refDoc(ai.src, [person.dst, ai.dst], ALL_HOWS));
    write(root, client.src.path, refDoc(client.src, [person.dst, ai.dst, client.dst], ALL_HOWS));
    for (const target of [person.dst, ai.dst, client.dst]) write(root, target.path, plainDoc(target));
    const result = await checkedAfterConverge(root);
    assert.deepEqual(result.violations, [], result.detail);
  });

  it('[TST-102] ai/specs/ の文書は、別の ai/specs/ の文書を経ても person/ に届く。depends_on に external: が混ざっても、行末にコメントがあってもよい', async () => {
    const root = makeRoot();
    writeBase(root);
    // 行末のコメント (空白と # から後ろ) は、`#` の後ろに空白が無くても値に含めない。配列の 1 行ずつの形も同じ
    write(
      root,
      'docs/ai/specs/shared/01-crosscutting.md',
      doc('crosscutting', 'crosscutting', { arc42: 8, dependsOn: ['map'] }).flatMap((line) => (line === 'depends_on: [map]' ? ['depends_on:', '  - map #メモ'] : [line])),
    );
    write(
      root,
      'docs/ai/specs/reservation/api/01-reserve.md',
      doc('reservation-api', 'api-spec', { arc42: 5, context: 'reservation', dependsOn: ['crosscutting', 'external:x'] }).map((line) =>
        line.startsWith('depends_on:') ? `${line}  #メモ` : line,
      ),
    );
    const result = await checkedAfterConverge(root);
    assert.deepEqual(result.violations, [], result.detail);
  });

  it('[TST-103] accepted の ADR は要件の決まりの行が ADR-0003 と引いていれば通り (列の数が見出しと合わない行も決まりの行)、proposed・superseded の ADR は引かれていなくてよい', async () => {
    const root = makeRoot();
    writeBase(root);
    writeRequirements(root, ['0003']);
    // 列の数が見出しと合わない行も、決まりの行として数える (列のずれは 03 の P3 が違反にする)。ADR-0006 は、この行からだけ引く
    write(
      root,
      'docs/person/requirements/02-extra-column.md',
      doc('requirements-extra', 'requirements', { arc42: 1, body: [...decisionTable([['REQ-101', '別の決まり', '決定']]), '| REQ-102 | ADR-0006 の決定を反映する | 決定 | 余分な列 |'] }),
    );
    write(root, 'docs/person/decisions/2026/0003-cache.md', adr('0003', 'cache', 'accepted'));
    write(root, 'docs/person/decisions/2026/0004-search.md', adr('0004', 'search', 'proposed'));
    write(root, 'docs/person/decisions/2026/0005-old.md', adr('0005', 'old', 'superseded'));
    write(root, 'docs/person/decisions/2026/0006-queue.md', adr('0006', 'queue', 'accepted'));
    const result = await checkedAfterConverge(root);
    assert.deepEqual(result.violations, [], result.detail);
  });

  it('[TST-105] 新しい構成の索引に読み手の表示と凡例は出ず、person・ai・client の README.md は決まった目的の行で作られる', async () => {
    const root = makeRoot();
    write(root, 'docs/person/requirements/01-requirements.md', doc('requirements', 'requirements', { arc42: 1 }));
    write(root, 'docs/ai/handbook/how-to/01-setup.md', doc('setup', 'guide', { type: 'guide' }));
    write(root, 'docs/client/delivery/spec-v1/01-overview.md', doc('overview', 'delivery-chapter', { dependsOn: ['requirements'] }));
    await converge(root);
    const purposes: ReadonlyArray<readonly [folder: string, purpose: string]> = [
      ['person', '人が確定させる文書。確定の前に人が全部読んで承認する (要件・設計・決定)'],
      ['ai', 'AI が書き、評価する AI が確定させる文書 (作り方の仕様と、作業の手引き)。人の承認は要らない (`humanPaths` で足したパスを除く)'],
      ['client', '顧客と合意して渡す文書 (提出物の章と提案書)。渡す前に人が全部読む'],
    ];
    for (const [folder, purpose] of purposes) {
      assert.ok(read(root, `docs/${folder}/README.md`).split('\n').includes(`> このディレクトリの目的: ${purpose}`), folder);
    }
    const readmes = globSync('docs/**/README.md', { cwd: root });
    assert.ok(readmes.length >= 4, readmes.join(', '));
    for (const readme of readmes) assert.doesNotMatch(read(root, readme), /_\(読み手:/, readme);
    assert.deepEqual((await run(root, 'check')).violations, []);
  });

  it('[TST-106] 人 → AI のリンクと届かない ai/specs/ の文書があっても、docs-graph は警告を出して索引を書き (終了コード 0)、続く docs-check は違反にする', async () => {
    const root = makeRoot();
    write(root, 'AGENTS.md', ['# AGENTS.md', '', '決まりは docs/person/、作り方は docs/ai/ を読む。']);
    // 人の承認が要るパス (ADR-0008 決定 1) の全部に持ち主を付ける (`init` が置く CODEOWNERS と同じ 10 行)
    write(
      root,
      '.github/CODEOWNERS',
      ['/docs/person/', '/docs/client/', '/.github/', '/CODEOWNERS', '/docs/CODEOWNERS', '/.igeta.json', '/.igeta-version', '/.claude/', 'AGENTS.md', 'CLAUDE.md'].map(
        (pattern) => `${pattern} @owners`,
      ),
    );
    const { person, ai } = ROLE_DOCS;
    write(root, person.src.path, refDoc(person.src, [ai.dst], ['link']));
    write(root, ai.dst.path, plainDoc(ai.dst));
    write(root, 'docs/ai/specs/shared/01-crosscutting.md', doc('crosscutting', 'crosscutting', { arc42: 8, dependsOn: [ai.dst.id] }));

    let written = await runCommand(new DocsGraphCommand(), root);
    written = await runCommand(new DocsGraphCommand(), root);
    assert.equal(written.code, ExitCode.Ok, written.stderr.join('\n'));
    const warnings = written.stderr.filter((line) => line.startsWith('WARN '));
    assert.equal(warnings.filter((line) => line.includes('[direction]')).length, 1, written.stderr.join('\n'));
    assert.equal(warnings.filter((line) => line.includes('[reach]')).length, 1, written.stderr.join('\n'));
    assert.equal(existsSync(join(root, 'docs', 'dependencies.md')), true);
    assert.equal(existsSync(join(root, 'docs', 'person', 'README.md')), true);

    const checked = await runCommand(new DocsCheckCommand(), root);
    assert.equal(checked.code, ExitCode.Violation, checked.stderr.join('\n'));
    const violations = checked.stderr.filter((line) => line.startsWith('VIOLATION '));
    assert.equal(violations.length, 2, checked.stderr.join('\n'));
    assert.ok(violations.some((line) => line.includes('[direction]')) && violations.some((line) => line.includes('[reach]')), violations.join('\n'));
  });

  it('[TST-111] 決定台帳だけがある木で docs-graph を 3 回回しても終了コード 0 で、2 回目と 3 回目の生成物は変わらず、decisions/README.md は adr-index の区間を持つ。ADR を足すと、印を手で足さなくても区間の表に載る', async () => {
    const root = makeRoot();
    write(root, 'docs/person/decisions/01-decisions.md', DECISION_LOG);
    /** docs/ の下の Markdown の全部。dependencies.md の生成日の行は毎日変わるので落とす */
    const generated = (): Record<string, string> =>
      Object.fromEntries(
        globSync('docs/**/*.md', { cwd: root })
          .map((path) => path.split('\\').join('/'))
          .sort()
          .map((path) => [path, read(root, path).replace(/^> 自動生成: .*$/m, '> 自動生成: <date>')] as const),
      );
    const snapshots: Array<Record<string, string>> = [];
    for (let time = 1; time <= 3; time += 1) {
      const written = await runCommand(new DocsGraphCommand(), root);
      assert.equal(written.code, ExitCode.Ok, `${time} 回目: ${written.stderr.join('\n')}`);
      snapshots.push(generated());
    }
    assert.deepEqual(snapshots[2], snapshots[1], '3 回目が、2 回目の生成物を変えた');
    const readme = read(root, 'docs/person/decisions/README.md');
    assert.ok(readme.includes('<!-- AUTOGEN:adr-index:start') && readme.includes('<!-- AUTOGEN:adr-index:end -->'), 'adr-index の区間が無い');

    // ADR を 1 本足す。README.md の印は、手で足さない
    write(root, 'docs/person/decisions/2026/0001-use-postgres.md', adr('0001', 'use-postgres', 'proposed'));
    const added = await runCommand(new DocsGraphCommand(), root);
    assert.equal(added.code, ExitCode.Ok, added.stderr.join('\n'));
    assert.match(read(root, 'docs/person/decisions/README.md'), /\| \[0001\]\(2026\/0001-use-postgres\.md\) \| adr-0001-use-postgres の題名 \| proposed \|/);
  });

  it('[TST-301] person の文書が ai の文書を、depends_on・relates_to・本文のリンク・参照の形の定義・修飾 ID のどれで指しても違反 (参照元の行)。frontmatter の行末にコメントがあっても、値のある項目の次の行の字下げした配列でも、修飾 ID を斜体・太字・インラインコードで囲んでも同じ', async () => {
    const { person, ai } = ROLE_DOCS;
    const dependsOnLine = `depends_on: [${ai.dst.id}]`;
    /** 修飾 ID を decorate で囲んだ 1 行を、本文に持つ文書 */
    const qualified = (decorate: (id: string) => string): string[] =>
      doc(person.src.id, person.src.kind, { type: person.src.type, body: [`参照: ${decorate(`${ai.dst.id}/REQ-001`)}`] });
    const cases: ReadonlyArray<{ readonly name: string; readonly lines: readonly string[]; readonly linePrefix: string }> = [
      { name: 'depends_on', lines: refDoc(person.src, [ai.dst], ['depends_on']), linePrefix: 'depends_on:' },
      { name: 'relates_to', lines: refDoc(person.src, [ai.dst], ['relates_to']), linePrefix: 'relates_to:' },
      { name: '本文のリンク', lines: refDoc(person.src, [ai.dst], ['link']), linePrefix: `[${ai.dst.id}](` },
      { name: '参照の形の定義', lines: refDoc(person.src, [ai.dst], ['definition']), linePrefix: `[ref-${ai.dst.id}]: ` },
      { name: '修飾 ID', lines: refDoc(person.src, [ai.dst], ['qualified-id']), linePrefix: `${ai.dst.id}/REQ-001` },
      // 行末のコメントは、索引を作るときと同じく、空白と # から後ろを捨てる。# の後ろに空白が無くても同じ
      {
        name: 'depends_on の行末のコメント',
        lines: refDoc(person.src, [ai.dst], ['depends_on']).map((line) => (line === dependsOnLine ? `${line}  #メモ` : line)),
        linePrefix: 'depends_on:',
      },
      {
        name: '配列の 1 行ずつの形と行末のコメント',
        lines: refDoc(person.src, [ai.dst], ['depends_on']).flatMap((line) => (line === dependsOnLine ? ['depends_on:', `  - ${ai.dst.id} #メモ`] : [line])),
        linePrefix: `  - ${ai.dst.id}`,
      },
      // 値のある項目の次の行の字下げした `- y` も、その項目の配列に足す (索引が辺にするのと同じ)
      {
        name: '値のある depends_on の次の行に、字下げした - y を続ける',
        lines: refDoc(person.src, [person.dst], ['depends_on']).flatMap((line) =>
          line === `depends_on: [${person.dst.id}]` ? [line, `  - ${ai.dst.id}`] : [line],
        ),
        linePrefix: `  - ${ai.dst.id}`,
      },
      // 修飾 ID を囲む記号は、直前の文字を英数字・/・- にしない
      { name: '修飾 ID を斜体で囲む', lines: qualified((id) => `_${id}_`), linePrefix: '参照: ' },
      { name: '修飾 ID を太字で囲む', lines: qualified((id) => `**${id}**`), linePrefix: '参照: ' },
      { name: '修飾 ID をインラインコードで囲む', lines: qualified((id) => `\`${id}\``), linePrefix: '参照: ' },
    ];
    for (const { name, lines, linePrefix } of cases) {
      const root = makeRoot();
      write(root, person.src.path, lines);
      write(root, person.dst.path, plainDoc(person.dst));
      write(root, ai.dst.path, plainDoc(ai.dst));
      const found = tagged(await checkedAfterConverge(root), 'direction');
      assert.equal(found.length, 1, name);
      assert.equal(found[0]?.file, person.src.path, name);
      assert.equal(found[0]?.line, lineOf(root, person.src.path, linePrefix), name);
      assert.match(found[0]?.message ?? '', /person の文書が ai の文書を指している/, name);
    }
  });

  it('[TST-302] person の文書のリンク先が docs/ai・docs/ai/specs/ (フォルダ)・無いファイル docs/ai/x.md・docs/client/ でも違反', async () => {
    const { person, client } = ROLE_DOCS;
    const root = makeRoot();
    write(root, person.dst.path, plainDoc(person.dst));
    write(root, 'docs/ai/specs/shared/01-crosscutting.md', doc('crosscutting', 'crosscutting', { arc42: 8, dependsOn: [person.dst.id] }));
    write(root, client.dst.path, plainDoc(client.dst));
    for (const target of ['../../ai', '../../ai/specs/', '../../ai/x.md', '../../client/']) {
      write(root, person.src.path, doc(person.src.id, person.src.kind, { type: person.src.type, body: [`[リンク](${target})`] }));
      const found = tagged(await checkedAfterConverge(root), 'direction');
      assert.equal(found.length, 1, target);
      assert.equal(found[0]?.file, person.src.path, target);
      assert.equal(found[0]?.line, lineOf(root, person.src.path, '[リンク]('), target);
    }
  });

  it('[TST-303] ai の文書が client の文書を、5 通りのどの書き方で指しても違反', async () => {
    const { ai, client } = ROLE_DOCS;
    const cases: ReadonlyArray<readonly [how: How, linePrefix: string]> = [
      ['depends_on', 'depends_on:'],
      ['relates_to', 'relates_to:'],
      ['link', `[${client.dst.id}](`],
      ['definition', `[ref-${client.dst.id}]: `],
      ['qualified-id', `${client.dst.id}/REQ-001`],
    ];
    for (const [how, linePrefix] of cases) {
      const root = makeRoot();
      write(root, ai.src.path, refDoc(ai.src, [client.dst], [how]));
      write(root, client.dst.path, plainDoc(client.dst));
      const found = tagged(await checkedAfterConverge(root), 'direction');
      assert.equal(found.length, 1, how);
      assert.equal(found[0]?.file, ai.src.path, how);
      assert.equal(found[0]?.line, lineOf(root, ai.src.path, linePrefix), how);
      assert.match(found[0]?.message ?? '', /ai の文書が client の文書を指している/, how);
    }
  });

  it('[TST-304] ai/specs/ の文書の depends_on が空・ai の文書だけを回る・解決できない id だけ・external: だけなら、person/ に届かず違反', async () => {
    const crosscutting = 'docs/ai/specs/shared/01-crosscutting.md';
    const testPlan = 'docs/ai/specs/shared/02-test-plan.md';
    const cases: ReadonlyArray<{
      readonly name: string;
      readonly crosscutting: readonly string[];
      readonly testPlan: readonly string[];
      /** 届かないと言われる文書 */
      readonly unreached: readonly string[];
    }> = [
      { name: 'depends_on が空', crosscutting: [], testPlan: ['crosscutting', 'map'], unreached: [crosscutting] },
      { name: 'ai の文書だけを回る', crosscutting: ['test-plan'], testPlan: ['crosscutting'], unreached: [crosscutting, testPlan] },
      { name: '解決できない id だけ', crosscutting: ['no-such-doc'], testPlan: ['crosscutting', 'map'], unreached: [crosscutting] },
      { name: 'external: だけ', crosscutting: ['external:x'], testPlan: ['crosscutting', 'map'], unreached: [crosscutting] },
    ];
    for (const { name, crosscutting: crosscuttingDeps, testPlan: testPlanDeps, unreached } of cases) {
      const root = makeRoot();
      writeBase(root);
      write(root, crosscutting, doc('crosscutting', 'crosscutting', { arc42: 8, dependsOn: crosscuttingDeps }));
      write(root, testPlan, doc('test-plan', 'test-plan', { arc42: 10, dependsOn: testPlanDeps }));
      const found = tagged(await checkedAfterConverge(root), 'reach');
      assert.deepEqual(found.map((violation) => violation.file).sort(), [...unreached].sort(), name);
      for (const violation of found) {
        assert.equal(violation.line, lineOf(root, violation.file ?? '', 'depends_on:'), name);
      }
    }
  });

  it('[TST-305] accepted の ADR が、どこからも・ai の文書からだけ・廃の行からだけ・関連の表や地の文からだけ・ADR-0003・0006 の 0006・小文字の adr-0003 でしか引かれていなければ違反 (amended の ADR も同じ)', async () => {
    const adrFile = (number: string, slug: string): string => `docs/person/decisions/2026/${number}-${slug}.md`;
    const aiRows = decisionTable([['AI-001', 'ADR-0003 に従う', '決定']]);
    const cases: ReadonlyArray<{
      readonly name: string;
      readonly adrNumber: string;
      readonly requirements: readonly string[];
      readonly status?: string;
      readonly extra?: () => (root: string) => void;
    }> = [
      { name: 'amended の ADR がどこからも引かれない', adrNumber: '0003', status: 'amended', requirements: decisionTable([['REQ-001', '別の決まり', '決定']]) },
      { name: 'どこからも引かれない', adrNumber: '0003', requirements: decisionTable([['REQ-001', '別の決まり', '決定']]) },
      {
        name: 'ai の文書からだけ',
        adrNumber: '0003',
        requirements: decisionTable([['REQ-001', '別の決まり', '決定']]),
        extra: () => (root) => write(root, 'docs/ai/handbook/how-to/01-setup.md', doc('setup', 'guide', { type: 'guide', body: aiRows })),
      },
      { name: '廃の行からだけ', adrNumber: '0003', requirements: decisionTable([['REQ-001', 'ADR-0003 の古い決まり', '廃']]) },
      {
        name: '関連の表や地の文からだけ',
        adrNumber: '0003',
        requirements: [
          ...decisionTable([['REQ-001', '別の決まり', '決定']]),
          '',
          'この決まりは ADR-0003 による。',
          '',
          '## 関連',
          '',
          '| 区分 | 文書 | 対応 ID |',
          '|---|---|---|',
          '| 上流 | ADR-0003 | ADR-0003 |',
        ],
      },
      { name: 'ADR-0003・0006 の 0006', adrNumber: '0006', requirements: decisionTable([['REQ-001', 'ADR-0003・0006 を反映する', '決定']]) },
      { name: '小文字の adr-0003', adrNumber: '0003', requirements: decisionTable([['REQ-001', 'adr-0003 を反映する', '決定']]) },
    ];
    for (const { name, adrNumber, requirements, status = 'accepted', extra } of cases) {
      const root = makeRoot();
      writeBase(root);
      write(root, 'docs/person/requirements/01-requirements.md', doc('requirements', 'requirements', { arc42: 1, body: requirements }));
      write(root, adrFile(adrNumber, 'cache'), adr(adrNumber, 'cache', status));
      extra?.()(root);
      const found = tagged(await checkedAfterConverge(root), 'adr');
      assert.equal(found.length, 1, `${name}: ${found.map((violation) => violation.message).join(' / ')}`);
      assert.equal(found[0]?.file, adrFile(adrNumber, 'cache'), name);
      assert.equal(found[0]?.line, 1, name);
      assert.match(found[0]?.message ?? '', new RegExp(`ADR-${adrNumber}`), name);
    }
  });

  it('[TST-306] ai の文書の 仮 の行は決定台帳の一覧に出ず、ai/ だけを変えても person/・client/ の下は 1 バイトも変わらない', async () => {
    const root = makeRoot();
    writeBase(root);
    write(root, 'docs/person/decisions/01-decisions.md', DECISION_LOG);
    write(
      root,
      'docs/person/requirements/01-requirements.md',
      doc('requirements', 'requirements', { arc42: 1, body: decisionTable([['REQ-001', '予約は 15 分で失効する', '仮']]) }),
    );
    write(root, 'docs/client/delivery/spec-v1/01-overview.md', doc('delivery-overview', 'delivery-chapter', { dependsOn: ['requirements'] }));
    const writeAi = (rows: ReadonlyArray<readonly [id: string, text: string, state: string]>): void =>
      write(root, 'docs/ai/specs/shared/01-crosscutting.md', doc('crosscutting', 'crosscutting', { arc42: 8, dependsOn: ['map'], body: decisionTable(rows) }));
    const snapshot = (): Record<string, string> =>
      Object.fromEntries(
        globSync('docs/{person,client}/**/*.md', { cwd: root })
          .map((path) => path.split('\\').join('/'))
          .sort()
          .map((path) => [path, read(root, path)] as const),
      );

    writeAi([['AI-001', 'キャッシュは 5 分', '仮']]);
    assert.deepEqual((await checkedAfterConverge(root)).violations, []);
    const log = read(root, 'docs/person/decisions/01-decisions.md');
    assert.match(log, /\| requirements\/REQ-001 \| 仮 \|/);
    assert.doesNotMatch(log, /AI-001|crosscutting\//);
    const before = snapshot();
    assert.ok(Object.keys(before).length >= 4, Object.keys(before).join(', '));

    writeAi([
      ['AI-001', 'キャッシュは 5 分', '仮'],
      ['AI-002', 'キューは 3 本', '未決'],
    ]);
    assert.deepEqual((await checkedAfterConverge(root)).violations, []);
    assert.deepEqual(snapshot(), before);
  });
});
