// node --test dist/checks/DocGraphCheck.test.js
// 章別索引 (docs/README.md と docs/design/README.md) の生成だけを検証する。
// 一時ツリーを targetRoot に渡して DocGraphCheck を直接呼ぶ。
import { appendFileSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { after, beforeEach, describe, it } from 'node:test';
import assert from 'node:assert/strict';

import { DocGraphCheck } from './DocGraphCheck.js';
import { IGETA_ROOT } from '../core/Paths.js';
import { Report } from '../core/Report.js';
import type { Violation } from '../core/Report.js';
import type { ExitCode } from '../core/ExitCode.js';

const workspaces: string[] = [];

function writeDoc(root: string, rel: string, lines: readonly string[]): void {
  const target = join(root, 'docs', rel);
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, `${lines.join('\n')}\n`);
}

const doc = (id: string, type: string, kind: string, arc42: number, title: string): string[] => [
  '---', `id: ${id}`, `title: ${title}`, `type: ${type}`, `kind: ${kind}`,
  `arc42: ${arc42}`, 'status: active', 'owners: [eng]', 'depends_on: []', 'relates_to: []', '---',
  '', `# ${title}`, '',
];

function makeRoot(): string {
  const root = mkdtempSync(join(tmpdir(), 'yatsu-graph-'));
  workspaces.push(root);
  writeDoc(root, 'product/requirements.md', doc('requirements', 'design', 'requirements', 1, '要件定義書'));
  writeDoc(root, 'adr/0001-x.md', [
    '---', 'id: adr-0001-x', 'title: ADR-0001 x', 'type: adr', 'kind: adr', 'arc42: 9',
    'status: accepted', 'owners: [eng]', 'depends_on: []', 'relates_to: []', '---', '', '# ADR-0001 x', '',
  ]);
  writeDoc(root, 'adr/README.md', [
    '---', 'id: adr-index', 'title: ADR — 索引', 'type: index', 'status: active', 'owners: [eng]', '---',
    '', '# adr', '', '## 索引', '',
    '<!-- AUTOGEN:adr-index:start — generated by scripts/generate-docs-graph.mjs, do not edit by hand -->',
    '<!-- AUTOGEN:adr-index:end -->', '',
  ]);
  writeDoc(root, 'design/basic/function-list.md', doc('function-list', 'design', 'function-list', 1, '機能一覧'));
  return root;
}

interface RunResult {
  readonly status: ExitCode;
  readonly violations: readonly Violation[];
  readonly warnings: readonly string[];
  readonly detail: string;
}

const run = async (root: string, mode: 'write' | 'check'): Promise<RunResult> => {
  const check = new DocGraphCheck(mode === 'write' ? { write: true } : {});
  const violations = await check.run({ targetRoot: root, igetaRoot: IGETA_ROOT });
  const report = new Report();
  report.addAll(violations);
  return {
    status: report.exitCode,
    violations,
    warnings: check.warnings,
    detail: [report.format(), ...check.warnings].join('\n'),
  };
};

after(() => {
  for (const dir of workspaces) rmSync(dir, { recursive: true, force: true });
});

describe('DocGraphCheck の arc42 章別索引', () => {
  let root: string;
  beforeEach(() => {
    root = makeRoot();
  });

  it('別ディレクトリに実在する章はディレクトリ README へのリンクで示し、本当に無い章だけ _未作成_', async () => {
    const result = await run(root, 'write');
    assert.equal(result.status, 0, result.detail);
    const index = readFileSync(join(root, 'docs', 'design', 'README.md'), 'utf8');

    // §9 (ADR) は design/ の外にあるので、ディレクトリ README へのリンク 1 個で示す
    assert.match(index, /\*\*§9 Architecture Decisions\*\*.*→ \[adr\/\]\(\.\.\/adr\/README\.md\)/);
    // §1 は design/ 内 (機能一覧) と外 (要件定義書) の両方にあるので、両方出す
    assert.match(index, /\*\*§1 Introduction and Goals\*\*.*機能一覧.*→ \[product\/\]\(\.\.\/product\/README\.md\)/);
    // §11 はツリーのどこにも無いので未作成
    assert.match(index, /\*\*§11 Risks and Technical Debt\*\*[^|]*\|\s*_未作成_\s*\|/);
    // 「他所にある」ことを未作成と誤表示していないこと
    assert.doesNotMatch(index, /\*\*§9 Architecture Decisions\*\*[^|]*\|\s*_未作成_\s*\|/);
  });

  it('新規ツリーは write 2 回で不動点になる (1 回目で README が増えるため)', async () => {
    assert.equal((await run(root, 'write')).status, 0);
    // 1 回目の write が docs/README.md などを新規作成し、それ自体がグラフのノードになる。
    // 既存リポでは README が揃っているので 1 回で収束する。新規ツリーだけ 2 回必要。
    assert.equal((await run(root, 'write')).status, 0);
    const checked = await run(root, 'check');
    assert.equal(checked.status, 0, checked.detail);
  });
});

describe('DocGraphCheck の本文リンク検査', () => {
  let root: string;
  // 索引が収束した状態から本文だけを書き換える (索引 drift と混ざらないようにするため)
  const converge = async (r: string): Promise<void> => {
    assert.equal((await run(r, 'write')).status, 0);
    assert.equal((await run(r, 'write')).status, 0);
    assert.equal((await run(r, 'check')).status, 0);
  };
  const appendBody = (rel: string, lines: readonly string[]): void =>
    appendFileSync(join(root, 'docs', rel), `${lines.join('\n')}\n`);

  beforeEach(async () => {
    root = makeRoot();
    await converge(root);
  });

  it('正例: 実在する相対リンク・外部 URL・アンカーのみ・コードフェンス内・AUTOGEN 区間は通る', async () => {
    appendBody('design/basic/function-list.md', [
      '本文: [要件定義書](../../product/requirements.md) と [ADR](../../adr/0001-x.md#decision)。',
      '外部: [arc42](https://arc42.org/overview/) / アンカー: [上へ](#機能一覧)。',
      'インラインコード: `[x](./nope.md)` は本文リンクではない。',
      '',
      '```markdown',
      '[コードフェンス内の例](./absolutely-missing.md)',
      '```',
      '',
      '<!-- AUTOGEN:sample:start -->',
      '[生成区間](./generated-missing.md)',
      '<!-- AUTOGEN:sample:end -->',
    ]);
    const result = await run(root, 'check');
    assert.equal(result.status, 0, result.detail);
  });

  it('負例: 解決できない相対リンクは ERROR (exit 1) で file:line 付きで報告される', async () => {
    appendBody('design/basic/function-list.md', ['下流: [画面設計](./screens/README.md) を参照。']);
    const result = await run(root, 'check');
    assert.equal(result.status, 1);
    const link = result.violations.find((v) => v.message.includes('./screens/README.md'));
    assert.ok(link, result.detail);
    assert.match(link.message, /^\[link\] → \.\/screens\/README\.md/);
    assert.equal(link.file, 'docs/design/basic/function-list.md');
    assert.ok(typeof link.line === 'number' && link.line > 0, `line が無い: ${String(link.line)}`);
  });

  it('doc を直接持たず子ディレクトリだけのディレクトリにも索引 README を作る', async () => {
    writeDoc(root, 'design/detail/domain/overview.md', doc('domain-overview', 'design', 'domain-overview', 5, 'ドメイン概要'));
    await converge(root);
    const readme = join(root, 'docs', 'design', 'detail', 'README.md');
    assert.ok(existsSync(readme), 'design/detail/README.md が生成されていない');
    assert.match(readFileSync(readme, 'utf8'), /\[domain\/\]\(domain\/README\.md\)/);
  });

  it('arc42 未割当の doc は warning になる', async () => {
    writeDoc(root, 'design/basic/nonfunctional.md', [
      '---', 'id: nonfunctional', 'title: 非機能要件', 'type: design', 'kind: nonfunctional',
      'status: active', 'owners: [eng]', 'depends_on: []', 'relates_to: []', '---', '', '# 非機能要件', '',
    ]);
    const result = await run(root, 'write');
    assert.equal(result.status, 0, result.detail);
    assert.ok(
      result.warnings.some((w) => /docs\/design\/basic\/nonfunctional\.md に frontmatter arc42 が無い/.test(w)),
      result.detail,
    );
  });

  it('ADR が 1 本も無いツリーでは docs/adr/README.md を要求しない', async () => {
    rmSync(join(root, 'docs', 'adr'), { recursive: true, force: true });
    await converge(root);
    assert.equal(existsSync(join(root, 'docs', 'adr')), false, 'docs/adr/ を勝手に作っている');
    const result = await run(root, 'check');
    assert.equal(result.status, 0, result.detail);
  });

  it('負例: ADR があるのに docs/adr/README.md が無ければ落ちる (索引を黙って捨てない)', async () => {
    rmSync(join(root, 'docs', 'adr', 'README.md'));
    const result = await run(root, 'write');
    assert.notEqual(result.status, 0);
    assert.ok(
      result.violations.some((v) => v.message.includes('docs/adr/README.md')),
      result.detail,
    );
  });

  it('docs/design/ が無いツリーでは design/README.md を作らない', async () => {
    rmSync(join(root, 'docs', 'design'), { recursive: true, force: true });
    await converge(root);
    assert.equal(existsSync(join(root, 'docs', 'design')), false, 'docs/design/ を勝手に作っている');
    const result = await run(root, 'check');
    assert.equal(result.status, 0, result.detail);
  });

  it('arc42 を持つ文書が 1 本も無いツリーでは docs/README.md を章別ではなくファイル一覧にする (12 行の _未作成_ を出さない)', async () => {
    for (const d of ['product', 'design', 'adr']) rmSync(join(root, 'docs', d), { recursive: true, force: true });
    writeDoc(root, 'guides/how-to.md', [
      '---', 'id: how-to', 'title: 手引き', 'type: guide', 'kind: guide',
      'status: active', 'owners: [eng]', 'depends_on: []', 'relates_to: []', '---', '', '# 手引き', '',
    ]);
    await converge(root);
    const index = readFileSync(join(root, 'docs', 'README.md'), 'utf8');
    assert.doesNotMatch(index, /_未作成_/);
    assert.match(index, /\| ファイル \| タイトル \|/);
    assert.match(index, /\[guides\/\]\(guides\/README\.md\)/);
  });

  it('ディレクトリ索引は <context>.md を <context>-<aspect>.md より先に並べる', async () => {
    writeDoc(root, 'design/detail/domain/catalog.md', doc('domain-catalog', 'design', 'domain-model', 5, 'catalog'));
    writeDoc(root, 'design/detail/domain/catalog-pricing.md', doc('domain-catalog-pricing', 'design', 'domain-model', 5, 'catalog / 料金'));
    await converge(root);
    const index = readFileSync(join(root, 'docs', 'design', 'detail', 'domain', 'README.md'), 'utf8');
    assert.ok(index.indexOf('[catalog.md]') < index.indexOf('[catalog-pricing.md]'), index);
  });

  it('ディレクトリ索引に各文書の TL;DR を「説明」列として出す (強調・リンク・コードは剥がす)', async () => {
    writeDoc(root, 'design/detail/domain/catalog.md', [
      ...doc('domain-catalog', 'design', 'domain-model', 5, 'catalog'),
      '> **TL;DR**: 「何を貸すか」を持つ。**在庫の個体は持たない** (それは [索引](./README.md))。`Item` が集約。',
      '',
    ]);
    writeDoc(root, 'design/detail/domain/README.md', [
      '---', 'id: domain-index', 'title: domain — 索引', 'type: index', 'status: active', 'owners: [eng]', '---', '',
      '# domain', '', '> このディレクトリの目的: ドメインクラス図。1 コンテキスト 1 ファイル。', '', '## 索引', '',
      '<!-- AUTOGEN:dir-index:start — generated by scripts/generate-docs-graph.mjs, do not edit by hand -->',
      '<!-- AUTOGEN:dir-index:end -->', '',
    ]);
    await converge(root);
    const domain = readFileSync(join(root, 'docs', 'design', 'detail', 'domain', 'README.md'), 'utf8');
    assert.match(domain, /\| ファイル \| タイトル \| 説明 \|/);
    assert.match(domain, /\[catalog\.md\]\(catalog\.md\) \| catalog \| 「何を貸すか」を持つ。在庫の個体は持たない \(それは 索引\)。Item が集約。 \|/);
    // 親 (detail/) の索引では、子ディレクトリの行に README の「目的」を出す
    const detail = readFileSync(join(root, 'docs', 'design', 'detail', 'README.md'), 'utf8');
    assert.match(detail, /\[domain\/\]\(domain\/README\.md\) \| domain — 索引 \| ドメインクラス図。1 コンテキスト 1 ファイル。 \|/);
  });
});
