// node --test dist/checks/DocGraphCheck.test.js
// 章別索引 (docs/README.md と docs/design/README.md) の生成だけを検証する。
// 一時ツリーを targetRoot に渡して DocGraphCheck を直接呼ぶ。
import { appendFileSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { after, beforeEach, describe, it } from 'node:test';
import assert from 'node:assert/strict';

import { DocGraphCheck } from './DocGraphCheck.js';
import { IGETA_ROOT } from '../core/Paths.js';
import { Report } from '../core/Report.js';
import type { Violation } from '../core/Report.js';
import type { ExitCode } from '../core/ExitCode.js';

const workspaces: string[] = [];

function writeDoc(root: string, rel: string, lines: readonly string[]): void {
  const target = join(root, 'docs', rel);
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, `${lines.join('\n')}\n`);
}

const doc = (
  id: string,
  type: string,
  kind: string,
  arc42: number,
  title: string,
  dependsOn: readonly string[] = [],
): string[] => [
  '---', `id: ${id}`, `title: ${title}`, `type: ${type}`, `kind: ${kind}`,
  `arc42: ${arc42}`, 'status: active', 'owners: [eng]', `depends_on: [${dependsOn.join(', ')}]`, 'relates_to: []', '---',
  '', `# ${title}`, '',
];

function makeRoot(): string {
  const root = mkdtempSync(join(tmpdir(), 'igeta-graph-'));
  workspaces.push(root);
  writeDoc(root, 'product/requirements.md', doc('requirements', 'design', 'requirements', 1, '要件定義書'));
  writeDoc(root, 'adr/0001-x.md', [
    '---', 'id: adr-0001-x', 'title: ADR-0001 x', 'type: adr', 'kind: adr', 'arc42: 9',
    'status: accepted', 'owners: [eng]', 'depends_on: []', 'relates_to: []', '---', '', '# ADR-0001 x', '',
  ]);
  writeDoc(root, 'adr/README.md', [
    '---', 'id: adr-index', 'title: ADR — 索引', 'type: index', 'status: active', 'owners: [eng]', '---',
    '', '# adr', '', '## 索引', '',
    '<!-- AUTOGEN:adr-index:start — generated by scripts/generate-docs-graph.mjs, do not edit by hand -->',
    '<!-- AUTOGEN:adr-index:end -->', '',
  ]);
  writeDoc(root, 'design/basic/function-list.md', doc('function-list', 'design', 'function-list', 1, '機能一覧', ['requirements']));
  return root;
}

interface RunResult {
  readonly status: ExitCode;
  readonly violations: readonly Violation[];
  readonly warnings: readonly string[];
  readonly detail: string;
}

const run = async (root: string, mode: 'write' | 'check'): Promise<RunResult> => {
  const check = new DocGraphCheck(mode === 'write' ? { write: true } : {});
  const violations = await check.run({ targetRoot: root, igetaRoot: IGETA_ROOT });
  const report = new Report();
  report.addAll(violations);
  return {
    status: report.exitCode,
    violations,
    warnings: check.warnings,
    detail: [report.format(), ...check.warnings].join('\n'),
  };
};

after(() => {
  for (const dir of workspaces) rmSync(dir, { recursive: true, force: true });
});

describe('DocGraphCheck の arc42 章別索引', () => {
  let root: string;
  beforeEach(() => {
    root = makeRoot();
  });

  it('別ディレクトリに実在する章はディレクトリ README へのリンクで示し、本当に無い章だけ _未作成_', async () => {
    const result = await run(root, 'write');
    assert.equal(result.status, 0, result.detail);
    const index = readFileSync(join(root, 'docs', 'design', 'README.md'), 'utf8');

    // §9 (ADR) は design/ の外にあるので、ディレクトリ README へのリンク 1 個で示す
    assert.match(index, /\*\*§9 Architecture Decisions\*\*.*→ \[adr\/\]\(\.\.\/adr\/README\.md\)/);
    // §1 は design/ 内 (機能一覧) と外 (要件定義書) の両方にあるので、両方出す
    assert.match(index, /\*\*§1 Introduction and Goals\*\*.*機能一覧.*→ \[product\/\]\(\.\.\/product\/README\.md\)/);
    // §11 はツリーのどこにも無いので未作成
    assert.match(index, /\*\*§11 Risks and Technical Debt\*\*[^|]*\|\s*_未作成_\s*\|/);
    // 「他所にある」ことを未作成と誤表示していないこと
    assert.doesNotMatch(index, /\*\*§9 Architecture Decisions\*\*[^|]*\|\s*_未作成_\s*\|/);
  });

  it('新規ツリーは write 2 回で不動点になる (1 回目で README が増えるため)', async () => {
    assert.equal((await run(root, 'write')).status, 0);
    // 1 回目の write が docs/README.md などを新規作成し、それ自体がグラフのノードになる。
    // 既存リポでは README が揃っているので 1 回で収束する。新規ツリーだけ 2 回必要。
    assert.equal((await run(root, 'write')).status, 0);
    const checked = await run(root, 'check');
    assert.equal(checked.status, 0, checked.detail);
  });
});

describe('DocGraphCheck の本文リンク検査', () => {
  let root: string;
  // 索引が収束した状態から本文だけを書き換える (索引 drift と混ざらないようにするため)
  const converge = async (r: string): Promise<void> => {
    assert.equal((await run(r, 'write')).status, 0);
    assert.equal((await run(r, 'write')).status, 0);
    assert.equal((await run(r, 'check')).status, 0);
  };
  const appendBody = (rel: string, lines: readonly string[]): void =>
    appendFileSync(join(root, 'docs', rel), `${lines.join('\n')}\n`);

  beforeEach(async () => {
    root = makeRoot();
    await converge(root);
  });

  it('正例: 実在する相対リンク・外部 URL・アンカーのみ・コードフェンス内・AUTOGEN 区間は通る', async () => {
    appendBody('design/basic/function-list.md', [
      '本文: [要件定義書](../../product/requirements.md) と [ADR](../../adr/0001-x.md#decision)。',
      '外部: [arc42](https://arc42.org/overview/) / アンカー: [上へ](#機能一覧)。',
      'インラインコード: `[x](./nope.md)` は本文リンクではない。',
      '',
      '```markdown',
      '[コードフェンス内の例](./absolutely-missing.md)',
      '```',
      '',
      '<!-- AUTOGEN:sample:start -->',
      '[生成区間](./generated-missing.md)',
      '<!-- AUTOGEN:sample:end -->',
    ]);
    const result = await run(root, 'check');
    assert.equal(result.status, 0, result.detail);
  });

  it('負例: 解決できない相対リンクは ERROR (exit 1) で file:line 付きで報告される', async () => {
    appendBody('design/basic/function-list.md', ['下流: [画面設計](./screens/README.md) を参照。']);
    const result = await run(root, 'check');
    assert.equal(result.status, 1);
    const link = result.violations.find((v) => v.message.includes('./screens/README.md'));
    assert.ok(link, result.detail);
    assert.match(link.message, /^\[link\] → \.\/screens\/README\.md/);
    assert.equal(link.file, 'docs/design/basic/function-list.md');
    assert.ok(typeof link.line === 'number' && link.line > 0, `line が無い: ${String(link.line)}`);
  });

  it('doc を直接持たず子ディレクトリだけのディレクトリにも索引 README を作る', async () => {
    writeDoc(root, 'design/detail/domain/overview.md', doc('domain-overview', 'design', 'domain-overview', 5, 'ドメイン概要', ['function-list']));
    await converge(root);
    const readme = join(root, 'docs', 'design', 'detail', 'README.md');
    assert.ok(existsSync(readme), 'design/detail/README.md が生成されていない');
    assert.match(readFileSync(readme, 'utf8'), /\[domain\/\]\(domain\/README\.md\)/);
  });

  it('arc42 未割当の doc は warning になる', async () => {
    writeDoc(root, 'design/basic/nonfunctional.md', [
      '---', 'id: nonfunctional', 'title: 非機能要件', 'type: design', 'kind: nonfunctional',
      'status: active', 'owners: [eng]', 'depends_on: []', 'relates_to: []', '---', '', '# 非機能要件', '',
    ]);
    const result = await run(root, 'write');
    assert.equal(result.status, 0, result.detail);
    assert.ok(
      result.warnings.some((w) => /docs\/design\/basic\/nonfunctional\.md に frontmatter arc42 が無い/.test(w)),
      result.detail,
    );
  });

  it('ADR が 1 本も無いツリーでは docs/adr/README.md を要求しない', async () => {
    rmSync(join(root, 'docs', 'adr'), { recursive: true, force: true });
    await converge(root);
    assert.equal(existsSync(join(root, 'docs', 'adr')), false, 'docs/adr/ を勝手に作っている');
    const result = await run(root, 'check');
    assert.equal(result.status, 0, result.detail);
  });

  it('負例: ADR があるのに docs/adr/README.md が無ければ落ちる (索引を黙って捨てない)', async () => {
    rmSync(join(root, 'docs', 'adr', 'README.md'));
    const result = await run(root, 'write');
    assert.notEqual(result.status, 0);
    assert.ok(
      result.violations.some((v) => v.message.includes('docs/adr/README.md')),
      result.detail,
    );
  });

  it('docs/design/ が無いツリーでは design/README.md を作らない', async () => {
    rmSync(join(root, 'docs', 'design'), { recursive: true, force: true });
    await converge(root);
    assert.equal(existsSync(join(root, 'docs', 'design')), false, 'docs/design/ を勝手に作っている');
    const result = await run(root, 'check');
    assert.equal(result.status, 0, result.detail);
  });

  it('arc42 を持つ文書が 1 本も無いツリーでは docs/README.md を章別ではなくファイル一覧にする (12 行の _未作成_ を出さない)', async () => {
    for (const d of ['product', 'design', 'adr']) rmSync(join(root, 'docs', d), { recursive: true, force: true });
    writeDoc(root, 'guides/how-to.md', [
      '---', 'id: how-to', 'title: 手引き', 'type: guide', 'kind: guide',
      'status: active', 'owners: [eng]', 'depends_on: []', 'relates_to: []', '---', '', '# 手引き', '',
    ]);
    await converge(root);
    const index = readFileSync(join(root, 'docs', 'README.md'), 'utf8');
    assert.doesNotMatch(index, /_未作成_/);
    assert.match(index, /階層は frontmatter `depends_on` から生成/);
    assert.match(index, /^- \[guides\/\]\(guides\/README\.md\)/m);
  });

  it('ディレクトリ索引は <context>.md を <context>-<aspect>.md より先に並べる', async () => {
    writeDoc(root, 'design/detail/domain/catalog.md', doc('domain-catalog', 'design', 'domain-model', 5, 'catalog', ['function-list']));
    writeDoc(root, 'design/detail/domain/catalog-pricing.md', doc('domain-catalog-pricing', 'design', 'domain-model', 5, 'catalog / 料金', ['function-list']));
    await converge(root);
    const index = readFileSync(join(root, 'docs', 'design', 'detail', 'domain', 'README.md'), 'utf8');
    assert.ok(index.indexOf('[catalog.md]') < index.indexOf('[catalog-pricing.md]'), index);
  });

  it('ディレクトリ索引に各文書の TL;DR を説明として出す (強調・リンク・コードは剥がす)', async () => {
    writeDoc(root, 'design/detail/domain/catalog.md', [
      ...doc('domain-catalog', 'design', 'domain-model', 5, 'catalog', ['function-list']),
      '> **TL;DR**: 「何を貸すか」を持つ。**在庫の個体は持たない** (それは [索引](./README.md))。`Item` が集約。',
      '',
    ]);
    writeDoc(root, 'design/detail/domain/README.md', [
      '---', 'id: domain-index', 'title: domain — 索引', 'type: index', 'status: active', 'owners: [eng]', '---', '',
      '# domain', '', '> このディレクトリの目的: ドメインクラス図。1 コンテキスト 1 ファイル。', '', '## 索引', '',
      '<!-- AUTOGEN:dir-index:start — generated by scripts/generate-docs-graph.mjs, do not edit by hand -->',
      '<!-- AUTOGEN:dir-index:end -->', '',
    ]);
    await converge(root);
    const domain = readFileSync(join(root, 'docs', 'design', 'detail', 'domain', 'README.md'), 'utf8');
    assert.match(
      domain,
      /^- \[catalog\.md\]\(catalog\.md\) — \*\*catalog\*\* `design` — 「何を貸すか」を持つ。在庫の個体は持たない \(それは 索引\)。Item が集約。 ← 上流: \[function-list\]\(\.\.\/\.\.\/basic\/function-list\.md\)$/m,
    );
    // 親 (detail/) の索引では、子ディレクトリの行に README の「目的」を出す
    const detail = readFileSync(join(root, 'docs', 'design', 'detail', 'README.md'), 'utf8');
    assert.match(detail, /^- \[domain\/\]\(domain\/README\.md\) — \*\*domain — 索引\*\* — ドメインクラス図。1 コンテキスト 1 ファイル。$/m);
  });

  it('生成日付が古いだけでは drift にしない (生成の翌日に必ず赤くなるのを防ぐ)', async () => {
    await converge(root);
    const depsPath = join(root, 'docs', 'dependencies.md');
    const aged = readFileSync(depsPath, 'utf8').replace(/^> 自動生成: .*$/m, '> 自動生成: 2000-01-01 (UTC) / ソース: 各 `docs/**/*.md` の frontmatter');
    writeFileSync(depsPath, aged);

    const result = await run(root, 'check');
    assert.equal(result.status, 0, result.detail);
  });
});

describe('DocGraphCheck の階層索引と配置検査', () => {
  let root: string;
  const converge = async (r: string): Promise<void> => {
    assert.equal((await run(r, 'write')).status, 0);
    assert.equal((await run(r, 'write')).status, 0);
  };
  const business = (id: string, title: string, extra: readonly string[] = []): string[] => [
    '---', `id: ${id}`, `title: ${title}`, 'type: business', 'status: active', 'owners: [eng]', ...extra, '---',
    '', `# ${title}`, '',
  ];

  beforeEach(() => {
    root = makeRoot();
  });

  it('ディレクトリ索引は depends_on の木で出す (子は親の下に字下げ、ディレクトリ外の上流は ← 上流)', async () => {
    writeDoc(root, 'business/finance/policy.md', business('fin-policy', '財務方針', ['depends_on: [requirements]']));
    writeDoc(root, 'business/finance/plan.md', business('fin-plan', '収支計画', ['depends_on: [fin-policy]']));
    writeDoc(root, 'business/finance/tax.md', business('fin-tax', '税務手順', ['depends_on: [fin-plan]']));
    writeDoc(root, 'business/finance/old-plan.md', business('fin-old-plan', '旧 収支計画', ['status: superseded', 'superseded_by: fin-plan']));
    writeDoc(root, 'business/finance/grants/sogyo.md', business('fin-grant-sogyo', '創業助成金', ['depends_on: [fin-plan]']));
    await converge(root);
    const check = await run(root, 'check');
    assert.equal(check.status, 0, check.detail);

    const index = readFileSync(join(root, 'docs', 'business', 'finance', 'README.md'), 'utf8');
    const lines = index.split('\n');
    const at = (needle: string): number => lines.findIndex((l) => l.includes(needle));
    const indent = (needle: string): number => lines[at(needle)]?.match(/^ */)?.[0].length ?? -1;
    assert.equal(indent('[policy.md]'), 0, index);
    assert.equal(indent('[plan.md]'), 2, index);
    assert.equal(indent('[tax.md]'), 4, index);
    assert.equal(indent('[old-plan.md]'), 4, index); // superseded_by で新の下にぶら下がる
    assert.ok(at('[policy.md]') < at('[plan.md]') && at('[plan.md]') < at('[tax.md]'), index);
    assert.match(index, /\[policy\.md\].*← 上流: \[requirements\]\(\.\.\/\.\.\/product\/requirements\.md\)/);
    assert.match(index, /\[old-plan\.md\].*_\(superseded\)_/);
    assert.match(index, /^- \[grants\/\]\(grants\/README\.md\)/m);
    assert.doesNotMatch(index, /\| ファイル \| タイトル \|/);
  });

  it('負例: 上流も下流も無い文書は --check で落ちる (一覧に足すだけでは登録にならない)', async () => {
    writeDoc(root, 'business/finance/lonely.md', business('fin-lonely', '孤立文書'));
    const written = await run(root, 'write');
    assert.equal(written.status, 0, written.detail); // --write は書いたうえで warning
    assert.ok(written.warnings.some((w) => w.includes('fin-lonely') && w.includes('階層に無い')), written.detail);
    await converge(root);
    const result = await run(root, 'check');
    assert.equal(result.status, 1, result.detail);
    const hit = result.violations.find((v) => v.message.includes('fin-lonely'));
    assert.ok(hit, result.detail);
    assert.match(hit.message, /^\[graph\] fin-lonely \(docs\/business\/finance\/lonely\.md\) が階層に無い/);
  });

  it('根になれる種別 (requirements / adr / runbook / guide など) は上流が無くても通る', async () => {
    writeDoc(root, 'runbooks/deploy.md', [
      '---', 'id: deploy-runbook', 'title: デプロイ手順', 'type: runbook', 'kind: runbook',
      'status: active', 'owners: [eng]', 'depends_on: []', 'relates_to: []', '---', '', '# デプロイ手順', '',
    ]);
    await converge(root);
    const result = await run(root, 'check');
    assert.equal(result.status, 0, result.detail);
  });

  it('負例: depends_on の循環は落ちる (木にならない)。索引からは消さない', async () => {
    writeDoc(root, 'business/finance/a.md', business('fin-a', 'A', ['depends_on: [fin-b]']));
    writeDoc(root, 'business/finance/b.md', business('fin-b', 'B', ['depends_on: [fin-a]']));
    await converge(root);
    const result = await run(root, 'check');
    assert.equal(result.status, 1, result.detail);
    assert.ok(result.violations.some((v) => /\[graph\] depends_on が循環: fin-(a|b) → fin-(a|b) → fin-(a|b)/.test(v.message)), result.detail);
    const index = readFileSync(join(root, 'docs', 'business', 'finance', 'README.md'), 'utf8');
    assert.match(index, /\[a\.md\]/);
    assert.match(index, /\[b\.md\]/);
  });
});

describe('DocGraphCheck の決定台帳 AUTOGEN (仮置き一覧)', () => {
  let root: string;
  const decisionLog = (): string[] => [
    '---', 'id: decisions', 'title: 決定台帳', 'type: decision-log', 'kind: decision-log',
    'status: active', 'owners: [eng]', 'depends_on: []', 'relates_to: []', '---',
    '', '# 決定台帳', '', '## 1. 決定 (DEC)', '', '## 2. 未決 (OPEN)', '', '## 3. 仮置き一覧 (自動生成)', '',
    '<!-- AUTOGEN:tentative-index:start — generated by scripts/generate-docs-graph.mjs, do not edit by hand -->',
    '<!-- AUTOGEN:tentative-index:end -->', '',
  ];

  beforeEach(() => {
    root = mkdtempSync(join(tmpdir(), 'igeta-graph-tentative-'));
    workspaces.push(root);
    writeDoc(root, '01-decisions.md', decisionLog());
    writeDoc(root, 'product/requirements.md', [
      '---', 'id: requirements', 'title: 要件定義書', 'type: design', 'kind: requirements', 'arc42: 1',
      'status: active', 'owners: [eng]', 'depends_on: []', 'relates_to: []', '---',
      '', '# 要件定義書', '', '猶予は仮置きで30日とする (OPEN-001)。', '',
    ]);
  });

  it('正例: 「仮置き」を含む行が OPEN 参照つきで台帳の AUTOGEN 区間へ集まる', async () => {
    const result = await run(root, 'write');
    assert.equal(result.status, 0, result.detail);
    const index = readFileSync(join(root, 'docs', '01-decisions.md'), 'utf8');
    assert.match(index, /\| OPEN-001 \| \[docs\/product\/requirements\.md:\d+\]\(product\/requirements\.md#L\d+\) \| 猶予は仮置きで30日とする \(OPEN-001\)。 \|/);
  });

  it('正例: 決定台帳の見出し (「仮置き一覧」) や列名 (「仮置き値」) は自分自身への言及として拾わない', async () => {
    writeDoc(root, '01-decisions.md', [
      ...decisionLog().slice(0, -3),
      '| ID | 論点 | 仮置き値 |', '|---|---|---|', '| OPEN-001 | 猶予日数 | 30日 |', '',
      '## 3. 仮置き一覧 (自動生成)', '',
      '<!-- AUTOGEN:tentative-index:start — generated by scripts/generate-docs-graph.mjs, do not edit by hand -->',
      '<!-- AUTOGEN:tentative-index:end -->', '',
    ]);
    const result = await run(root, 'write');
    assert.equal(result.status, 0, result.detail);
    const index = readFileSync(join(root, 'docs', '01-decisions.md'), 'utf8');
    // 台帳自身の行 (見出し・列名) は仮置き一覧に出ない。他文書の OPEN-001 だけが載る
    assert.equal((index.match(/仮置きで30日とする/g) ?? []).length, 1);
  });

  it('負例: --write 後に本文だけ書き換えると台帳の仮置き一覧が drift で落ちる', async () => {
    assert.equal((await run(root, 'write')).status, 0);
    writeDoc(root, 'product/requirements.md', [
      '---', 'id: requirements', 'title: 要件定義書', 'type: design', 'kind: requirements', 'arc42: 1',
      'status: active', 'owners: [eng]', 'depends_on: []', 'relates_to: []', '---',
      '', '# 要件定義書', '', '猶予は仮置きで30日とする (OPEN-001)。', '値上げ幅も仮置きで5%とする (OPEN-002)。', '',
    ]);
    const result = await run(root, 'check');
    assert.equal(result.status, 1, result.detail);
    assert.ok(result.violations.some((v) => /決定台帳の仮置き一覧が out of date/.test(v.message)), result.detail);
  });

  it('前提修正: 日付入り ID (OPEN-20260917-02) の先頭 3 桁を実在の OPEN-nnn へ部分一致させない', async () => {
    // 台帳に OPEN-202 を実在させた状態で、本文が日付入りの原文表記 (OPEN-20260917-02) を含んでいても
    // 「OPEN-202 への参照がある」と誤認して openRef を埋めてはいけない (無関係な参照先を仮置き一覧に出す)。
    writeDoc(root, '01-decisions.md', [
      ...decisionLog().slice(0, -3),
      '| ID | 論点 | 仮置き値 |', '|---|---|---|', '| OPEN-202 | 猶予日数 | 30日 |', '',
      '## 3. 仮置き一覧 (自動生成)', '',
      '<!-- AUTOGEN:tentative-index:start — generated by scripts/generate-docs-graph.mjs, do not edit by hand -->',
      '<!-- AUTOGEN:tentative-index:end -->', '',
    ]);
    writeDoc(root, 'product/requirements.md', [
      '---', 'id: requirements', 'title: 要件定義書', 'type: design', 'kind: requirements', 'arc42: 1',
      'status: active', 'owners: [eng]', 'depends_on: []', 'relates_to: []', '---',
      '', '# 要件定義書', '', '猶予は仮置きで30日とする (OPEN-20260917-02)。', '',
    ]);
    const result = await run(root, 'write');
    assert.equal(result.status, 0, result.detail);
    const index = readFileSync(join(root, 'docs', '01-decisions.md'), 'utf8');
    assert.match(index, /\| \*\*\(無し\)\*\* \| \[docs\/product\/requirements\.md:\d+\]/, index);
    // 仮置き一覧の行 (docs/product/requirements.md を場所に持つ行) の openRef が OPEN-202 になっていないこと。
    // 台帳自身の §2 定義行 (`| OPEN-202 | 猶予日数 | 30日 |`) は別行なので対象外。
    assert.doesNotMatch(index, /\| OPEN-202 \| \[docs\/product/);
  });

  it('decision-log の doc が無いツリーでは何もしない (人間レビュー層は opt-in)', async () => {
    rmSync(join(root, 'docs', '01-decisions.md'));
    const result = await run(root, 'write');
    assert.equal(result.status, 0, result.detail);
  });

  it('負例: 引用「」内の「仮置き」は台帳に集めない (template-check の判定と一致させる、code-reviewer 実バグ #2)', async () => {
    writeDoc(root, 'product/requirements.md', [
      '---', 'id: requirements', 'title: 要件定義書', 'type: design', 'kind: requirements', 'arc42: 1',
      'status: active', 'owners: [eng]', 'depends_on: []', 'relates_to: []', '---',
      '', '# 要件定義書', '', '前版は「仮置き」と書かれていたが、正式値に更新した。', '',
    ]);
    const result = await run(root, 'write');
    assert.equal(result.status, 0, result.detail);
    const index = readFileSync(join(root, 'docs', '01-decisions.md'), 'utf8');
    assert.match(index, /_該当なし_/, index);
  });

  it('負例: 否定直後の「仮置き」は台帳に集めない (template-check の判定と一致させる、code-reviewer 実バグ #2)', async () => {
    writeDoc(root, 'product/requirements.md', [
      '---', 'id: requirements', 'title: 要件定義書', 'type: design', 'kind: requirements', 'arc42: 1',
      'status: active', 'owners: [eng]', 'depends_on: []', 'relates_to: []', '---',
      '', '# 要件定義書', '', 'この値は仮置きではない。', '',
    ]);
    const result = await run(root, 'write');
    assert.equal(result.status, 0, result.detail);
    const index = readFileSync(join(root, 'docs', '01-decisions.md'), 'utf8');
    assert.match(index, /_該当なし_/, index);
  });

  it('負例: HTML コメント内の「仮置き」は台帳に集めない (template-check の判定と一致させる、code-reviewer 実バグ #2)', async () => {
    writeDoc(root, 'product/requirements.md', [
      '---', 'id: requirements', 'title: 要件定義書', 'type: design', 'kind: requirements', 'arc42: 1',
      'status: active', 'owners: [eng]', 'depends_on: []', 'relates_to: []', '---',
      '', '# 要件定義書', '', '<!-- 著者向けの注記: 仮置きで30日とする例を書く予定 -->', '',
    ]);
    const result = await run(root, 'write');
    assert.equal(result.status, 0, result.detail);
    const index = readFileSync(join(root, 'docs', '01-decisions.md'), 'utf8');
    assert.match(index, /_該当なし_/, index);
  });

  it('正例: 否定の decoy を先に置いても後続の本物の仮置きは拾う (round 3 C2 と同じ判定)', async () => {
    writeDoc(root, 'product/requirements.md', [
      '---', 'id: requirements', 'title: 要件定義書', 'type: design', 'kind: requirements', 'arc42: 1',
      'status: active', 'owners: [eng]', 'depends_on: []', 'relates_to: []', '---',
      '', '# 要件定義書', '', '前者は仮置きではないが、後者は仮置きで30日とする (OPEN-001)。', '',
    ]);
    const result = await run(root, 'write');
    assert.equal(result.status, 0, result.detail);
    const index = readFileSync(join(root, 'docs', '01-decisions.md'), 'utf8');
    assert.match(index, /OPEN-001/, index);
  });

  it('正例: 他文書の AUTOGEN 索引 (ADR 一覧の title 列など) に「仮置き」が写っても仮置き一覧に拾わない (code-reviewer 実バグ #2)', async () => {
    // ADR のタイトルに「仮置き」が入っていると、docs-graph --write が adr/README.md の
    // AUTOGEN:adr-index 区間へそのタイトルを写す。この索引行は他文書の要約の引用であって、
    // ADR 自身が新たに「仮置き」を主張したわけではないので、決定台帳の仮置き一覧には拾わない。
    writeDoc(root, 'adr/0001-tentative.md', [
      '---', 'id: adr-0001-tentative', 'title: 仮置き値の運用方針', 'type: adr', 'kind: adr', 'arc42: 9',
      'status: accepted', 'owners: [eng]', 'depends_on: []', 'relates_to: []', '---', '', '# ADR-0001 仮置き値の運用方針', '',
    ]);
    writeDoc(root, 'adr/README.md', [
      '---', 'id: adr-index', 'title: ADR — 索引', 'type: index', 'status: active', 'owners: [eng]', '---',
      '', '# adr', '', '## 索引', '',
      '<!-- AUTOGEN:adr-index:start — generated by scripts/generate-docs-graph.mjs, do not edit by hand -->',
      '<!-- AUTOGEN:adr-index:end -->', '',
    ]);
    const result = await run(root, 'write');
    assert.equal(result.status, 0, result.detail);
    const adrReadme = readFileSync(join(root, 'docs', 'adr', 'README.md'), 'utf8');
    assert.match(adrReadme, /仮置き値の運用方針/, 'ADR 索引に自分のタイトルが写っていることの前提確認');
    const index = readFileSync(join(root, 'docs', '01-decisions.md'), 'utf8');
    assert.doesNotMatch(index, /adr\/README\.md/, index);
    // requirements.md 由来の本物の仮置きマークは変わらず 1 件だけ拾われる
    assert.equal((index.match(/仮置きで30日とする/g) ?? []).length, 1);
  });

  it('正例: 同じツリーへ write を 2 回かけても仮置き一覧が安定する (不動点、root cause 回帰 (b) の縮小版)', async () => {
    writeDoc(root, 'adr/0001-tentative.md', [
      '---', 'id: adr-0001-tentative', 'title: 仮置き値の運用方針', 'type: adr', 'kind: adr', 'arc42: 9',
      'status: accepted', 'owners: [eng]', 'depends_on: []', 'relates_to: []', '---', '', '# ADR-0001 仮置き値の運用方針', '',
    ]);
    writeDoc(root, 'adr/README.md', [
      '---', 'id: adr-index', 'title: ADR — 索引', 'type: index', 'status: active', 'owners: [eng]', '---',
      '', '# adr', '', '## 索引', '',
      '<!-- AUTOGEN:adr-index:start — generated by scripts/generate-docs-graph.mjs, do not edit by hand -->',
      '<!-- AUTOGEN:adr-index:end -->', '',
    ]);
    assert.equal((await run(root, 'write')).status, 0);
    const afterFirstWrite = readFileSync(join(root, 'docs', '01-decisions.md'), 'utf8');
    assert.equal((await run(root, 'write')).status, 0);
    const afterSecondWrite = readFileSync(join(root, 'docs', '01-decisions.md'), 'utf8');
    assert.equal(afterFirstWrite, afterSecondWrite);
    const result = await run(root, 'check');
    assert.equal(result.status, 0, result.detail);
  });

  it('正例: 決定台帳が docs/ 直下以外にあっても仮置き一覧のリンクが正しい相対パスになる (code-reviewer 実バグ #3)', async () => {
    // 決定台帳を docs/governance/01-decisions.md に置く。以前は「docs/ を剥がすだけ」で
    // href を作っていたため、決定台帳自身のディレクトリからの相対パスにならず、
    // docs/governance/product/requirements.md という存在しないパスを指すリンクになっていた。
    rmSync(join(root, 'docs', '01-decisions.md'));
    writeDoc(root, 'governance/01-decisions.md', decisionLog());
    const result = await run(root, 'write');
    assert.equal(result.status, 0, result.detail);
    const index = readFileSync(join(root, 'docs', 'governance', '01-decisions.md'), 'utf8');
    const hrefMatch = /\|\s*OPEN-001\s*\|\s*\[docs\/product\/requirements\.md:\d+\]\(([^)]+)\)/.exec(index);
    assert.ok(hrefMatch, `仮置き一覧の行が見つからない:\n${index}`);
    const href = (hrefMatch?.[1] ?? '').replace(/#L\d+$/, '');
    assert.equal(href, '../product/requirements.md', index);
    // リンクが実際に実在するファイルへ解決することも確認する (リンク切れ検出)
    assert.ok(existsSync(join(root, 'docs', 'governance', href)), `リンクが解決できない: docs/governance/${href}`);
  });
});
