// node --test dist/checks/DocGraphCheck.v4.test.js
// 新しい構成 (docs/person・ai・client) の repo での、索引と参照の検査 (DocGraphCheck の v4 対応)。
// 旧い構成 (docs/adr/ に ADR 索引) の挙動が変わらないことも、同じ検査で並べて確かめる。
// 一時ディレクトリに 3 区分・複数のまとまり・複数の年の ADR を持つ構成を作る。
// 文書のつながり (テスト仕様 04 の G1〜G8) の行は、`[TST-nnn]` で始まる名前の it が持つ。
import { existsSync, globSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, posix } from 'node:path';
import { after, beforeEach, describe, it } from 'node:test';
import assert from 'node:assert/strict';

import { DocsCheckCommand, DocsGraphCommand } from '../cli/commands/checkCommands.js';
import { ExitCode } from '../core/ExitCode.js';
import { IGETA_ROOT } from '../core/Paths.js';
import type { Violation } from '../core/Report.js';
import { DocGraphCheck } from './DocGraphCheck.js';

const workspaces: string[] = [];

after(() => {
  for (const dir of workspaces) rmSync(dir, { recursive: true, force: true });
});

function makeRoot(): string {
  const root = mkdtempSync(join(tmpdir(), 'igeta-graph-v4-'));
  workspaces.push(root);
  return root;
}

function write(root: string, relPath: string, lines: readonly string[]): void {
  const target = join(root, relPath);
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, `${lines.join('\n')}\n`);
}

interface DocOptions {
  readonly type?: string;
  readonly arc42?: number;
  readonly status?: string;
  readonly dependsOn?: readonly string[];
  readonly relatesTo?: readonly string[];
  readonly context?: string;
  readonly body?: readonly string[];
}

/** 索引と参照の検査が読む frontmatter と、本文の行 */
function doc(id: string, kind: string, options: DocOptions = {}): string[] {
  const { type = 'design', arc42, status = 'active', dependsOn = [], relatesTo = [], context, body = [] } = options;
  return [
    '---',
    `id: ${id}`,
    `title: ${id} の題名`,
    `type: ${type}`,
    `kind: ${kind}`,
    ...(arc42 === undefined ? [] : [`arc42: ${arc42}`]),
    ...(context === undefined ? [] : [`context: ${context}`]),
    `status: ${status}`,
    'owners: [eng]',
    `depends_on: [${dependsOn.join(', ')}]`,
    `relates_to: [${relatesTo.join(', ')}]`,
    '---',
    '',
    `# ${id}`,
    '',
    ...body,
  ];
}

function adr(number: string, slug: string, status: string, extra: readonly string[] = []): string[] {
  return doc(`adr-${number}-${slug}`, 'adr', { type: 'adr', arc42: 9, status, body: extra });
}

/** ADR 索引と、ディレクトリ索引の 2 区間を持つ decisions/README.md (雛形と同じ形) */
const DECISIONS_README: readonly string[] = [
  '---',
  'id: decisions-index',
  'title: decisions — 索引',
  'type: index',
  'status: active',
  'owners: [eng]',
  '---',
  '',
  '# decisions',
  '',
  '> このディレクトリの目的: 決定の記録。',
  '',
  '## 索引',
  '',
  '<!-- AUTOGEN:adr-index:start — generated by scripts/generate-docs-graph.mjs, do not edit by hand -->',
  '<!-- AUTOGEN:adr-index:end -->',
  '',
  '<!-- AUTOGEN:dir-index:start — generated by scripts/generate-docs-graph.mjs, do not edit by hand -->',
  '<!-- AUTOGEN:dir-index:end -->',
];

/** 決まりの表 (最後の列が 状態)。決まりの行は、最初のセルが ID の形だけの行 */
function decisionTable(rows: ReadonlyArray<readonly [id: string, text: string, state: string]>): string[] {
  return ['| ID | 決まり | 状態 |', '|---|---|---|', ...rows.map(([id, text, state]) => `| ${id} | ${text} | ${state} |`)];
}

/** 要件の文書。accepted・amended の ADR は、要件の決まりの行が `ADR-NNNN` の形で引く (G4) */
function writeRequirements(root: string, citedAdrs: readonly string[]): void {
  write(
    root,
    'docs/person/requirements/01-requirements.md',
    doc('requirements', 'requirements', {
      arc42: 1,
      body: decisionTable(citedAdrs.map((number, index) => [`REQ-${String(index + 1).padStart(3, '0')}`, `ADR-${number} の決定を反映する`, '決定'])),
    }),
  );
}

/** tentative-index の区間を持つ決定台帳 (雛形と同じ形。DEC・OPEN の表は、状態の列が無いので決まりの表ではない) */
const DECISION_LOG: readonly string[] = [
  '---',
  'id: decisions',
  'title: 決定台帳',
  'type: decision-log',
  'kind: decision-log',
  'status: active',
  'owners: [eng]',
  'depends_on: []',
  'relates_to: [map]',
  '---',
  '',
  '# 決定台帳',
  '',
  '## 1. 決定 (DEC)',
  '',
  '| ID | 日付 | 決定 |',
  '|---|---|---|',
  '| DEC-001 | 2026-10-02 | 決めたこと |',
  '',
  '## 3. 仮・未決の一覧 (自動生成)',
  '',
  '<!-- AUTOGEN:tentative-index:start — generated by scripts/generate-docs-graph.mjs, do not edit by hand -->',
  '<!-- AUTOGEN:tentative-index:end -->',
];

/** 3 区分・まとまり 2 つ・年 2 つの ADR を持つ、正しい構成 */
function writeValidTree(root: string): void {
  writeRequirements(root, ['0001', '0002']);
  write(root, 'docs/person/design/shared/00-map.md', doc('map', 'map'));
  write(
    root,
    'docs/person/design/reservation/00-map.md',
    doc('reservation-map', 'context-map', { dependsOn: ['map'], context: 'reservation' }),
  );
  write(
    root,
    'docs/person/design/payment/00-map.md',
    doc('payment-map', 'context-map', { dependsOn: ['map'], context: 'payment' }),
  );
  write(root, 'docs/person/decisions/README.md', DECISIONS_README);
  write(root, 'docs/person/decisions/2025/0001-use-postgres.md', adr('0001', 'use-postgres', 'accepted'));
  write(root, 'docs/person/decisions/2026/0002-queue.md', adr('0002', 'queue', 'amended'));
  write(root, 'docs/person/decisions/2026/0003-cache.md', adr('0003', 'cache', 'proposed'));
  write(
    root,
    'docs/ai/specs/reservation/api/01-reserve.md',
    doc('reservation-api', 'api-spec', { arc42: 5, dependsOn: ['reservation-map'], context: 'reservation' }),
  );
  write(root, 'docs/ai/handbook/how-to/01-setup.md', doc('setup', 'guide', { type: 'guide' }));
  write(root, 'docs/client/delivery/spec-v1/01-overview.md', doc('delivery-overview', 'delivery-chapter', { dependsOn: ['requirements'] }));
}

interface RunResult {
  readonly violations: readonly Violation[];
  readonly warnings: readonly string[];
  readonly detail: string;
}

async function run(root: string, mode: 'write' | 'check'): Promise<RunResult> {
  const check = new DocGraphCheck(mode === 'write' ? { write: true } : {});
  const violations = await check.run({ targetRoot: root, igetaRoot: IGETA_ROOT });
  return {
    violations,
    warnings: check.warnings,
    detail: [...violations.map((violation) => `${violation.file ?? ''} ${violation.message}`), ...check.warnings].join('\n'),
  };
}

/** 新規の木は、1 回目の write が README を作り、それが 2 回目のグラフの節点になるので、2 回で収束する */
async function converge(root: string): Promise<void> {
  assert.deepEqual((await run(root, 'write')).violations, []);
  assert.deepEqual((await run(root, 'write')).violations, []);
}

const read = (root: string, relPath: string): string => readFileSync(join(root, relPath), 'utf8');

describe('DocGraphCheck v4: ADR 索引は docs/person/decisions/README.md に出す', () => {
  let root: string;
  beforeEach(async () => {
    root = makeRoot();
    writeValidTree(root);
    await converge(root);
  });

  it('[TST-104] ADR の表は decisions/README.md に、仮・未決の行は決定台帳に、パスの順で出る。0 件なら _該当なし_', async () => {
    // G5: 年をまたぐ ADR が、decisions/ からの相対パスのリンクで 1 つの表に並ぶ。docs/adr/ は作らない
    const readme = read(root, 'docs/person/decisions/README.md');
    assert.match(readme, /\| \[0001\]\(2025\/0001-use-postgres\.md\) \| adr-0001-use-postgres の題名 \| accepted \|/);
    assert.match(readme, /\| \[0002\]\(2026\/0002-queue\.md\) \| adr-0002-queue の題名 \| amended \|/);
    assert.match(readme, /\| \[0003\]\(2026\/0003-cache\.md\) \| adr-0003-cache の題名 \| proposed \|/);
    assert.ok(readme.indexOf('[0001]') < readme.indexOf('[0002]') && readme.indexOf('[0002]') < readme.indexOf('[0003]'));
    assert.equal(existsSync(join(root, 'docs', 'adr')), false, 'docs/adr/ を勝手に作っている');

    // G6: 仮の行と未決の行を持つ人の文書 2 本。台帳の一覧は、docs/ からのパスの順 (design/ が requirements/ より前)
    const bookingPath = 'docs/person/design/reservation/flows/01-booking.md';
    const requirementsPath = 'docs/person/requirements/01-requirements.md';
    const writeLog = (state102: string, state003: string): void => {
      write(root, 'docs/person/decisions/01-decisions.md', DECISION_LOG);
      write(
        root,
        bookingPath,
        doc('reservation-booking', 'business-flow', {
          context: 'reservation',
          dependsOn: ['reservation-map'],
          body: decisionTable([
            ['BF-101', '予約を確定する', '決定'],
            ['BF-102', 'キャンセル料は 0 円', state102],
          ]),
        }),
      );
      write(
        root,
        requirementsPath,
        doc('requirements', 'requirements', {
          arc42: 1,
          body: decisionTable([
            ['REQ-001', 'ADR-0001 の決定を反映する', '決定'],
            ['REQ-002', 'ADR-0002 の決定を反映する', '決定'],
            ['REQ-003', '予約は 15 分で失効する', state003],
          ]),
        }),
      );
    };
    writeLog('未決', '仮');
    await converge(root);
    const lineOf = (path: string, needle: string): number => read(root, path).split('\n').findIndex((line) => line.startsWith(needle)) + 1;
    const log = read(root, 'docs/person/decisions/01-decisions.md');
    const region = log.slice(log.indexOf('AUTOGEN:tentative-index:start'), log.indexOf('AUTOGEN:tentative-index:end'));
    assert.deepEqual(
      region.split('\n').filter((line) => line.startsWith('|')),
      [
        '| 対象 ID | 状態 | 場所 | 決まり |',
        '|---|---|---|---|',
        `| reservation-booking/BF-102 | 未決 | [${bookingPath}:${lineOf(bookingPath, '| BF-102')}](../design/reservation/flows/01-booking.md#L${lineOf(bookingPath, '| BF-102')}) | キャンセル料は 0 円 |`,
        `| requirements/REQ-003 | 仮 | [${requirementsPath}:${lineOf(requirementsPath, '| REQ-003')}](../requirements/01-requirements.md#L${lineOf(requirementsPath, '| REQ-003')}) | 予約は 15 分で失効する |`,
      ],
    );
    assert.deepEqual((await run(root, 'check')).violations, []);

    // 仮・未決が 0 件になれば、_該当なし_
    writeLog('決定', '決定');
    await converge(root);
    const emptied = read(root, 'docs/person/decisions/01-decisions.md');
    assert.match(emptied.slice(emptied.indexOf('AUTOGEN:tentative-index:start')), /-->\n\n_該当なし_\n\n<!-- AUTOGEN:tentative-index:end/);
    assert.deepEqual((await run(root, 'check')).violations, []);
  });

  it('書いた直後の木は、check で違反も警告も出ない (索引・年のフォルダの README・依存グラフが収束している)', async () => {
    const result = await run(root, 'check');
    assert.deepEqual(result.violations, [], result.detail);
    assert.deepEqual(result.warnings, []);
  });

  it('decisions/README.md の ADR 索引とディレクトリ索引は共存する。ADR を足して write しても、古い ADR 索引に戻らない', async () => {
    const before = read(root, 'docs/person/decisions/README.md');
    assert.match(before, /AUTOGEN:dir-index:start[\s\S]*\[2025\/\]\(2025\/README\.md\)[\s\S]*\[2026\/\]\(2026\/README\.md\)[\s\S]*AUTOGEN:dir-index:end/);
    write(root, 'docs/person/decisions/2026/0004-search.md', adr('0004', 'search', 'accepted'));
    writeRequirements(root, ['0001', '0002', '0004']);
    await converge(root);
    const after = read(root, 'docs/person/decisions/README.md');
    assert.match(after, /\| \[0004\]\(2026\/0004-search\.md\) \| adr-0004-search の題名 \| accepted \|/);
    assert.match(after, /AUTOGEN:dir-index:start[\s\S]*\[2026\/\]\(2026\/README\.md\)/);
    // 年のフォルダの README にも、その年の ADR が出る
    assert.match(read(root, 'docs/person/decisions/2026/README.md'), /\[0004-search\.md\]\(0004-search\.md\)/);
    const result = await run(root, 'check');
    assert.deepEqual(result.violations, [], result.detail);
  });

  it('ADR のタイトルを直して再生成しないと、check は ADR 索引が古いと落ちる (file は新しい場所)', async () => {
    write(
      root,
      'docs/person/decisions/2025/0001-use-postgres.md',
      doc('adr-0001-use-postgres', 'adr', { type: 'adr', arc42: 9, status: 'accepted' }).map((line) =>
        line.startsWith('title:') ? 'title: ADR-0001 PostgreSQL を使う (改題)' : line,
      ),
    );
    const result = await run(root, 'check');
    assert.ok(
      result.violations.some(
        (violation) => violation.file === 'docs/person/decisions/README.md' && /ADR 索引が out of date/.test(violation.message),
      ),
      result.detail,
    );
    assert.ok(!result.violations.some((violation) => violation.file === 'docs/adr/README.md'));
  });

  it('[TST-307] ADR があるのに decisions/README.md が無い・adr-index の区間が無いと、新しい場所を名指しして落ちる', async () => {
    const cases: ReadonlyArray<{ readonly name: string; readonly prepare: () => void; readonly message: RegExp }> = [
      {
        name: 'README.md が無い (docs/adr/README.md は求めない)',
        prepare: () => rmSync(join(root, 'docs', 'person', 'decisions', 'README.md')),
        message: /docs\/person\/decisions\/README\.md が無い/,
      },
      {
        name: 'adr-index の区間が無い',
        prepare: () => write(root, 'docs/person/decisions/README.md', DECISIONS_README.filter((line) => !line.includes('adr-index'))),
        message: /docs\/person\/decisions\/README\.md に AUTOGEN マーカーが無い/,
      },
    ];
    for (const { name, prepare, message } of cases) {
      prepare();
      for (const mode of ['write', 'check'] as const) {
        const result = await run(root, mode);
        assert.equal(result.violations.length, 1, `${name} (${mode}): ${result.detail}`);
        assert.match(result.violations[0]?.message ?? '', message, `${name} (${mode})`);
        assert.doesNotMatch(result.violations[0]?.message ?? '', /docs\/adr\/README\.md/, `${name} (${mode})`);
      }
    }
  });

  it('ADR が 1 本も無い新しい構成は、decisions/README.md を求めず、docs/adr/ も作らない', async () => {
    const empty = makeRoot();
    write(empty, 'docs/person/requirements/01-requirements.md', doc('requirements', 'requirements', { arc42: 1 }));
    write(empty, 'docs/ai/handbook/how-to/01-setup.md', doc('setup', 'guide', { type: 'guide' }));
    await converge(empty);
    assert.equal(existsSync(join(empty, 'docs', 'adr')), false);
    assert.equal(existsSync(join(empty, 'docs', 'person', 'decisions')), false);
    const result = await run(empty, 'check');
    assert.deepEqual(result.violations, [], result.detail);
  });

  it('年のフォルダをまたいで同じ番号の ADR があれば、番号の重複で落ちる', async () => {
    write(root, 'docs/person/decisions/2025/0002-other.md', adr('0005', 'other', 'accepted'));
    const result = await run(root, 'check');
    assert.equal(result.violations.length, 1, result.detail);
    const message = result.violations[0]?.message ?? '';
    assert.match(message, /ADR 番号の重複検出:\n {2}- ADR-0002: /);
    assert.ok(message.includes('docs/person/decisions/2025/0002-other.md') && message.includes('docs/person/decisions/2026/0002-queue.md'), message);
  });

  it('新しい構成では ADR の status に amended が使える。語彙の外の値は落ちる', async () => {
    write(root, 'docs/person/decisions/2026/0003-cache.md', adr('0003', 'cache', 'adopted'));
    const result = await run(root, 'write');
    assert.equal(result.violations.length, 1, result.detail);
    assert.match(result.violations[0]?.message ?? '', /status="adopted" は許可外 \(adr: .*amended/);
  });
});

describe('DocGraphCheck: 旧い構成の ADR 索引は変えない', () => {
  function writeLegacyTree(root: string): void {
    write(root, 'docs/product/requirements.md', doc('requirements', 'requirements', { arc42: 1 }));
    write(root, 'docs/adr/0001-x.md', adr('0001', 'x', 'accepted'));
    write(root, 'docs/adr/README.md', [
      '---', 'id: adr-index', 'title: ADR — 索引', 'type: index', 'status: active', 'owners: [eng]', '---', '',
      '# adr', '', '## 索引', '',
      '<!-- AUTOGEN:adr-index:start — generated by scripts/generate-docs-graph.mjs, do not edit by hand -->',
      '<!-- AUTOGEN:adr-index:end -->',
    ]);
  }

  it('docs/adr/README.md に、ファイル名のリンクで索引を出し、docs/person/ は作らない', async () => {
    const root = makeRoot();
    writeLegacyTree(root);
    await converge(root);
    assert.match(read(root, 'docs/adr/README.md'), /\| \[0001\]\(0001-x\.md\) \| adr-0001-x の題名 \| accepted \|/);
    assert.equal(existsSync(join(root, 'docs', 'person')), false);
    assert.deepEqual((await run(root, 'check')).violations, []);
  });

  it('ADR があるのに docs/adr/README.md が無ければ、これまでの文言で落ちる', async () => {
    const root = makeRoot();
    writeLegacyTree(root);
    rmSync(join(root, 'docs', 'adr', 'README.md'));
    const result = await run(root, 'check');
    assert.equal(result.violations.length, 1, result.detail);
    assert.equal(result.violations[0]?.message, '[docs-graph] docs/adr/README.md が無い (ADR があるツリーでは ADR 索引が必須). Run: --write');
  });

  it('amended は旧い構成の語彙に無く、これまでどおり許可外', async () => {
    const root = makeRoot();
    writeLegacyTree(root);
    write(root, 'docs/adr/0002-y.md', adr('0002', 'y', 'amended'));
    const result = await run(root, 'write');
    assert.equal(result.violations.length, 1, result.detail);
    assert.match(result.violations[0]?.message ?? '', /status="amended" は許可外 \(adr: proposed\|accepted\|deprecated\|superseded\|rejected\|template\)/);
  });

  it('旧い構成の docs/adr/ の番号の重複は、これまでどおり落ちる', async () => {
    const root = makeRoot();
    writeLegacyTree(root);
    write(root, 'docs/adr/0001-other.md', adr('0009', 'other', 'accepted'));
    const result = await run(root, 'check');
    assert.equal(result.violations.length, 1, result.detail);
    assert.match(result.violations[0]?.message ?? '', /ADR 番号の重複検出[\s\S]*ADR-0001/);
  });
});
