// node --test dist/checks/LegacyLayoutUnchanged.test.js
// 旧い構成 (docs/person・ai・client が無い repo) の生成物と検査の結果が、新しい構成の検査を足す前と 1 バイトも変わらないこと
// (テスト仕様 04 の適用範囲・TST-107)。sharedKinds の設定つきの旧い構成の木に、docs-graph・docs-check・context-boundary-check・
// context-files・context-size を回し、新しい構成の検査を足す前 (a9fdd0c) の build が同じ木から作った出力と比べる。
// 旧い構成の警告の文 (LEGACY_LAYOUT_MESSAGE) だけは、この版で意図して変えたので、定数で比べる。
import { createHash } from 'node:crypto';
import { globSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { after, describe, it } from 'node:test';
import assert from 'node:assert/strict';

import { ContextFilesModule } from '../generators/ContextFilesModule.js';
import { ContextSizeModule } from '../generators/ContextSizeModule.js';
import { ContextBoundaryCheck } from './ContextBoundaryCheck.js';
import { DocGraphCheck } from './DocGraphCheck.js';
import { DocsCheck } from './DocsCheck.js';
import { LEGACY_LAYOUT_MESSAGE } from './RoleBoundaryCheck.js';

const workspaces: string[] = [];

after(() => {
  for (const dir of workspaces) rmSync(dir, { recursive: true, force: true });
});

function write(root: string, relPath: string, lines: readonly string[]): void {
  const target = join(root, relPath);
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, `${lines.join('\n')}\n`);
}

/** frontmatter の行と、本文の行 */
const page = (frontmatter: readonly string[], body: readonly string[]): string[] => ['---', ...frontmatter, '---', '', ...body];

/**
 * 旧い構成 (docs/product・design・contexts・governance・adr・guides) の木。sharedKinds は function-list と map だけ
 * (既定の用語集などを共有から外す) にして、まとまりの境界の結果が設定に左右されることを見る。「仮置き」を含む行・
 * 読み手が付く kind・ADR・決定台帳・まとまり 2 つ (reservation・payment) を持つ。
 */
function writeLegacyTree(root: string): void {
  writeFileSync(join(root, '.igeta.json'), `${JSON.stringify({ sharedKinds: ['function-list', 'map'] }, null, 2)}\n`);
  const meta = (id: string, title: string, type: string, kind: string, extra: readonly string[], dependsOn: readonly string[]): string[] => [
    `id: ${id}`,
    `title: ${title}`,
    `type: ${type}`,
    `kind: ${kind}`,
    ...extra,
    'status: active',
    'owners: [eng]',
    `depends_on: [${dependsOn.join(', ')}]`,
    'relates_to: []',
  ];
  write(root, 'docs/product/01-requirements.md', page(meta('requirements', '要件定義書', 'prd', 'requirements', ['arc42: 1'], []), [
    '# 要件定義書',
    '',
    '> **TL;DR**: 予約と決済の要件。',
    '',
    '- 予約の保持時間は 15 分 (仮置き。OPEN-001)',
    '- 返金の期限は 30 日 (仮置き)',
  ]));
  write(root, 'docs/design/basic/00-glossary.md', page(meta('glossary', '用語集', 'design', 'glossary', ['arc42: 12'], ['requirements']), ['# 用語集', '', '> **TL;DR**: 用語の定義。']));
  write(root, 'docs/design/basic/01-function-list.md', page(meta('function-list', '機能一覧', 'design', 'function-list', ['arc42: 5'], ['requirements']), ['# 機能一覧', '', '> **TL;DR**: 機能の一覧。']));
  write(root, 'docs/design/basic/flows/01-booking.md', page(meta('reservation-flow', '予約の業務フロー', 'design', 'business-flow', ['context: reservation', 'arc42: 6'], ['function-list', 'payment-contract']), [
    '# 予約の業務フロー',
    '',
    '> **TL;DR**: 予約の流れ。',
    '',
    '[機能一覧](../01-function-list.md) と [用語集](../00-glossary.md) と [決済の約束](../../../contexts/payment/contract.md) を見る。',
  ]));
  write(root, 'docs/design/basic/flows/02-refund.md', page(meta('payment-flow', '返金の業務フロー', 'design', 'business-flow', ['context: payment', 'arc42: 6'], ['function-list']), ['# 返金の業務フロー', '', '> **TL;DR**: 返金の流れ。']));
  write(root, 'docs/contexts/payment/contract.md', page(meta('payment-contract', '決済の約束', 'design', 'context-contract', ['context: payment'], ['payment-flow']), ['# 決済の約束', '', '> **TL;DR**: 決済が外へ見せるもの。']));
  write(root, 'docs/00-map.md', page(meta('map', '地図', 'design', 'map', [], []), ['# 地図', '', '> **TL;DR**: 全体の地図。']));
  write(root, 'docs/guides/01-setup.md', page(meta('setup', '手引き', 'guide', 'guide', [], []), ['# 手引き', '', '> **When to use**: 準備するとき。']));
  write(root, 'docs/governance/01-decisions.md', page(meta('decisions', '決定台帳', 'decision-log', 'decision-log', [], []), [
    '# 決定台帳',
    '',
    '> **TL;DR**: 決めたこと。',
    '',
    '## 仮置き一覧 (自動生成)',
    '',
    '<!-- AUTOGEN:tentative-index:start — generated by scripts/generate-docs-graph.mjs, do not edit by hand -->',
    '<!-- AUTOGEN:tentative-index:end -->',
  ]));
  write(root, 'docs/adr/0001-use-postgres.md', page(meta('adr-0001-use-postgres', 'PostgreSQL を使う', 'adr', 'adr', ['arc42: 9', 'proposed: 2026-09-01', 'accepted: 2026-09-02'], []).map((line) => (line === 'status: active' ? 'status: accepted' : line)), ['# ADR-0001 PostgreSQL を使う']));
  write(root, 'docs/adr/README.md', page(['id: adr-index', 'title: ADR — 索引', 'type: index', 'status: active', 'owners: [eng]'], [
    '# adr',
    '',
    '## 索引',
    '',
    '<!-- AUTOGEN:adr-index:start — generated by scripts/generate-docs-graph.mjs, do not edit by hand -->',
    '<!-- AUTOGEN:adr-index:end -->',
  ]));
}

/** 生成物 (各フォルダの README.md・依存グラフ・決定台帳) の SHA-256 の先頭 16 文字。生成日の行は毎日変わるので落とす */
function generatedDigests(root: string): Record<string, string> {
  const generated = (relPath: string): boolean =>
    relPath.endsWith('README.md') || relPath === 'docs/dependencies.md' || relPath === 'docs/governance/01-decisions.md';
  return Object.fromEntries(
    globSync('docs/**/*.md', { cwd: root })
      .map((path) => path.split('\\').join('/'))
      .filter(generated)
      .sort()
      .map((relPath) => {
        const text = readFileSync(join(root, relPath), 'utf8').replace(/^> 自動生成: .*$/m, '> 自動生成: <date>');
        return [relPath, createHash('sha256').update(text).digest('hex').slice(0, 16)] as const;
      }),
  );
}

/** 基準 (a9fdd0c) の build が、上の木から作った生成物の digest */
const BASELINE_DIGESTS: Readonly<Record<string, string>> = {
  'docs/README.md': '1a00e5dc20682e0b',
  'docs/adr/README.md': 'e191dc358bd9d102',
  'docs/contexts/README.md': 'd2b8a2b9427e21a7',
  'docs/contexts/payment/README.md': '19594fd22ae2cd14',
  'docs/dependencies.md': '90bb4850e87c86c1',
  'docs/design/README.md': '0e88636114e95faa',
  'docs/design/basic/README.md': '394f263816e9e0cf',
  'docs/design/basic/flows/README.md': 'a83d9e1aa702b157',
  'docs/governance/01-decisions.md': '6d12f294ac2d9045',
  'docs/governance/README.md': '456bd0241c52d3ed',
  'docs/guides/README.md': '46342f024c57b906',
  'docs/product/README.md': '478443d6f2520efc',
};

describe('旧い構成の検査と生成物は変わらない', () => {
  it('[TST-107] sharedKinds の設定つきの旧い構成で、docs-graph・docs-check・context-boundary-check・context-files の生成物と結果が 1 バイトも変わらない', async () => {
    const root = mkdtempSync(join(tmpdir(), 'igeta-legacy-unchanged-'));
    workspaces.push(root);
    writeLegacyTree(root);
    // 旧い構成は、Igeta の版が 1.0.0 以上になると警告でなく違反になる (ADR-0005)。版を 0.4.0 に固定した置き場所を渡す
    const igetaRoot = mkdtempSync(join(tmpdir(), 'igeta-legacy-unchanged-igeta-'));
    workspaces.push(igetaRoot);
    writeFileSync(join(igetaRoot, 'package.json'), JSON.stringify({ name: 'igeta', version: '0.4.0' }));
    const ctx = { targetRoot: root, igetaRoot };
    const read = (relPath: string): string => readFileSync(join(root, relPath), 'utf8');

    // docs-graph: 新しい木は 2 回で収束し、違反も警告も出ない
    for (let pass = 1; pass <= 2; pass += 1) {
      const graph = new DocGraphCheck({ write: true });
      assert.deepEqual(await graph.run(ctx), [], `docs-graph ${pass} 回目`);
      assert.deepEqual(graph.warnings, [], `docs-graph ${pass} 回目`);
    }
    // 生成物は 1 バイトも変わらない (各フォルダの README.md・依存グラフ・決定台帳)
    assert.deepEqual(generatedDigests(root), BASELINE_DIGESTS);
    // 読めるように、変わっていないものの要点: 読み手の表示と凡例、「仮置き」の一覧
    const basic = read('docs/design/basic/README.md');
    assert.match(basic, /\*\*用語集\*\* _\(読み手: AI\)_ `design` — 用語の定義。 ← 上流: \[requirements\]\(\.\.\/\.\.\/product\/01-requirements\.md\)/);
    assert.match(basic, /`_\(読み手: …\)_` は frontmatter `kind` から機械判定した読み手 \(顧客 \/ 開発者 \/ AI \/ 共通\)/);
    const log = read('docs/governance/01-decisions.md');
    assert.match(log, /\| OPEN \| 場所 \| 本文 \|\n\|---\|---\|---\|\n\| OPEN-001 \| \[docs\/product\/01-requirements\.md:17\]\(\.\.\/product\/01-requirements\.md#L17\) \| - 予約の保持時間は 15 分 \(仮置き。OPEN-001\) \|\n\| \*\*\(無し\)\*\* \| \[docs\/product\/01-requirements\.md:18\]/);
    assert.deepEqual(await new DocGraphCheck({}).run(ctx), [], '書いた直後の check');

    // docs-check: 違反は増えず、旧い構成の警告が 1 件
    const docsCheck = new DocsCheck();
    assert.deepEqual(await docsCheck.run(ctx), []);
    assert.deepEqual(docsCheck.warnings, [LEGACY_LAYOUT_MESSAGE]);

    // context-boundary-check: sharedKinds の設定に従う (function-list は共有で通り、用語集は共有でないので落ちる)。未割り当ての警告も出る
    const boundary = new ContextBoundaryCheck();
    assert.deepEqual(
      boundary.run(ctx).map((violation) => `${violation.file}:${violation.line} ${violation.message}`),
      ['docs/design/basic/flows/01-booking.md:18 参照先が未割り当て (context 無記入・共有 kind でもない): docs/design/basic/00-glossary.md (このまとまり: reservation)'],
    );
    assert.deepEqual(boundary.warnings, [
      '未割り当て (context 無記入・共有 kind でもない) が 5 件: docs/adr/0001-use-postgres.md, docs/design/basic/00-glossary.md, docs/governance/01-decisions.md, docs/guides/01-setup.md, docs/product/01-requirements.md',
    ]);

    // context-files・context-size: 旧い構成の範囲 (自分の文書 + 隣の約束 + 共有の map・glossary。--with-shared で共有を全部)
    const files = new ContextFilesModule({ targetRoot: root });
    assert.deepEqual(files.analyze('reservation', false).files, [
      'docs/00-map.md',
      'docs/contexts/payment/contract.md',
      'docs/design/basic/00-glossary.md',
      'docs/design/basic/flows/01-booking.md',
    ]);
    assert.deepEqual(files.analyze('reservation', true).files, [
      'docs/00-map.md',
      'docs/adr/0001-use-postgres.md',
      'docs/contexts/payment/contract.md',
      'docs/design/basic/00-glossary.md',
      'docs/design/basic/01-function-list.md',
      'docs/design/basic/flows/01-booking.md',
      'docs/governance/01-decisions.md',
      'docs/guides/01-setup.md',
      'docs/product/01-requirements.md',
    ]);
    const size = new ContextSizeModule({ targetRoot: root }).analyze('reservation');
    assert.deepEqual(size.entries.map((entry) => [entry.context, entry.files.map((file) => file.relPath), entry.totalLines]), [
      ['reservation', ['docs/contexts/payment/contract.md', 'docs/design/basic/flows/01-booking.md'], 33],
    ]);
  });
});
