// node --test dist/checks/LineClassificationConsistency.test.js
//
// main 指摘 (2 回目の /code-review 系列、5 件): 「AUTOGEN・HTML コメント・引用「」・否定 の除外が
// 検査ごとにばらばら」だったのを core/LineClassifier.ts の classifyLines / hasLiveOccurrence に
// 集約した。この集約が実際に効いていることを、同じ入力を template-check・docs-graph の仮置き収集・
// review-sheet の 3 系にそれぞれ通し、表形式で「同じ結論になる」ことを保証する回帰テスト。
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { after, describe, it } from 'node:test';
import assert from 'node:assert/strict';

import { DocTemplateCheck } from './DocTemplateCheck.js';
import { DocGraphCheck } from './DocGraphCheck.js';
import { ReviewSheetModule } from '../generators/ReviewSheetModule.js';
import { IGETA_ROOT } from '../core/Paths.js';
import { Report } from '../core/Report.js';
import { ExitCode } from '../core/ExitCode.js';

const workspaces: string[] = [];

function writeDoc(root: string, rel: string, lines: readonly string[]): void {
  const target = join(root, 'docs', rel);
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, `${lines.join('\n')}\n`);
}

function makeRoot(): string {
  const root = mkdtempSync(join(tmpdir(), 'igeta-classification-'));
  workspaces.push(root);
  return root;
}

after(() => {
  for (const dir of workspaces) rmSync(dir, { recursive: true, force: true });
});

const decisionLogLines = (): string[] => [
  '---', 'id: decisions', 'title: 決定台帳', 'kind: decision-log', 'depends_on: []', '---', '',
  '## 1. 決定 (DEC)', '',
  '| ID | 日付 | 決めた人 | 原文 | 決定 | 影響する文書 |',
  '|---|---|---|---|---|---|', '',
  '## 2. 未決 (OPEN)', '',
  '| ID | 論点 | 推奨案 | 仮置き値 | 影響する文書 |',
  '|---|---|---|---|---|', '',
  '## 3. 仮置き一覧 (自動生成)', '',
  '<!-- AUTOGEN:tentative-index:start — generated by scripts/generate-docs-graph.mjs, do not edit by hand -->',
  '<!-- AUTOGEN:tentative-index:end -->', '',
];

const mapLines = (): string[] => [
  '---', 'id: map', 'title: 地図', 'kind: map', 'line_limit: 150', 'depends_on: []', '---', '',
  '> **TL;DR**: テスト。', '',
  '## 関連', '', '| 区分 | 文書 | 対応 ID |', '|---|---|---|',
  '| 上流 (depends_on) | なし | — |', '| 下流 | [要件定義書](./product/requirements.md) | — |', '',
  ...['1. 何を作るか', '2. 誰が使うか', '3. 主要フロー', '4. やらないこと', '5. 詳細への入口'].flatMap((s) => [
    `## ${s}`,
    '',
    s === '5. 詳細への入口' ? '[要件定義書](./product/requirements.md)' : 'x',
    '',
  ]),
];

const requirementsHeaderLines = (): string[] => [
  '---', 'id: requirements', 'title: 要件定義書', 'kind: requirements', 'depends_on: []', '---', '',
  '> **TL;DR**: テスト。', '',
  '## 関連', '', '| 区分 | 文書 | 対応 ID |', '|---|---|---|',
  '| 上流 (depends_on) | なし | — |', '| 下流 | なし | — |', '',
  '## 1. 業務要件', '',
  '| ID | 業務要件 | 現状の課題 | 受入基準 | 出典 |',
  '|---|---|---|---|---|',
  '| REQ-001 | 予約したい | 電話予約しかない | 予約が作成されること | ヒアリング |', '',
];

interface TentativeScenario {
  readonly name: string;
  /** requirements.md の本文に足す行 (「仮置き」を含む) */
  readonly snippet: readonly string[];
  /** 「仮置き」が主張として有効 (OPEN 参照が必要/仮置き一覧に載る) かどうか */
  readonly live: boolean;
}

// 4 種類の除外区間 + 生の主張 (対照)。同じ判定 (classifyLines / hasLiveOccurrence) を
// template-check (checkDecisionAttribution) と docs-graph (collectTentativeMarks) の両方が使う。
const TENTATIVE_SCENARIOS: readonly TentativeScenario[] = [
  { name: '生の本文 (対照): OPEN 参照が無い仮置きは主張として有効', snippet: ['猶予は仮置きで30日とする。'], live: true },
  { name: '引用「」内: 主張ではない', snippet: ['前版は「仮置き」と書かれていたが、正式値に更新した。'], live: false },
  { name: '否定直後: 主張ではない', snippet: ['この値は仮置きではない。'], live: false },
  { name: 'HTML コメント内: 主張ではない', snippet: ['<!-- 猶予は仮置きで30日とする。 -->'], live: false },
  {
    name: 'AUTOGEN 区間内: 主張ではない (他文書の行の索引)',
    snippet: ['<!-- AUTOGEN:x:start -->', '猶予は仮置きで30日とする。', '<!-- AUTOGEN:x:end -->'],
    live: false,
  },
];

describe('表: 「仮置き」の有効性は template-check と docs-graph で同じ結論になる', () => {
  for (const scenario of TENTATIVE_SCENARIOS) {
    it(`template-check: ${scenario.name} → ${scenario.live ? '違反 (OPEN 参照を要求)' : '違反なし'}`, () => {
      const root = makeRoot();
      writeDoc(root, '00-map.md', mapLines());
      writeDoc(root, '01-decisions.md', decisionLogLines());
      writeDoc(root, 'product/requirements.md', [...requirementsHeaderLines(), ...scenario.snippet, '']);
      const result = new DocTemplateCheck({ requireKind: true, requireHumanReview: true }).analyze({
        targetRoot: root,
        igetaRoot: IGETA_ROOT,
      });
      const report = new Report();
      report.addAll(result.violations);
      const hasTentativeViolation = /「仮置き」に OPEN-nnn の参照が無い/.test(report.format());
      assert.equal(hasTentativeViolation, scenario.live, report.format());
    });

    it(`docs-graph (仮置き収集): ${scenario.name} → ${scenario.live ? '仮置き一覧に載る' : '仮置き一覧に載らない'}`, async () => {
      const root = makeRoot();
      writeDoc(root, '01-decisions.md', decisionLogLines());
      writeDoc(root, 'product/requirements.md', [...requirementsHeaderLines(), ...scenario.snippet, '']);
      const check = new DocGraphCheck({ write: true });
      const violations = await check.run({ targetRoot: root, igetaRoot: IGETA_ROOT });
      const report = new Report();
      report.addAll(violations);
      assert.equal(report.exitCode, ExitCode.Ok, `docs-graph --write:\n${report.format()}\n${check.warnings.join('\n')}`);
      const index = readFileSync(join(root, 'docs', '01-decisions.md'), 'utf8');
      const collected = !index.includes('_該当なし_');
      assert.equal(collected, scenario.live, index);
    });
  }
});

interface DefinitionScenario {
  readonly name: string;
  /** requirements.md に足す REQ-101 の行 (定義行を含むかどうかを変える) */
  readonly lines: readonly string[];
  /** REQ-101 がこの文書の「定義」として解決されるかどうか */
  readonly isDefinition: boolean;
}

// 「行頭セルが ID の定義かどうか」の除外区間 (AUTOGEN / HTML コメント / コードフェンス)。
// 同じ判定を template-check (idHomes/collectRowDefinedTokens 経由の checkQualifiedIds) と
// review-sheet (findTableRow) の両方が使う。
const DEFINITION_SCENARIOS: readonly DefinitionScenario[] = [
  { name: '生の本文 (対照): 行頭セルは定義', lines: ['| REQ-101 | Event | 予約が確定したとき、システムは通知を送らなければならない | REQ-001 | 通知が送られること |'], isDefinition: true },
  {
    name: 'AUTOGEN 区間内: 索引であって定義ではない',
    lines: ['<!-- AUTOGEN:x:start -->', '| REQ-101 | 場所 | 本文 |', '<!-- AUTOGEN:x:end -->'],
    isDefinition: false,
  },
  {
    name: 'HTML コメント内: 記入例であって定義ではない',
    lines: ['<!-- | REQ-101 | Event | 記入例 | REQ-001 | 例 | -->'],
    isDefinition: false,
  },
  {
    name: 'コードフェンス内: 例示であって定義ではない',
    lines: ['```', '| REQ-101 | Event | 記入例 | REQ-001 | 例 |', '```'],
    isDefinition: false,
  },
];

describe('表: ID 行の「定義」判定は template-check と review-sheet で同じ結論になる', () => {
  for (const scenario of DEFINITION_SCENARIOS) {
    it(`template-check (修飾 ID): ${scenario.name} → ${scenario.isDefinition ? '他文書からの裸参照は違反' : '裸参照でも違反なし (未知の ID)'}`, () => {
      const root = makeRoot();
      writeDoc(root, '00-map.md', mapLines());
      writeDoc(root, '01-decisions.md', decisionLogLines());
      writeDoc(root, 'product/requirements.md', [...requirementsHeaderLines(), ...scenario.lines, '']);
      // 別文書から REQ-101 を裸で参照する。REQ-101 が requirements 側で定義されていれば
      // 「修飾 ID で参照する」違反になり、定義されていなければ「未知の ID」として素通りする。
      writeDoc(root, 'design/basic/function-list.md', [
        '---', 'id: function-list', 'title: 機能一覧', 'kind: function-list', 'depends_on: [requirements]', '---', '',
        '> **TL;DR**: テスト。', '',
        '## 関連', '', '| 区分 | 文書 | 対応 ID |', '|---|---|---|',
        '| 上流 (depends_on) | [要件定義書](../../product/requirements.md) | REQ-101 |',
        '| 下流 | なし | — |', '',
        '## 1. 機能一覧', '', '| ID | 内容 |', '|---|---|', '| FN-001 | 予約する |', '',
        '表の外の自由記述: REQ-101 を裸で参照。', '',
      ]);
      const result = new DocTemplateCheck({ requireKind: true, requireHumanReview: true }).analyze({
        targetRoot: root,
        igetaRoot: IGETA_ROOT,
      });
      const report = new Report();
      report.addAll(result.violations);
      const flaggedAsDefined = /他ファイルの ID は修飾 ID \(<doc-id>\/REQ-101\) で参照する/.test(report.format());
      assert.equal(flaggedAsDefined, scenario.isDefinition, report.format());
    });

    it(`review-sheet (findTableRow): ${scenario.name} → ${scenario.isDefinition ? '解決できる' : '解決できない'}`, () => {
      const root = makeRoot();
      writeDoc(root, 'product/requirements.md', [...requirementsHeaderLines(), ...scenario.lines, '']);
      const result = new ReviewSheetModule({ targetRoot: root }).generate(['requirements/REQ-101']);
      const entry = result.entries[0];
      assert.equal(entry?.resolved, scenario.isDefinition, JSON.stringify(entry));
    });
  }
});
