// node --test dist/checks/PersonFormCheck.test.js
// テスト仕様 03 (docs/design/test/specs/03-person-form.md) の表の行ごとに 1 本。名前の先頭が行の ID。
// 1 つの行に複数の場合があるときは、配列を回す 1 本にする。一時ディレクトリに 3 区分・複数のまとまりの docs を作り、
// 廃の行は本物の git repo で、宛先のブランチと HEAD の枝分かれの点と比べる。
import { execFileSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { after, describe, it } from 'node:test';
import assert from 'node:assert/strict';

import { TemplateCheckCommand } from '../cli/commands/checkCommands.js';
import { IGETA_ROOT } from '../core/Paths.js';
import type { Violation } from '../core/Report.js';
import { PLACEMENTS } from '../core/Role.js';
import { DocGraphCheck } from './DocGraphCheck.js';
import type { PersonFormTemplate } from './PersonFormCheck.js';
import { PersonFormCheck } from './PersonFormCheck.js';

const workspaces: string[] = [];

after(() => {
  for (const dir of workspaces) rmSync(dir, { recursive: true, force: true });
});

function makeRoot(): string {
  const root = mkdtempSync(join(tmpdir(), 'igeta-personform-'));
  workspaces.push(root);
  return root;
}

function write(root: string, relPath: string, content: readonly string[]): void {
  const target = join(root, relPath);
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, `${content.join('\n')}\n`);
}

/** 版だけを持つ Igeta の package.json の置き場所 (合計字数の警告と違反の切替は、この版で決まる) */
function igetaRootWithVersion(version: string): string {
  const igetaRoot = makeRoot();
  writeFileSync(join(igetaRoot, 'package.json'), JSON.stringify({ name: 'igeta', version }));
  return igetaRoot;
}

// ---------------------------------------------------------------------------
// 文書の部品
// ---------------------------------------------------------------------------

/** 4 つの状態を 1 行ずつ。番号は 101〜104 で、104 が 廃 */
const ROWS: ReadonlyArray<readonly [number, string, string]> = [
  [101, '確定のときに同じ時間帯が埋まっていたら、予約は成立させない', '決定'],
  [102, '仮押さえは 15 分で解除する', '仮'],
  [103, '利用者の希望により日付を選び直せるか', '未決'],
  [104, '(作り方のため ai/ へ移した)', '廃'],
];

const row = (id: string, text: string, state: string): string => `| ${id} | ${text} | ${state} |`;
/** 決まりの表 (見出しの最後の列が 状態) */
const table = (...rows: readonly string[]): string[] => ['| ID | 決まり | 状態 |', '|---|---|---|', ...rows, ''];
const rowsOf = (prefix: string): string[] => ROWS.map(([n, text, state]) => row(`${prefix}-${n}`, text, state));
const decisions = (prefix: string): string[] => table(...rowsOf(prefix));

const MERMAID: readonly string[] = ['```mermaid', 'flowchart LR', '  A[予約] --> B[確定]', '```', ''];

/** frontmatter (kind が無い文書も作れる) と題名の次から、本文の行 */
function titled(id: string, kind: string | null, body: readonly string[], extra: readonly string[] = []): string[] {
  return [
    '---',
    `id: ${id}`,
    `title: ${id} の題名`,
    'type: design',
    ...(kind === null ? [] : [`kind: ${kind}`]),
    ...extra,
    'status: active',
    'owners: [product]',
    '---',
    '',
    `# ${id}`,
    '',
    ...body,
  ];
}

const marker = (name: string, edge: 'start' | 'end'): string =>
  edge === 'start'
    ? `<!-- AUTOGEN:${name}:start — generated by scripts/generate-docs-graph.mjs, do not edit by hand -->`
    : `<!-- AUTOGEN:${name}:end -->`;

const readme = (id: string, body: readonly string[]): string[] => [
  '---', `id: ${id}`, `title: ${id} — 索引`, 'type: index', 'status: active', 'owners: [eng]', '---', '', `# ${id}`, '', ...body,
];

const DIR_INDEX: readonly string[] = [marker('dir-index', 'start'), '- [01-x.md](01-x.md)', marker('dir-index', 'end')];

/** 型の検査が ○ の kind (要件定義書 02 §7) 12 種の文書。business-flow は 2 つのまとまりに 1 つずつ */
interface FormDoc {
  readonly id: string;
  readonly kind: string;
  readonly prefix: string;
  readonly path: string;
  readonly context?: string;
  readonly diagram?: true;
}

const FORM_DOCS: readonly FormDoc[] = [
  { id: 'requirements', kind: 'requirements', prefix: 'REQ', path: 'person/requirements/01-requirements.md' },
  { id: 'function-list', kind: 'function-list', prefix: 'FN', path: 'person/design/shared/01-function-list.md' },
  { id: 'solution-strategy', kind: 'solution-strategy', prefix: 'SS', path: 'person/design/shared/02-solution-strategy.md', diagram: true },
  { id: 'nonfunctional', kind: 'nonfunctional', prefix: 'NFR', path: 'person/design/shared/03-nonfunctional.md' },
  { id: 'permission-matrix', kind: 'permission-matrix', prefix: 'PRM', path: 'person/design/shared/04-permission-matrix.md' },
  { id: 'data-management', kind: 'data-management', prefix: 'DM', path: 'person/design/shared/05-data-management.md' },
  { id: 'as-is-overview', kind: 'as-is-overview', prefix: 'ARC', path: 'person/design/shared/06-as-is-overview.md', diagram: true },
  { id: 'risks-tech-debt', kind: 'risks-tech-debt', prefix: 'RSK', path: 'person/design/shared/07-risks-tech-debt.md' },
  { id: 'operations', kind: 'operations', prefix: 'OPS', path: 'person/design/shared/08-operations.md' },
  { id: 'migration-plan', kind: 'migration-plan', prefix: 'MIG', path: 'person/design/shared/09-migration-plan.md' },
  { id: 'reservation-booking', kind: 'business-flow', prefix: 'BF', path: 'person/design/reservation/flows/01-booking.md', context: 'reservation', diagram: true },
  { id: 'payment-refund', kind: 'business-flow', prefix: 'BF', path: 'person/design/payment/flows/01-refund.md', context: 'payment', diagram: true },
  { id: 'reservation-top', kind: 'screen-spec', prefix: 'SCR', path: 'person/design/reservation/screens/01-top.md', context: 'reservation', diagram: true },
];

/** DocTemplateCheck が雛形から渡す ID の接頭辞 */
const TEMPLATES: ReadonlyMap<string, PersonFormTemplate> = new Map(FORM_DOCS.map((doc) => [doc.kind, { idPrefixes: [doc.prefix] }]));

const docOf = (id: string): FormDoc => FORM_DOCS.find((doc) => doc.id === id) ?? assert.fail(`FORM_DOCS に無い: ${id}`);
const BOOKING = docOf('reservation-booking').path;
const REFUND = docOf('payment-refund').path;
const TOP = docOf('reservation-top').path;
const REQUIREMENTS = docOf('requirements').path;
const GLOSSARY = 'person/design/shared/10-glossary.md';
const PAYMENT_README = 'person/design/payment/README.md';
const LEDGER = 'person/decisions/01-decisions.md';
const CHAPTER = 'client/delivery/spec-v1/01-overview.md';

function formLines(doc: FormDoc, body: readonly string[] = [...(doc.diagram === true ? MERMAID : []), ...decisions(doc.prefix)]): string[] {
  return titled(doc.id, doc.kind, body, doc.context === undefined ? [] : [`context: ${doc.context}`]);
}
const booking = (body: readonly string[]): string[] => formLines(docOf('reservation-booking'), body);

/** 型の検査が ○ の kind の文書 (自分の接頭辞の決まりの行・図が要る kind は図) */
function writeFormDocs(root: string): void {
  for (const doc of FORM_DOCS) write(root, `docs/${doc.path}`, formLines(doc));
}

/** 型の検査が 図 (地図・まとまりの地図) と — (用語集・機能ブリーフ・ADR・決定台帳) の kind の文書と、ai・client の文書 */
function writeOtherDocs(root: string): void {
  write(root, 'docs/person/design/shared/00-map.md', titled('map', 'map', MERMAID));
  write(root, 'docs/person/design/reservation/00-map.md', titled('reservation-map', 'context-map', MERMAID, ['context: reservation']));
  write(root, 'docs/person/design/payment/00-map.md', titled('payment-map', 'context-map', MERMAID, ['context: payment']));
  write(root, `docs/${GLOSSARY}`, titled('glossary', 'glossary', ['| 用語 | 意味 |', '|---|---|', '| 予約 | 席を押さえること |', '']));
  write(root, 'docs/person/design/payment/features/01-refund.md', titled('payment-refund-brief', 'feature-brief', ['返金の機能ブリーフ。'], ['context: payment']));
  write(root, 'docs/person/decisions/2026/0001-use-postgres.md', titled('adr-0001-use-postgres', 'adr', ['## Decision', '', 'PostgreSQL を使う。']));
  write(root, `docs/${LEDGER}`, titled('decisions', 'decision-log', ['| ID | 日付 | 決定 |', '|---|---|---|', '| DEC-001 | 2026-10-01 | 採用 |', '']));
  write(root, 'docs/ai/specs/reservation/api/01-reserve.md', [
    ...titled('reservation-api', 'api-spec', ['<!-- ai/ の文書のコメントは書いてよい -->', '', '| API-001 | 予約する | 仮 |', ''], ['context: reservation']),
    '<!-- AUTOGEN:api-index:start — generated from packages/api-contract -->',
    '| API-001 |',
    '<!-- AUTOGEN:api-index:end -->',
  ]);
  write(root, 'docs/ai/handbook/how-to/01-setup.md', titled('setup', 'guide', ['手順。']));
  write(root, `docs/${CHAPTER}`, titled('delivery-overview', 'delivery-chapter', ['顧客に渡す章。']));
  write(root, 'docs/client/proposals/2026/01-proposal.md', titled('proposal-1', 'proposal', ['提案。']));
}

/** 生成区間を持つ文書。README.md (見出し・目的の 1 行・dir-index)・decisions/README.md (adr-index と dir-index)・決定台帳 (tentative-index) */
function writeGeneratedDocs(root: string): void {
  write(root, 'docs/person/README.md', readme('person-index', ['> このディレクトリの目的: 人が確定させる文書。', '', '## 索引', '', ...DIR_INDEX]));
  write(root, 'docs/person/design/reservation/README.md', readme('reservation-index', ['> このディレクトリの目的: 予約のまとまり。', '', ...DIR_INDEX]));
  write(root, 'docs/client/README.md', readme('client-index', ['> このディレクトリの目的: 顧客と合意する文書。', '', ...DIR_INDEX]));
  write(root, 'docs/person/decisions/README.md', readme('decisions-index', [
    '> このディレクトリの目的: 決定の記録。', '', marker('adr-index', 'start'), '| # | タイトル |', marker('adr-index', 'end'), '', ...DIR_INDEX,
  ]));
  write(root, `docs/${LEDGER}`, [
    ...titled('decisions', 'decision-log', ['## 仮・未決の一覧', '']),
    marker('tentative-index', 'start'), '_該当なし_', marker('tentative-index', 'end'),
  ]);
}

function writeValidTree(root: string): void {
  writeFormDocs(root);
  writeOtherDocs(root);
  writeGeneratedDocs(root);
}

// ---------------------------------------------------------------------------
// 実行と照合
// ---------------------------------------------------------------------------

interface RunOptions {
  readonly igetaRoot?: string;
  readonly base?: string;
  readonly docsDir?: string;
  readonly templates?: ReadonlyMap<string, PersonFormTemplate>;
}

interface RunResult {
  readonly violations: readonly Violation[];
  readonly warnings: readonly string[];
}

/** 警告の段階 (メジャー版 0) の Igeta */
const WARNING_STAGE_IGETA = igetaRootWithVersion('0.9.9');

function run(root: string, options: RunOptions = {}): RunResult {
  const check = new PersonFormCheck({ docsDir: options.docsDir, templates: options.templates ?? TEMPLATES, base: options.base });
  const violations = check.run({ targetRoot: root, igetaRoot: options.igetaRoot ?? WARNING_STAGE_IGETA });
  return { violations, warnings: check.warnings };
}

/** 正しい構成のうち、1 つの文書を差し替えて検査する */
function runWith(path: string, lines: readonly string[], options: RunOptions = {}): RunResult {
  const root = makeRoot();
  writeValidTree(root);
  write(root, `docs/${path}`, lines);
  return run(root, options);
}

const posix = (path: string | undefined): string => (path ?? '').split('\\').join('/');
const describeAll = (result: RunResult): string => result.violations.map((violation) => `${violation.file}:${violation.line} ${violation.message}`).join('\n');

/** 文書の行の配列から、条件に合う最初の行の、1 始まりの行番号 */
function lineOf(lines: readonly string[], predicate: (line: string) => boolean): number {
  const index = lines.findIndex(predicate);
  assert.ok(index >= 0, '行が見つからない');
  return index + 1;
}

/** 違反がちょうど 1 件で、その file・line・文言が期待どおり */
function assertOnly(result: RunResult, file: string, line: number, message: RegExp, label: string): void {
  assert.equal(result.violations.length, 1, `${label}: ${describeAll(result)}`);
  const [violation] = result.violations;
  assert.equal(violation?.severity, 'violation', label);
  assert.equal(posix(violation?.file), `docs/${file}`, label);
  assert.equal(violation?.line, line, label);
  assert.match(violation?.message ?? '', message, label);
}

/** 行数がちょうど n になるまで、補足の行を足す */
const padTo = (lines: readonly string[], n: number): string[] => [...lines, ...Array.from({ length: n - lines.length }, (_, i) => `補足 ${i + 1}`)];

/** 本文の字が chars 字になる行 (1 行 100 字、最後の行は端数)。ch は 1 字 (サロゲートペアの字でも 1 字) */
const fill = (ch: string, chars: number): string[] =>
  Array.from({ length: Math.ceil(chars / 100) }, (_, i) => ch.repeat(Math.min(100, chars - i * 100)));

// ---------------------------------------------------------------------------
// 1. テストケース一覧
// ---------------------------------------------------------------------------

describe('テスト仕様 03 §1 テストケース一覧', () => {
  it('[TST-101] ○ の kind の文書 (自分の接頭辞の決まりの行・図が要る kind は図) は違反 0 件。○ の kind 12 種の全部で確かめる', () => {
    const fullKinds = PLACEMENTS.filter((placement) => placement.formCheck === 'full').map((placement) => placement.kind).sort();
    assert.deepEqual([...new Set(FORM_DOCS.map((doc) => doc.kind))].sort(), fullKinds, 'fixture が ○ の kind の全部を持つ');
    const root = makeRoot();
    writeFormDocs(root);
    assert.deepEqual(run(root), { violations: [], warnings: [] });
  });

  it('[TST-102] 図だけの kind (地図・まとまりの地図) に図があり表が無い / 用語集・機能ブリーフ・ADR・決定台帳に決まりの表が無い → 違反 0 件', () => {
    const root = makeRoot();
    writeOtherDocs(root);
    assert.deepEqual(run(root), { violations: [], warnings: [] });
  });

  it('[TST-103] kind が無く置き場所で決まる文書は型の検査を受ける。kind と置き場所が別の kind を指す文書は型の違反を出さない', () => {
    const flow = 'person/design/reservation/flows/02-extra.md';
    const body = ['表も図も無い。'];
    // kind が無い: 置き場所の型から business-flow と決まり、決まりの行 (BF) と図が求められる
    const checked = runWith(flow, titled('extra', null, body, ['context: reservation'])).violations;
    assert.deepEqual(checked.map((violation) => posix(violation.file)), Array<string>(2).fill(`docs/${flow}`));
    assert.ok(checked.some((violation) => /^決まりの行が 1 つも無い .*BF-nnn/.test(violation.message)));
    assert.ok(checked.some((violation) => /^図が 1 枚も無い \(kind: business-flow/.test(violation.message)));
    // kind が screen-spec: 置き場所の型 (business-flow) と別の kind を指すので、型の検査をしない (置き場所の検査が違反にする)
    assert.deepEqual(runWith(flow, titled('extra', 'screen-spec', body, ['context: reservation'])).violations, []);
  });

  it('[TST-104] ○ の kind がちょうど 100 行 / requirements がちょうど 150 行 → 違反 0 件', () => {
    const root = makeRoot();
    writeValidTree(root);
    write(root, `docs/${BOOKING}`, padTo(booking([...MERMAID, ...decisions('BF')]), 100));
    write(root, `docs/${REQUIREMENTS}`, padTo(formLines(docOf('requirements')), 150));
    assert.deepEqual(run(root).violations, []);
  });

  it('[TST-105] 合計字数: 上限ちょうどは何も出ない。1 字超は版 0 で警告、版 1 で違反。frontmatter・コードフェンス・README.md の字は数えず、全角も半角も 1 字', () => {
    const doc = (id: string, kind: string, context: string | null, body: readonly string[], fm: readonly string[] = []): string[] => [
      '---', `id: ${id}`, `kind: ${kind}`, ...(context === null ? [] : [`context: ${context}`]), ...fm, '---', ...body,
    ];
    // 要件の文書の本文の字数 (frontmatter を除く)。全体共通の残りを、上限ちょうどになるように用意する
    const requirements = formLines(docOf('requirements'));
    const requirementsChars = requirements.slice(requirements.lastIndexOf('---') + 1).reduce((sum, line) => sum + [...line].length, 0);
    /** まとまり 3 つと全体共通が、どれも上限ちょうど。reservation は半角と全角、payment はサロゲートペアの字。extra は 1 字だけ足す */
    function writeAtLimits(root: string, extra: { reservation?: string; global?: string } = {}): void {
      write(root, 'docs/person/design/reservation/features/01-a.md', doc('a', 'feature-brief', 'reservation', fill('a', 7_500)));
      write(root, 'docs/person/design/reservation/features/02-b.md', doc('b', 'feature-brief', 'reservation', [...fill('あ', 7_500), ...(extra.reservation === undefined ? [] : [extra.reservation])]));
      write(root, 'docs/person/design/payment/features/01-c.md', doc('c', 'feature-brief', 'payment', fill('𠮷', 15_000)));
      write(root, 'docs/person/design/billing/features/01-d.md', doc('d', 'feature-brief', 'billing', fill('あ', 100)));
      write(root, `docs/${REQUIREMENTS}`, requirements);
      write(root, 'docs/person/design/shared/10-glossary.md', doc('g', 'glossary', null, [...fill('あ', 30_000 - requirementsChars), ...(extra.global === undefined ? [] : [extra.global])]));
    }

    for (const version of ['0.9.9', '1.0.0']) {
      const igetaRoot = igetaRootWithVersion(version);
      const root = makeRoot();
      writeAtLimits(root);
      assert.deepEqual(run(root, { igetaRoot }), { violations: [], warnings: [] }, `${version}: 上限ちょうど`);

      // frontmatter・コードフェンス・README.md に字を足しても、合計は変わらない
      write(root, 'docs/person/design/reservation/features/02-b.md', doc('b', 'feature-brief', 'reservation', [...fill('あ', 7_500), '```text', ...fill('あ', 5_000), '```'], [`memo: ${'あ'.repeat(5_000)}`]));
      write(root, 'docs/person/design/reservation/README.md', readme('reservation-index', ['あ'.repeat(3_000)]));
      assert.deepEqual(run(root, { igetaRoot }), { violations: [], warnings: [] }, `${version}: 数えない字を足した`);

      for (const [subject, extra, total, file] of [
        ['まとまり reservation', { reservation: 'あ' }, '15,001', 'docs/person/design/reservation'],
        ['全体共通', { global: 'a' }, '30,001', 'docs/person/design/shared'],
      ] as const) {
        writeAtLimits(root, extra);
        const result = run(root, { igetaRoot });
        const text = new RegExp(`^${subject} .*${total} 字で、上限`);
        if (version === '0.9.9') {
          assert.deepEqual(result.violations, [], `${version} ${subject}`);
          assert.equal(result.warnings.length, 1, `${version} ${subject}`);
          assert.match(result.warnings[0] ?? '', text);
        } else {
          assert.deepEqual(result.warnings, [], `${version} ${subject}`);
          assert.equal(result.violations.length, 1, `${version} ${subject}`);
          assert.equal(result.violations[0]?.severity, 'violation');
          assert.equal(posix(result.violations[0]?.file), file);
          assert.match(result.violations[0]?.message ?? '', text);
        }
      }
    }
  });

  it('[TST-106] 廃の行: 起点で 廃 の行がいまも廃 / この変更で 決定 を 廃 に変えた / 枝を切った後で宛先が別の行を 廃 にした (古い枝ではその行が 決定 のまま) → `--base <宛先>` で違反 0 件', () => {
    const root = makeRepo();
    git(root, 'checkout', '-q', '-b', 'feature');
    assert.deepEqual(run(root, { base: 'dest' }).violations, [], '起点で 廃 の行が、いまも 廃');

    // この変更で、決定 を 廃 に変える
    write(root, `docs/${BOOKING}`, formLines(docOf('reservation-booking')).map((line) => (line.startsWith('| BF-101 ') ? line.replace('| 決定 |', '| 廃 |') : line)));
    commit(root, '決定の行を廃にした');
    assert.deepEqual(run(root, { base: 'dest' }).violations, [], 'この変更で 決定 を 廃 にした');

    // 枝を切った後で、宛先が別の行 (payment-refund の BF-101) を 廃 にする。この枝では、その行は 決定 のまま
    git(root, 'checkout', '-q', 'dest');
    write(root, `docs/${REFUND}`, formLines(docOf('payment-refund')).map((line) => (line.startsWith('| BF-101 ') ? line.replace('| 決定 |', '| 廃 |') : line)));
    commit(root, '宛先で別の行を廃にした');
    git(root, 'checkout', '-q', 'feature');
    assert.deepEqual(run(root, { base: 'dest' }).violations, [], '宛先の先端ではなく、枝分かれの点と比べる');
  });

  it('[TST-107] README.md (見出し・目的の 1 行・dir-index) / decisions/README.md (adr-index と dir-index) / 決定台帳 (tentative-index) → 違反 0 件。生成器 (docs-graph) が書き直した後も同じ', async () => {
    const root = makeRoot();
    writeGeneratedDocs(root);
    assert.deepEqual(run(root), { violations: [], warnings: [] });

    // 検査が例外にする印の文字列は、生成器が書く文字列と同じでなければならない。ADR を足して、生成器に区間を書き直させる
    write(root, 'docs/person/decisions/2026/0001-use-postgres.md', [
      '---', 'id: adr-0001-use-postgres', 'title: ADR-0001 PostgreSQL を使う', 'type: adr', 'kind: adr', 'arc42: 9', 'status: accepted', 'owners: [eng]', 'depends_on: []', 'relates_to: []', '---', '', '# ADR-0001',
    ]);
    for (let pass = 1; pass <= 2; pass += 1) {
      assert.deepEqual(await new DocGraphCheck({ write: true }).run({ targetRoot: root, igetaRoot: IGETA_ROOT }), [], `docs-graph --write (${pass} 回目)`);
    }
    assert.deepEqual(run(root), { violations: [], warnings: [] }, '生成器が書き直した README.md・決定台帳');
  });

  it('[TST-108] 旧い構成の repo / `docs/ai/` の文書の HTML コメント → 何も出ない', () => {
    const legacy = makeRoot();
    write(legacy, 'docs/design/basic/flows/01-booking.md', titled('booking', 'business-flow', ['<!-- コメント -->', '表も図も無い。']));
    write(legacy, 'docs/design/basic/README.md', readme('basic-index', ['文章。', '文章。', '文章。']));
    assert.deepEqual(run(legacy, { base: 'no-such-ref' }), { violations: [], warnings: [] });

    const root = makeRoot();
    writeValidTree(root);
    write(root, 'docs/ai/handbook/how-to/02-comments.md', titled('comments', 'guide', ['<!-- 1 行 -->', '<!--', '複数行', '-->']));
    assert.deepEqual(run(root), { violations: [], warnings: [] });
  });
});

// ---------------------------------------------------------------------------
// 2. 否定テスト
// ---------------------------------------------------------------------------

describe('テスト仕様 03 §2 否定テスト', () => {
  it('[TST-301] ○ の kind に、自分の接頭辞の決まりの行が 1 つも無い (表が無い / 別の接頭辞の行だけ) → 違反', () => {
    const cases: ReadonlyArray<readonly [string, readonly string[]]> = [
      ['表が無い', [...MERMAID, '予約の流れを文章だけで書いた。']],
      ['別の接頭辞 (REQ) の決まりの行だけ', [...MERMAID, ...decisions('REQ')]],
    ];
    for (const [name, body] of cases) {
      assertOnly(runWith(BOOKING, booking(body)), BOOKING, 1, /^決まりの行が 1 つも無い .*BF-nnn/, name);
    }
  });

  it('[TST-302] 自分の接頭辞の ID の行を持つ表の最後の列が `状態` でない (列が無い / 最後ではない) → 違反 (見出しの行)', () => {
    const cases: ReadonlyArray<readonly [string, string, readonly string[]]> = [
      ['状態の列が無い', '| ID | 決まり | 強さ |', ['| BF-101 | 予約は成立させない | 強い |', '| BF-102 | 15 分で解除する | 弱い |']],
      ['状態の列が最後ではない', '| ID | 状態 | 決まり |', ['| BF-101 | 決定 | 予約は成立させない |', '| BF-102 | 仮 | 15 分で解除する |']],
    ];
    for (const [name, header, rows] of cases) {
      const lines = booking([...MERMAID, header, '|---|---|---|', ...rows, '']);
      assertOnly(runWith(BOOKING, lines), BOOKING, lineOf(lines, (line) => line === header), /^BF-nnn の行が、決まりの表ではない表にある/, name);
    }
  });

  it('[TST-303] 決まりの表の 1 行だけ、最初のセルを `**BF-130**`・`bf-130`・`ＢＦ-130`・`BF-1130`・`BF-130 (案)` にする → どれも違反 (その行)', () => {
    for (const cell of ['**BF-130**', 'bf-130', 'ＢＦ-130', 'BF-1130', 'BF-130 (案)']) {
      const lines = booking([...MERMAID, ...table(...rowsOf('BF'), row(cell, '隠した決まり', '決定'))]);
      const result = runWith(BOOKING, lines);
      assertOnly(result, BOOKING, lineOf(lines, (line) => line.startsWith(`| ${cell} |`)), /^決まりの表の行の最初のセルが ID の形ではない/, cell);
      assert.ok(result.violations[0]?.message.includes(`「${cell}」`), cell);
    }
  });

  it('[TST-304] 最後のセルが `確定`・空・`決定 (仮)` → 違反 (その行)。自分の接頭辞の行でも、別の接頭辞の行でも、○ でない kind (用語集) の決まりの表でも同じ', () => {
    const targets: ReadonlyArray<{ name: string; path: string; id: string; build: (hidden: string) => string[] }> = [
      { name: '自分の接頭辞', path: BOOKING, id: 'BF-130', build: (hidden) => booking([...MERMAID, ...table(...rowsOf('BF'), hidden)]) },
      { name: '別の接頭辞', path: BOOKING, id: 'REQ-130', build: (hidden) => booking([...MERMAID, ...table(...rowsOf('BF'), hidden)]) },
      { name: '用語集の決まりの表', path: GLOSSARY, id: 'GL-130', build: (hidden) => titled('glossary', 'glossary', table(hidden)) },
    ];
    for (const { name, path, id, build } of targets) {
      for (const state of ['確定', '', '決定 (仮)']) {
        const hidden = row(id, '隠した決まり', state);
        const lines = build(hidden);
        assertOnly(runWith(path, lines), path, lineOf(lines, (line) => line === hidden), new RegExp(`^${id} の状態が不正`), `${name} / 「${state}」`);
      }
    }
  });

  it('[TST-305] 決まりの行の列の数が見出しと違う (少ない / 多い) → 違反 (その行)', () => {
    for (const bad of ['| BF-130 | 決まり |', '| BF-130 | 決まり | 決定 | 余り |']) {
      const lines = booking([...MERMAID, ...table(...rowsOf('BF'), bad)]);
      assertOnly(runWith(BOOKING, lines), BOOKING, lineOf(lines, (line) => line === bad), /^BF-130 の行の列数/, bad);
    }
  });

  it('[TST-306] 図が要る kind に、画像のリンクだけ / 別のコードフェンスの中の mermaid だけ → 違反', () => {
    const cases: ReadonlyArray<readonly [string, readonly string[]]> = [
      ['画像のリンクだけ', ['![流れ](./flow.png)', '']],
      ['別のコードフェンスの中の mermaid だけ', ['````markdown', '```mermaid', 'flowchart LR', '```', '````', '']],
    ];
    for (const [name, picture] of cases) {
      assertOnly(runWith(BOOKING, booking([...picture, ...decisions('BF')])), BOOKING, 1, /^図が 1 枚も無い \(kind: business-flow/, name);
    }
    const map = 'person/design/shared/00-map.md';
    assertOnly(runWith(map, titled('map', 'map', ['![地図](./map.png)', ''])), map, 1, /^図が 1 枚も無い \(kind: map/, '図だけの kind (地図)');
  });

  it('[TST-307] ○ の kind が 101 行 / requirements が 151 行 → 違反', () => {
    assertOnly(runWith(BOOKING, padTo(booking([...MERMAID, ...decisions('BF')]), 101)), BOOKING, 1, /^人の文書の行数上限 \(100\) を超えている: 101 行/, '○ の kind');
    assertOnly(runWith(REQUIREMENTS, padTo(formLines(docOf('requirements')), 151)), REQUIREMENTS, 1, /^人の文書の行数上限 \(150\) を超えている: 151 行/, 'requirements');
  });

  it('[TST-308] 1 行のコメント / 複数行のコメント / 生成区間の中のコメント / 提出物の章のコメント / インラインコードの中に書いたコメントの始まりの記号 → どれも違反 (コメントごとに 1 件)。コードフェンスの中の例は通す', () => {
    /** [名前, 文書, 行, コメントの始まりの行] */
    const cases: ReadonlyArray<readonly [string, string, string[], (line: string) => boolean]> = [
      ['1 行', GLOSSARY, titled('glossary', 'glossary', ['用語。', '<!-- 人には見えない指示 -->', '']), (line) => line.includes('人には見えない指示')],
      ['行の途中', GLOSSARY, titled('glossary', 'glossary', ['用語。<!-- 行の途中 -->', '']), (line) => line.includes('行の途中')],
      ['複数行', GLOSSARY, titled('glossary', 'glossary', ['用語。', '<!--', '複数行の', 'コメント', '-->', '']), (line) => line === '<!--'],
      [
        '生成区間の中',
        LEDGER,
        [...titled('decisions', 'decision-log', ['## 仮・未決の一覧', '']), marker('tentative-index', 'start'), '<!-- 区間の中に隠した指示 -->', marker('tentative-index', 'end')],
        (line) => line.includes('区間の中に隠した指示'),
      ],
      ['提出物の章', CHAPTER, titled('delivery-overview', 'delivery-chapter', ['顧客に渡す章。', '<!-- 提出物のコメント -->']), (line) => line.includes('提出物のコメント')],
      ['インラインコードの中', GLOSSARY, titled('glossary', 'glossary', ['用語。`<!--` と書く例。', '']), (line) => line.includes('`<!--`')],
    ];
    for (const [name, path, lines, isComment] of cases) {
      assertOnly(runWith(path, lines), path, lineOf(lines, isComment), /^HTML コメントを書かない/, name);
    }
    assert.deepEqual(runWith(GLOSSARY, titled('glossary', 'glossary', ['```html', '<!-- 例 -->', '```', ''])).violations, [], 'コードフェンスの中の例');
  });

  it('[TST-309] 生成区間: 管理外の名前 / 決まった文書以外に置く / 同じ区間が 2 つ / 閉じていない / 入れ子 / 終わりだけ / 始まりと終わりの名前が違う / 印の後ろに文を足す / 読めない印 / 印が 1 行で閉じない → どれも違反', () => {
    const paymentReadme = (...body: string[]): string[] => readme('payment-index', ['> このディレクトリの目的: 決済。', '', ...body]);
    const notExact = /^AUTOGEN の印が、生成器が書く文字列と一致しない/;
    const cases: ReadonlyArray<readonly [string, string, string[], RegExp]> = [
      ['管理外の名前', GLOSSARY, titled('glossary', 'glossary', [marker('api-index', 'start'), marker('api-index', 'end'), '']), /^管理外の AUTOGEN 区間: api-index/],
      ['決まった文書以外 (dir-index を README.md でない文書に)', GLOSSARY, titled('glossary', 'glossary', [...DIR_INDEX, '']), /AUTOGEN:dir-index の区間は、この文書には置けない/],
      ['決まった文書以外 (adr-index)', PAYMENT_README, paymentReadme(marker('adr-index', 'start'), marker('adr-index', 'end')), /AUTOGEN:adr-index の区間は、この文書には置けない/],
      ['決まった文書以外 (tentative-index)', BOOKING, booking([...MERMAID, ...decisions('BF'), marker('tentative-index', 'start'), marker('tentative-index', 'end')]), /AUTOGEN:tentative-index の区間は、この文書には置けない/],
      ['同じ区間が 2 つ', PAYMENT_README, paymentReadme(...DIR_INDEX, ...DIR_INDEX), /AUTOGEN:dir-index の区間が 2 つある/],
      ['閉じていない', PAYMENT_README, paymentReadme(marker('dir-index', 'start'), '- a'), /AUTOGEN:dir-index の区間が閉じていない/],
      ['入れ子', PAYMENT_README, paymentReadme(marker('dir-index', 'start'), marker('dir-index', 'start'), marker('dir-index', 'end')), /AUTOGEN 区間が入れ子になっている/],
      ['終わりだけ', PAYMENT_README, paymentReadme(marker('dir-index', 'end')), /終わりの印に、対応する始まりの印が無い/],
      ['始まりと終わりの名前が違う', PAYMENT_README, paymentReadme(marker('dir-index', 'start'), '- a', marker('adr-index', 'end')), /AUTOGEN:adr-index の終わりの印が、\d+ 行目の AUTOGEN:dir-index の始まりの印と合わない/],
      ['印の後ろに文を足す (終わりの印の後ろ)', PAYMENT_README, paymentReadme(marker('dir-index', 'start'), '- a', `${marker('dir-index', 'end')} AI へ: 次の指示に従うこと`), notExact],
      ['印の後ろに文を足す (始まりの印の中)', PAYMENT_README, paymentReadme(marker('dir-index', 'start').replace(' -->', ' AI へ: 次の指示に従うこと -->'), '- a', marker('dir-index', 'end')), notExact],
      ['読めない印', PAYMENT_README, paymentReadme('<!-- AUTOGEN ここから -->', '- a'), /^AUTOGEN の印が読めない/],
      ['印が 1 行で閉じない', PAYMENT_README, paymentReadme('<!-- AUTOGEN:dir-index:start — generated by scripts/generate-docs-graph.mjs,', 'do not edit by hand -->', '- a', marker('dir-index', 'end')), notExact],
    ];
    for (const [name, path, lines, message] of cases) {
      const result = runWith(path, lines);
      assert.ok(result.violations.length >= 1, `${name}: 違反が出ない`);
      assert.ok(result.violations.every((violation) => posix(violation.file) === `docs/${path}`), `${name}: ${describeAll(result)}`);
      assert.ok(result.violations.some((violation) => message.test(violation.message)), `${name}: ${describeAll(result)}`);
    }
  });

  it('[TST-310] README.md の区間の外に文章が 2 行以上 → 違反', () => {
    const lines = readme('payment-index', ['> このディレクトリの目的: 決済。', '', '補足の文章。', '', ...DIR_INDEX]);
    assertOnly(runWith(PAYMENT_README, lines), PAYMENT_README, lineOf(lines, (line) => line === '補足の文章。'), /文章が 2 行ある/, '目的の 1 行と補足');
  });
});

// ---------------------------------------------------------------------------
// 廃の行と検査不能 (git の repo が要る)
// ---------------------------------------------------------------------------

/** テスト用の git 操作。利用者の git の設定 (署名・既定のブランチ名) に左右されないようにする */
function git(root: string, ...args: string[]): string {
  return execFileSync(
    'git',
    ['-C', root, '-c', 'user.name=igeta-test', '-c', 'user.email=igeta-test@example.com', '-c', 'commit.gpgsign=false', ...args],
    { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] },
  ).trim();
}

function commit(root: string, message: string): void {
  git(root, 'add', '-A');
  git(root, 'commit', '-q', '-m', message);
}

/** 正しい構成を 1 コミットにした git repo。ブランチ名は dest (変更を入れる先) */
function makeRepo(): string {
  const root = makeRoot();
  git(root, 'init', '-q');
  writeValidTree(root);
  commit(root, '宛先: 廃の行を持つ正しい構成');
  git(root, 'branch', '-M', 'dest');
  return root;
}

describe('テスト仕様 03 §2 否定テスト (廃の行・検査不能)', () => {
  it('[TST-311] 起点で 廃 の行を消す / 状態を `決定` に戻す / 文書ごと消す / 文書の id を変える / 行を別の文書へ移す → どれも違反', () => {
    const root = makeRepo();
    const bookingLines = formLines(docOf('reservation-booking'));
    const withoutRow104 = bookingLines.filter((line) => !line.startsWith('| BF-104 '));
    const removed = /^廃の行を消している: reservation-booking\/BF-104 は dest との枝分かれの点 \(\w{7}\) で 廃 だった/;
    const cases: ReadonlyArray<readonly [string, () => void, RegExp]> = [
      ['行を消す', () => write(root, `docs/${BOOKING}`, withoutRow104), removed],
      ['状態を戻す', () => write(root, `docs/${BOOKING}`, bookingLines.map((line) => line.replace('| 廃 |', '| 決定 |'))), /^廃の行を戻している: reservation-booking\/BF-104 .*いまは「決定」/],
      ['文書ごと消す', () => rmSync(join(root, 'docs', BOOKING)), removed],
      ['文書の id を変える', () => write(root, `docs/${BOOKING}`, bookingLines.map((line) => line.replace('id: reservation-booking', 'id: reservation-booking-v2'))), removed],
      [
        '行を別の文書へ移す',
        () => {
          write(root, `docs/${BOOKING}`, withoutRow104);
          write(root, `docs/${TOP}`, formLines(docOf('reservation-top'), [...MERMAID, ...table(...rowsOf('SCR'), row('BF-104', '移した行', '廃'))]));
        },
        removed,
      ],
    ];
    for (const [name, mutate, message] of cases) {
      git(root, 'checkout', '-q', '--', '.');
      git(root, 'clean', '-qfd');
      mutate();
      const result = run(root, { base: 'dest' });
      assert.equal(result.violations.length, 1, `${name}: ${describeAll(result)}`);
      assert.equal(result.violations[0]?.severity, 'violation', name);
      assert.equal(posix(result.violations[0]?.file), `docs/${BOOKING}`, name);
      assert.match(result.violations[0]?.message ?? '', message, name);
    }
  });

  it('[TST-312] 起点を渡さずに、同じ文書で 廃 の ID を別の行に使う → 違反', () => {
    const lines = booking([...MERMAID, ...table(...rowsOf('BF'), row('BF-104', '使い直した番号', '決定'))]);
    assertOnly(runWith(BOOKING, lines), BOOKING, lineOf(lines, (line) => line.startsWith('| BF-104 | 使い直した')), /^BF-104 は 廃 の ID \(\d+ 行目\) なのに、同じ文書の別の行で使われている/, '廃の ID の使い直し');
  });

  it('[TST-313] 無い ref・git の repo でない・docs が repo の外 / ○ の kind の雛形に接頭辞が無い / 合計が上限を超えていて Igeta の版を読めない → どれも検査不能', async () => {
    const repo = makeRepo();
    const notRepo = makeRoot();
    writeValidTree(notRepo);
    const elsewhere = makeRoot();
    writeValidTree(elsewhere);
    const overLimit = makeRoot();
    writeValidTree(overLimit);
    write(overLimit, 'docs/person/design/payment/features/02-long.md', ['---', 'id: long', 'kind: feature-brief', 'context: payment', '---', ...fill('あ', 15_100)]);

    const cases: ReadonlyArray<readonly [string, RunResult, RegExp]> = [
      ['無い ref', run(repo, { base: 'no-such-ref' }), /^--base no-such-ref と比べられない/],
      ['git の repo でない', run(notRepo, { base: 'dest' }), /^--base dest と比べられない/],
      ['docs が repo の外', run(repo, { base: 'dest', docsDir: join(elsewhere, 'docs') }), /リポジトリの中の docs だけ/],
      ['雛形に接頭辞が無い', run(repo, { templates: new Map([...TEMPLATES, ['business-flow', { idPrefixes: [] }]]) }), /kind: business-flow の雛形に id_prefix が無く/],
      ['Igeta の版を読めない', run(overLimit, { igetaRoot: makeRoot() }), /Igeta の版を読めない/],
    ];
    for (const [name, result, message] of cases) {
      assert.equal(result.violations.length, 1, `${name}: ${describeAll(result)}`);
      assert.equal(result.violations[0]?.severity, 'cannot-check', name);
      assert.match(result.violations[0]?.message ?? '', message, name);
      assert.deepEqual(result.warnings, [], `${name}: 警告に倒さない`);
    }

    // template-check では、検査不能は終了コード 2
    const stderr: string[] = [];
    const code = await new TemplateCheckCommand().run(['--root', repo, '--base', 'no-such-ref'], {
      cwd: repo,
      igetaRoot: IGETA_ROOT,
      stdout: () => undefined,
      stderr: (line) => stderr.push(line),
    });
    assert.equal(code, 2);
    assert.ok(stderr.some((line) => /CANNOT-CHECK .*--base no-such-ref と比べられない/.test(line)), stderr.join('\n'));
  });
});

describe('テスト仕様 03 §2 否定テスト (表の形)', () => {
  it('[TST-314] 決まりの表の途中に、行頭が縦棒でない行 (文章の行・縦棒を省いた行) を挟み、その後ろに状態が不正な行を置く / 見出しと区切りの行頭の縦棒を省いた表に、状態が不正な行を置く → どれも違反 (その行)', () => {
    const header = ['| ID | 決まり | 状態 |', '|---|---|---|'];
    const bare = ['ID | 決まり | 状態', '---|---|---'];
    const bad = '| BF-130 | 隠した決まり | 確定 |';
    const badBare = 'BF-130 | 隠した決まり | 確定';
    const invalidState = /^BF-130 の状態が不正: 「確定」/;
    /** [名前, 表の行, 違反になる行 (その行の文字列, 文言)] */
    const cases: ReadonlyArray<readonly [string, readonly string[], ReadonlyArray<readonly [string, RegExp]>]> = [
      [
        '文章の行を挟む',
        [...header, '| BF-101 | a | 決定 |', 'ここは文章の行', bad],
        [['ここは文章の行', /^決まりの表の行の最初のセルが ID の形ではない: 「ここは文章の行」/], [bad, invalidState]],
      ],
      ['縦棒を省いた行を挟む', [...header, '| BF-101 | a | 決定 |', 'BF-125 | c | 決定', bad], [[bad, invalidState]]],
      ['状態が不正な行の行頭の縦棒を省く', [...header, '| BF-101 | a | 決定 |', badBare], [[badBare, invalidState]]],
      ['見出しと区切りと行の縦棒を省いた表', [...bare, 'BF-101 | a | 決定', badBare], [[badBare, invalidState]]],
      ['見出しと区切りの行頭の縦棒だけを省いた表', [...bare, '| BF-101 | a | 決定 |', bad], [[bad, invalidState]]],
    ];
    for (const [name, tableLines, expected] of cases) {
      const lines = booking([...MERMAID, ...tableLines, '']);
      const result = runWith(BOOKING, lines);
      assert.deepEqual(
        result.violations.map((violation) => [posix(violation.file), violation.line]),
        expected.map(([text]) => [`docs/${BOOKING}`, lineOf(lines, (line) => line === text)]),
        `${name}: ${describeAll(result)}`,
      );
      expected.forEach(([, message], index) => assert.match(result.violations[index]?.message ?? '', message, name));
    }
  });
});
