// node --test dist/checks/RoleBoundaryCheck.test.js
// 確定させる人 (person / ai / client) の境界の検査。一時ディレクトリに 3 フォルダの構成を作り、
// 正しい構成が通ること、違反がそれぞれ検出されること、旧い構成では警告だけが出ることを確かめる。
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { after, beforeEach, describe, it } from 'node:test';
import assert from 'node:assert/strict';

import { IGETA_ROOT } from '../core/Paths.js';
import type { Violation } from '../core/Report.js';
import {
  LEGACY_LAYOUT_MESSAGE,
  LEGACY_LAYOUT_VIOLATION_FROM_MAJOR,
  RoleBoundaryCheck,
} from './RoleBoundaryCheck.js';

const workspaces: string[] = [];

after(() => {
  for (const dir of workspaces) rmSync(dir, { recursive: true, force: true });
});

function makeRoot(): string {
  const root = mkdtempSync(join(tmpdir(), 'igeta-roleboundary-'));
  workspaces.push(root);
  return root;
}

function write(root: string, relPath: string, content: string): void {
  const target = join(root, relPath);
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, content);
}

/** frontmatter に kind (と context) だけを書いた文書。body は本文の行 */
function doc(kind: string | null, context: string | null = null, body: readonly string[] = []): string {
  return [
    ...(kind === null && context === null
      ? []
      : ['---', ...(kind === null ? [] : [`kind: ${kind}`]), ...(context === null ? [] : [`context: ${context}`]), '---', '']),
    '# 題名',
    '',
    ...body,
    '',
  ].join('\n');
}

/** 正しい 3 フォルダの構成。まとまりは reservation・payment・shared の 3 つ、kind は 3 区分にまたがる */
const VALID: ReadonlyArray<readonly [path: string, kind: string, context?: string]> = [
  ['person/requirements/01-requirements.md', 'requirements'],
  ['person/requirements/02-billing.md', 'requirements'],
  ['person/design/shared/00-map.md', 'map'],
  ['person/design/shared/02-function-list.md', 'function-list'],
  ['person/design/shared/03-nonfunctional.md', 'nonfunctional', 'shared'],
  ['person/design/shared/05-glossary.md', 'glossary'],
  ['person/design/reservation/00-map.md', 'context-map', 'reservation'],
  ['person/design/reservation/flows/01-booking.md', 'business-flow', 'reservation'],
  ['person/design/reservation/screens/01-top.md', 'screen-spec', 'reservation'],
  ['person/design/payment/00-map.md', 'context-map', 'payment'],
  ['person/design/payment/03-operations.md', 'operations', 'payment'],
  ['person/design/payment/features/01-refund.md', 'feature-brief', 'payment'],
  ['person/decisions/2026/0001-use-postgres.md', 'adr'],
  ['person/decisions/01-decisions.md', 'decision-log'],
  ['ai/specs/shared/01-crosscutting.md', 'crosscutting'],
  ['ai/specs/shared/02-test-plan.md', 'test-plan'],
  ['ai/specs/reservation/contract.md', 'context-contract', 'reservation'],
  ['ai/specs/reservation/api/01-reserve.md', 'api-spec', 'reservation'],
  ['ai/specs/reservation/state-machines/01-reservation.md', 'state-machine', 'reservation'],
  ['ai/specs/payment/tables/01-payments.md', 'table-spec', 'payment'],
  ['ai/specs/payment/jobs/01-settlement.md', 'job', 'payment'],
  ['ai/specs/tasks/01-first.md', 'tasks'],
  ['ai/handbook/how-to/02-implementation-order.md', 'implementation-order'],
  ['ai/handbook/how-to/01-setup.md', 'guide'],
  ['ai/handbook/explanation/01-why.md', 'explanation'],
  ['ai/handbook/runbooks/01-incident.md', 'runbook'],
  ['client/delivery/spec-v1/01-overview.md', 'delivery-chapter'],
  ['client/proposals/2026/01-proposal.md', 'proposal'],
];

/** 生成索引 (docs/ 直下の 2 本と各フォルダの README.md)。置き場所の表の外に置いてよい */
const INDEXES: readonly string[] = [
  'README.md',
  'dependencies.md',
  'person/README.md',
  'person/design/reservation/flows/README.md',
  'ai/specs/README.md',
  'client/delivery/spec-v1/README.md',
];

function writeValidTree(root: string): void {
  for (const [path, kind, context] of VALID) write(root, `docs/${path}`, doc(kind, context ?? null));
  for (const path of INDEXES) write(root, `docs/${path}`, '<!-- AUTOGENERATED BY scripts/generate-docs-graph.mjs -->\n# 索引\n');
}

interface RunResult {
  readonly violations: readonly Violation[];
  readonly warnings: readonly string[];
  /** 違反の file (リポジトリルートからの相対パス) を / 区切りにして並べたもの */
  readonly files: readonly string[];
}

function run(root: string, igetaRoot: string = IGETA_ROOT): RunResult {
  const check = new RoleBoundaryCheck();
  const violations = check.run({ targetRoot: root, igetaRoot });
  return {
    violations,
    warnings: check.warnings,
    files: violations.map((violation) => (violation.file ?? '').split('\\').join('/')),
  };
}

/** 版だけを持つ Igeta の package.json の置き場所 */
function igetaRootWithVersion(version: string): string {
  const igetaRoot = makeRoot();
  write(igetaRoot, 'package.json', JSON.stringify({ name: 'igeta', version }));
  return igetaRoot;
}

const messageOf = (result: RunResult, file: string): string =>
  result.violations.find((violation) => (violation.file ?? '').split('\\').join('/') === file)?.message ?? '';

describe('RoleBoundaryCheck: 新しい構成 (v4)', () => {
  let root: string;
  beforeEach(() => {
    root = makeRoot();
    writeValidTree(root);
  });

  it('正しい構成 (3 区分・3 つのまとまり・生成索引つき) は違反も警告も出ない', () => {
    const result = run(root);
    assert.deepEqual(result.violations, []);
    assert.deepEqual(result.warnings, []);
  });

  it('person・ai・client のうち 1 つしか無くても新しい構成として検査する', () => {
    const only = makeRoot();
    write(only, 'docs/ai/handbook/how-to/01-setup.md', doc('guide'));
    write(only, 'docs/stray.md', doc('guide'));
    const result = run(only);
    assert.deepEqual(result.files, ['docs/stray.md']);
  });

  describe('置き場所 (kind から導く場所と実際のパスの食い違い)', () => {
    it('違う kind の場所に置いた文書だけが落ち、同じ場所の正しい文書は落ちない (複数のまとまり)', () => {
      write(root, 'docs/person/design/reservation/flows/02-wrong.md', doc('api-spec', 'reservation'));
      write(root, 'docs/ai/specs/payment/api/02-wrong.md', doc('table-spec', 'payment'));
      const result = run(root);
      assert.deepEqual(result.files, [
        'docs/ai/specs/payment/api/02-wrong.md',
        'docs/person/design/reservation/flows/02-wrong.md',
      ]);
      assert.match(
        messageOf(result, 'docs/person/design/reservation/flows/02-wrong.md'),
        /kind: api-spec の置き場所ではない \(置けるのは docs\/ai\/specs\/<c>\/api\/\*\.md\)/,
      );
    });

    it('person の kind を ai に、ai の kind を person に置くと落ちる (確定させる人の取り違え)', () => {
      write(root, 'docs/ai/specs/shared/09-requirements.md', doc('requirements'));
      write(root, 'docs/person/design/shared/09-crosscutting.md', doc('crosscutting'));
      write(root, 'docs/client/proposals/2026/09-guide.md', doc('guide'));
      const result = run(root);
      assert.deepEqual(result.files, [
        'docs/ai/specs/shared/09-requirements.md',
        'docs/client/proposals/2026/09-guide.md',
        'docs/person/design/shared/09-crosscutting.md',
      ]);
    });

    it('ai/specs/tasks/ の tasks の文書は contract.md という名前でも通り、context-contract は tasks と shared のフォルダには置けない', () => {
      // tasks と shared は、まとまりではなく固定のフォルダ。tasks の文書の名前が contract.md でも、約束 (context-contract) ではない
      write(root, 'docs/ai/specs/tasks/contract.md', doc('tasks'));
      write(root, 'docs/ai/specs/tasks/shared/contract.md', doc('tasks'));
      assert.deepEqual(run(root).violations, []);

      // 約束を tasks や shared に置いたら落ちる。まとまり (reservation) の約束は、基準の構成にあって落ちない
      write(root, 'docs/ai/specs/tasks/contract.md', doc('context-contract', 'tasks'));
      write(root, 'docs/ai/specs/shared/contract.md', doc('context-contract'));
      const result = run(root);
      assert.deepEqual(result.files, ['docs/ai/specs/shared/contract.md', 'docs/ai/specs/tasks/contract.md']);
      assert.match(
        messageOf(result, 'docs/ai/specs/tasks/contract.md'),
        /kind: context-contract の置き場所ではない \(置けるのは docs\/ai\/specs\/<c>\/contract\.md\)/,
      );
    });

    it('ai/specs/ の shared の固定の文書は、まとまりの約束にはならず、まとまりの下位フォルダの文書は shared でも通る', () => {
      write(root, 'docs/ai/specs/shared/03-messages.md', doc('messages'));
      write(root, 'docs/ai/specs/shared/api/01-common.md', doc('api-spec'));
      assert.deepEqual(run(root).violations, []);
      // shared の約束という置き方はできない。shared の下のフォルダの api-spec が、約束に取り違えられることも無い
      write(root, 'docs/ai/specs/shared/contract.md', doc('messages'));
      assert.deepEqual(run(root).violations, []);
    });

    it('置き場所の型の外 (まとまりの下位フォルダの名前違い・深すぎる・年でないフォルダ) は落ちる', () => {
      write(root, 'docs/person/design/reservation/workflows/01-x.md', doc('business-flow', 'reservation'));
      write(root, 'docs/person/design/reservation/flows/sub/01-x.md', doc('business-flow', 'reservation'));
      write(root, 'docs/person/decisions/latest/0002-x.md', doc('adr'));
      write(root, 'docs/ai/specs/reservation/01-api.md', doc('api-spec', 'reservation'));
      const result = run(root);
      assert.deepEqual(result.files, [
        'docs/ai/specs/reservation/01-api.md',
        'docs/person/decisions/latest/0002-x.md',
        'docs/person/design/reservation/flows/sub/01-x.md',
        'docs/person/design/reservation/workflows/01-x.md',
      ]);
    });

    it('利用 repo には置かない kind (document-taxonomy など) は、どこに置いても落ちる', () => {
      write(root, 'docs/ai/handbook/how-to/03-taxonomy.md', doc('document-taxonomy'));
      write(root, 'docs/ai/handbook/explanation/02-review.md', doc('human-review'));
      const result = run(root);
      assert.deepEqual(result.files, [
        'docs/ai/handbook/explanation/02-review.md',
        'docs/ai/handbook/how-to/03-taxonomy.md',
      ]);
      assert.match(messageOf(result, 'docs/ai/handbook/how-to/03-taxonomy.md'), /利用 repo には置かない/);
    });

    it('kind が無い文書・表に無い kind は、置き場所を判定できないので落ちる', () => {
      write(root, 'docs/person/design/shared/10-no-kind.md', doc(null, null));
      write(root, 'docs/person/design/shared/11-empty-kind.md', '---\nkind:\nid: x\n---\n# x\n');
      write(root, 'docs/ai/handbook/how-to/04-tutorial.md', doc('tutorial'));
      write(root, 'docs/ai/handbook/how-to/05-index.md', doc('index'));
      const result = run(root);
      assert.deepEqual(result.files, [
        'docs/ai/handbook/how-to/04-tutorial.md',
        'docs/ai/handbook/how-to/05-index.md',
        'docs/person/design/shared/10-no-kind.md',
        'docs/person/design/shared/11-empty-kind.md',
      ]);
      assert.match(messageOf(result, 'docs/person/design/shared/10-no-kind.md'), /kind が無く、置き場所を判定できない/);
      assert.match(messageOf(result, 'docs/ai/handbook/how-to/04-tutorial.md'), /置き場所の表に無い kind: tutorial/);
    });

    it('生成索引 (README.md) は kind が無くても落ちない', () => {
      write(root, 'docs/person/design/payment/features/README.md', '# 索引\n');
      write(root, 'docs/ai/README.md', doc(null, null));
      assert.deepEqual(run(root).violations, []);
    });
  });

  describe('フォルダ名のまとまりと frontmatter の context', () => {
    it('context が違う・無記入 (= shared) のとき、まとまりのフォルダの文書は落ちる', () => {
      write(root, 'docs/person/design/reservation/flows/02-other.md', doc('business-flow', 'payment'));
      write(root, 'docs/person/design/payment/features/02-nothing.md', doc('feature-brief'));
      write(root, 'docs/ai/specs/payment/api/02-other.md', doc('api-spec', 'reservation'));
      const result = run(root);
      assert.deepEqual(result.files, [
        'docs/ai/specs/payment/api/02-other.md',
        'docs/person/design/payment/features/02-nothing.md',
        'docs/person/design/reservation/flows/02-other.md',
      ]);
      assert.match(
        messageOf(result, 'docs/person/design/reservation/flows/02-other.md'),
        /フォルダ名のまとまり \(reservation\) と frontmatter の context \(payment\) が食い違う/,
      );
      assert.match(
        messageOf(result, 'docs/person/design/payment/features/02-nothing.md'),
        /フォルダ名のまとまり \(payment\) と frontmatter の context \(shared\) が食い違う/,
      );
    });

    it('shared のフォルダの文書は context 無記入か shared だけ。別のまとまりを名乗ると落ちる', () => {
      write(root, 'docs/person/design/shared/09-function-list-copy.md', doc('operations', 'shared'));
      write(root, 'docs/ai/specs/shared/09-claims-reservation.md', doc('messages', 'reservation'));
      const result = run(root);
      assert.deepEqual(result.files, ['docs/ai/specs/shared/09-claims-reservation.md']);
      assert.match(messageOf(result, 'docs/ai/specs/shared/09-claims-reservation.md'), /まとまり \(shared\).*context \(reservation\)/);
    });

    it('まとまりのフォルダを持たない場所 (要件・決定・提出物・実装タスク) の context は問わない', () => {
      write(root, 'docs/person/requirements/03-payment.md', doc('requirements', 'payment'));
      write(root, 'docs/person/decisions/2026/0002-x.md', doc('adr', 'reservation'));
      write(root, 'docs/ai/specs/tasks/02-second.md', doc('tasks', 'payment'));
      write(root, 'docs/client/delivery/spec-v1/02-detail.md', doc('delivery-chapter', 'payment'));
      assert.deepEqual(run(root).violations, []);
    });

    it('まとまりの下位フォルダへ分けた手引き・実装タスクは、フォルダ名と context が一致して通る', () => {
      write(root, 'docs/ai/specs/tasks/payment/01-x.md', doc('tasks', 'payment'));
      write(root, 'docs/ai/specs/tasks/shared/01-x.md', doc('tasks'));
      write(root, 'docs/ai/handbook/runbooks/reservation/01-x.md', doc('runbook', 'reservation'));
      write(root, 'docs/ai/specs/tasks/payment/02-wrong.md', doc('tasks', 'reservation'));
      assert.deepEqual(run(root).files, ['docs/ai/specs/tasks/payment/02-wrong.md']);
    });
  });

  describe('docs/ 直下と docs/common/', () => {
    it('docs/ 直下の文書 (README.md・dependencies.md 以外) と、3 フォルダの外のフォルダの文書は落ちる', () => {
      write(root, 'docs/00-map.md', doc('map'));
      write(root, 'docs/adr/0001-x.md', doc('adr'));
      write(root, 'docs/design/basic/01-function-list.md', doc('function-list'));
      write(root, 'docs/notes.md', '# メモ\n');
      const result = run(root);
      assert.deepEqual(result.files, [
        'docs/00-map.md',
        'docs/adr/0001-x.md',
        'docs/design/basic/01-function-list.md',
        'docs/notes.md',
      ]);
      assert.match(messageOf(result, 'docs/00-map.md'), /person・ai・client のどれにも属さない/);
    });

    it('docs/common/ が残っていると 1 件の違反になり、中の文書を 1 本ずつは数えない', () => {
      write(root, 'docs/common/01-a.md', doc('glossary'));
      write(root, 'docs/common/sub/02-b.md', doc('explanation'));
      const result = run(root);
      assert.deepEqual(result.files, ['docs/common']);
      assert.match(result.violations[0]?.message ?? '', /docs\/common\/ が残っている/);
    });

    it('docs/common/ だけが残っている (person・ai・client が無い) repo は、docs/common/ の違反 1 件と、旧い構成としての警告だけ', () => {
      const v3 = makeRoot();
      write(v3, 'docs/common/01-a.md', doc('glossary'));
      write(v3, 'docs/product/01-requirements.md', doc('requirements'));
      write(v3, 'docs/notes.md', '# メモ\n');
      const result = run(v3, igetaRootWithVersion('0.4.0'));
      assert.deepEqual(result.files, ['docs/common']);
      assert.deepEqual(result.warnings, [LEGACY_LAYOUT_MESSAGE]);
    });

    it('docs/common/ だけが残っている repo は、旧い構成を違反にする版では、違反が 2 件 (docs/common/ と旧い構成)', () => {
      const v3 = makeRoot();
      write(v3, 'docs/common/01-a.md', doc('glossary'));
      const result = run(v3, igetaRootWithVersion(`${LEGACY_LAYOUT_VIOLATION_FROM_MAJOR}.0.0`));
      assert.equal(result.violations.length, 2);
      assert.deepEqual(result.files, ['docs/common', '']);
      assert.ok(result.violations[1]?.message.startsWith(LEGACY_LAYOUT_MESSAGE));
      assert.deepEqual(result.warnings, []);
    });

    it('点で始まるフォルダと node_modules の Markdown は文書として数えない', () => {
      write(root, 'docs/.cache/01-x.md', '# cache\n');
      write(root, 'docs/node_modules/pkg/README.md', '# pkg\n');
      write(root, 'docs/node_modules/pkg/guide.md', '# pkg guide\n');
      assert.deepEqual(run(root).violations, []);
    });
  });

  describe('ai/ の文書の未決の節 (見出しの語)', () => {
    const headings = [
      '## 未決事項',
      '### 未確定の論点',
      '## 保留',
      '## 要確認',
      '## 宿題',
      '## TBD',
      '## TODO リスト',
      '## todos',
      '#### 3. 未決',
    ];

    it('見出しに 未決・未確定・保留・要確認・宿題・TBD・TODO を含む節は、見出しごとに 1 件落ちる', () => {
      write(root, 'docs/ai/specs/shared/09-open.md', doc('crosscutting', null, headings.flatMap((heading) => [heading, '', '本文', ''])));
      const result = run(root);
      assert.equal(result.violations.length, headings.length);
      assert.ok(result.files.every((file) => file === 'docs/ai/specs/shared/09-open.md'));
      assert.match(result.violations[0]?.message ?? '', /ai\/ の文書に未決の節がある: 「未決事項」/);
      // 行番号は見出しの行。frontmatter 3 行 + 空行 + 題名 + 空行 の次 (7 行目) から、見出し・空行・本文・空行の 4 行ずつ
      assert.deepEqual(
        result.violations.map((violation) => violation.line),
        headings.map((_, index) => 7 + index * 4),
      );
    });

    it('見出しではない行・コードフェンス・HTML コメント・単語の一部は未決の節とみなさない', () => {
      write(
        root,
        'docs/ai/specs/shared/09-clean.md',
        doc('crosscutting', null, [
          '## 決めたこと',
          '',
          '未決の項目は person の決定台帳に集める。保留や宿題という語を本文に書くのは構わない。',
          '',
          '```markdown',
          '## 未決事項',
          '```',
          '',
          '<!-- ## TODO: あとで -->',
          '',
          '## Mastodon との連携',
          '## Todoist の設定',
          '## 決定事項',
        ]),
      );
      assert.deepEqual(run(root).violations, []);
    });

    it('person・client の文書の見出しは検査しない (人の決めが要るものは person に書く)', () => {
      write(root, 'docs/person/design/shared/09-open.md', doc('operations', null, ['## 未決事項', '', '## TBD']));
      write(root, 'docs/client/proposals/2026/09-open.md', doc('proposal', null, ['## 宿題']));
      assert.deepEqual(run(root).violations, []);
    });

    it('frontmatter の中のコメント行 (# 未決) は見出しではない', () => {
      write(root, 'docs/ai/specs/shared/09-fm.md', '---\nkind: crosscutting\n# 未決の項目なし\n---\n\n# 題名\n');
      assert.deepEqual(run(root).violations, []);
    });
  });

  it('違反は file と行の順に並ぶ', () => {
    write(root, 'docs/zzz.md', '# z\n');
    write(root, 'docs/ai/specs/shared/09-open.md', doc('crosscutting', null, ['## 宿題', '', '## 保留']));
    write(root, 'docs/aaa.md', '# a\n');
    const result = run(root);
    assert.deepEqual(result.files, [
      'docs/aaa.md',
      'docs/ai/specs/shared/09-open.md',
      'docs/ai/specs/shared/09-open.md',
      'docs/zzz.md',
    ]);
    assert.deepEqual(
      result.violations.filter((violation) => violation.file?.endsWith('09-open.md') === true).map((violation) => violation.line),
      [7, 9],
    );
  });

  it('docs/ が無ければ検査不能', () => {
    const empty = makeRoot();
    const result = run(empty);
    assert.equal(result.violations.length, 1);
    assert.equal(result.violations[0]?.severity, 'cannot-check');
  });
});

describe('RoleBoundaryCheck: 旧い構成 (legacy)', () => {
  /** 旧い構成の repo。新しい構成なら全部が違反になる文書 (kind 無し・置き場所違い) も置いておく */
  function writeLegacyTree(root: string): void {
    write(root, 'docs/product/01-requirements.md', doc('requirements'));
    write(root, 'docs/design/basic/01-function-list.md', doc('function-list'));
    write(root, 'docs/design/basic/screens/__x__.md', doc('business-flow'));
    write(root, 'docs/adr/0001-x.md', doc('adr'));
    write(root, 'docs/notes.md', '# メモ\n');
    write(root, 'docs/design/detail/01-open.md', doc('crosscutting', null, ['## 未決事項']));
  }

  it('違反は 1 件も出さず、移行を促す警告を 1 件だけ出す', () => {
    const root = makeRoot();
    writeLegacyTree(root);
    const result = run(root, igetaRootWithVersion(`${LEGACY_LAYOUT_VIOLATION_FROM_MAJOR - 1}.9.9`));
    assert.deepEqual(result.violations, []);
    assert.deepEqual(result.warnings, [LEGACY_LAYOUT_MESSAGE]);
    assert.equal(LEGACY_LAYOUT_MESSAGE, '旧い構成です。`igeta docs-migrate` を実行してください');
  });

  it('検査のたびに警告を 1 件出す (同じ検査を 2 回走らせても 2 件にならない)', () => {
    const root = makeRoot();
    writeLegacyTree(root);
    const igetaRoot = igetaRootWithVersion('0.4.0');
    const check = new RoleBoundaryCheck();
    check.run({ targetRoot: root, igetaRoot });
    check.run({ targetRoot: root, igetaRoot });
    assert.deepEqual(check.warnings, [LEGACY_LAYOUT_MESSAGE]);
  });

  it('Igeta の版が LEGACY_LAYOUT_VIOLATION_FROM_MAJOR 以上なら、同じ指摘が違反になり、警告は出ない', () => {
    const root = makeRoot();
    writeLegacyTree(root);
    for (const version of [`${LEGACY_LAYOUT_VIOLATION_FROM_MAJOR}.0.0`, `${LEGACY_LAYOUT_VIOLATION_FROM_MAJOR + 1}.3.1`]) {
      const result = run(root, igetaRootWithVersion(version));
      assert.equal(result.violations.length, 1, version);
      assert.equal(result.violations[0]?.severity, 'violation');
      assert.ok(result.violations[0]?.message.startsWith(LEGACY_LAYOUT_MESSAGE), version);
      assert.deepEqual(result.warnings, [], version);
    }
  });

  it('Igeta の版を読めないときは、警告にも違反にも倒さず検査不能にする', () => {
    const root = makeRoot();
    writeLegacyTree(root);
    const noPackageJson = run(root, makeRoot());
    assert.equal(noPackageJson.violations.length, 1);
    assert.equal(noPackageJson.violations[0]?.severity, 'cannot-check');
    assert.deepEqual(noPackageJson.warnings, []);
    const notSemver = run(root, igetaRootWithVersion('next'));
    assert.equal(notSemver.violations[0]?.severity, 'cannot-check');
  });

  it('旧い構成の検査は、新しい構成の repo では警告を出さない', () => {
    const root = makeRoot();
    writeValidTree(root);
    assert.deepEqual(run(root).warnings, []);
  });
});
