// まとまり (context) 単位の文書グラフを作る共通ロジック。
// Spec: docs/explanation/07-context-boundaries.md §4〜§6
// context-boundary-check / context-size / context-files の 3 コマンドがこれを共有する。
//
// 参照の抜き出しは depends_on・本文の相対リンク・修飾 ID (<doc-id>/PREFIX-nnn) の 3 種類。
// 「## 関連」節も対象にする (約束の 1 枚を通らない依存を隠させない、他検査との違い)。
// AUTOGEN・HTML コメント・コードフェンスは core/LineClassifier.ts で除外する (既存検査と同じ判定)。

import { readFileSync, readdirSync, statSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { readContext } from './Context.js';
import type { FrontmatterData } from './Frontmatter.js';
import { parseFrontmatter, scalar, stringList } from './Frontmatter.js';
import { classifyLines } from './LineClassifier.js';

const SKIP_DIR = new Set(['node_modules', 'dist', 'coverage']);

export interface ContextDoc {
  /** targetRoot からの相対パス */
  readonly relPath: string;
  readonly file: string;
  readonly id: string | null;
  readonly kind: string | null;
  readonly context: string;
  readonly dependsOn: readonly string[];
  readonly lines: readonly string[];
  readonly bodyStart: number;
}

export interface ContextGraph {
  readonly docs: readonly ContextDoc[];
  readonly byId: ReadonlyMap<string, ContextDoc>;
}

const isDir = (path: string): boolean => {
  try {
    return statSync(path).isDirectory();
  } catch {
    return false;
  }
};

function listMarkdown(dir: string): string[] {
  const found: string[] = [];
  const walk = (current: string): void => {
    for (const entry of readdirSync(current, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
      const full = join(current, entry.name);
      if (entry.isDirectory()) {
        if (SKIP_DIR.has(entry.name) || entry.name.startsWith('.')) continue;
        walk(full);
        continue;
      }
      if (entry.name.endsWith('.md') && entry.name !== 'README.md') found.push(full);
    }
  };
  walk(dir);
  return found;
}

/** docsDir が無ければ null。 */
export function buildContextGraph(targetRoot: string, docsDir: string): ContextGraph | null {
  if (!isDir(docsDir)) return null;
  const docs: ContextDoc[] = [];
  const byId = new Map<string, ContextDoc>();
  for (const file of listMarkdown(docsDir)) {
    const lines = readFileSync(file, 'utf8').split(/\r?\n/);
    if (lines[0]?.includes('AUTOGENERATED')) continue; // 生成物は索引であって設計書ではない
    const meta = parseFrontmatter(lines);
    const data: FrontmatterData = meta?.data ?? new Map();
    const bodyStart = meta?.bodyStart ?? 0;
    const kind = scalar(data, 'kind') ?? null;
    const id = scalar(data, 'id') ?? null;
    const context = readContext(kind, data);
    const dependsOn = stringList(data, 'depends_on').filter((dep) => !dep.startsWith('external:'));
    const relPath = relative(targetRoot, file);
    const doc: ContextDoc = { relPath, file, id, kind, context, dependsOn, lines, bodyStart };
    docs.push(doc);
    if (id !== null && id !== '' && !byId.has(id)) byId.set(id, doc);
  }
  return { docs, byId };
}

export interface ContextReference {
  readonly target: ContextDoc;
  readonly line: number;
}

const BODY_LINK_RE = /\[[^\]]*\]\(\s*<?([^)<>\s]+)>?(?:\s+"[^"]*")?\s*\)/g;
const QUALIFIED_ID_RE = /\b([a-z][a-z0-9-]*)\/([A-Z]+-\d{3})\b/g;

function resolveLinkTarget(fromFile: string, targetRoot: string, target: string): string | null {
  const stripped = (target.split('#')[0] ?? target).trim();
  if (stripped === '' || /^[a-z][a-z0-9+.-]*:/i.test(stripped)) return null; // 外部リンク
  const abs = stripped.startsWith('/') ? join(targetRoot, stripped.slice(1)) : join(dirname(fromFile), stripped);
  return abs;
}

/** doc の depends_on・本文リンク・修飾 ID から参照先 doc を解決する。解決できない参照は無視する (別検査の責務)。 */
export function extractReferences(doc: ContextDoc, graph: ContextGraph, targetRoot: string): readonly ContextReference[] {
  const refs: ContextReference[] = [];
  const byRelPath = new Map<string, ContextDoc>(graph.docs.map((d) => [d.file, d]));

  for (const dependency of doc.dependsOn) {
    const target = graph.byId.get(dependency);
    if (target === undefined || target === doc) continue;
    let line = 1;
    for (let i = 0; i < doc.bodyStart; i += 1) {
      if ((doc.lines[i] ?? '').includes(dependency)) {
        line = i + 1;
        break;
      }
    }
    refs.push({ target, line });
  }

  const kinds = classifyLines(doc.lines);
  for (let i = doc.bodyStart; i < doc.lines.length; i += 1) {
    if (kinds[i] !== 'body') continue;
    const line = doc.lines[i] ?? '';

    for (const matched of line.matchAll(BODY_LINK_RE)) {
      const raw = matched[1];
      if (raw === undefined) continue;
      const abs = resolveLinkTarget(doc.file, targetRoot, raw);
      if (abs === null) continue;
      const target = byRelPath.get(abs);
      if (target !== undefined && target !== doc) refs.push({ target, line: i + 1 });
    }

    for (const matched of line.matchAll(QUALIFIED_ID_RE)) {
      const docId = matched[1];
      if (docId === undefined) continue;
      const target = graph.byId.get(docId);
      if (target !== undefined && target !== doc) refs.push({ target, line: i + 1 });
    }
  }
  return refs;
}
