// まとまり (context) 単位の文書グラフを作る共通ロジック。
// Spec: docs/explanation/07-context-boundaries.md §4〜§6
// context-boundary-check / context-size / context-files の 3 コマンドがこれを共有する。
//
// 参照の抜き出しは depends_on・本文の相対リンク・修飾 ID (<doc-id>/PREFIX-nnn) の 3 種類。
// 「## 関連」節も対象にする (約束の 1 枚を通らない依存を隠させない、他検査との違い)。
// AUTOGEN・HTML コメント・コードフェンスは core/LineClassifier.ts で除外する (既存検査と同じ判定)。
//
// 新しい構成 (docs/person・ai・client のどれかがある) では、まとまりを置き場所の型の階層から導き (B1)、決定の記録・AI の手引き・
// 顧客への提出物を検査から外し (B2)、context-files・context-size が読む範囲をフォルダで決める (B6)。
// Spec: docs/design/test/specs/04-doc-graph.md の B1〜B6。旧い構成の読み方は、いままでと変えない。

import { readFileSync, readdirSync, statSync } from 'node:fs';
import { dirname, join, relative, sep } from 'node:path';
import { readContext, SHARED_CONTEXT } from './Context.js';
import type { FrontmatterData } from './Frontmatter.js';
import { parseFrontmatter, scalar, stringList } from './Frontmatter.js';
import { classifyLines } from './LineClassifier.js';
import { detectLayout, matchPlacement } from './Role.js';

const SKIP_DIR = new Set(['node_modules', 'dist', 'coverage']);

export interface ContextDoc {
  /** targetRoot からの相対パス */
  readonly relPath: string;
  /** docsDir からの相対パス (区切りは `/`) */
  readonly docsRel: string;
  readonly file: string;
  readonly id: string | null;
  readonly kind: string | null;
  readonly context: string;
  readonly dependsOn: readonly string[];
  readonly lines: readonly string[];
  readonly bodyStart: number;
}

export interface ContextGraph {
  readonly docs: readonly ContextDoc[];
  readonly byId: ReadonlyMap<string, ContextDoc>;
  /** 新しい構成 (docs/person・ai・client のどれかがある) か。そうなら B1・B2 の読み方で作ってある */
  readonly v4: boolean;
}

/** 新しい構成で、境界の検査に掛けない場所 (B2): 決定の記録・AI の手引き (設計ではない)・顧客への提出物。参照元にも参照先にもしない */
const OUTSIDE_BOUNDARY_PREFIXES: readonly string[] = ['person/decisions/', 'ai/handbook/', 'client/'];

/**
 * 新しい構成のまとまり (B1): 置き場所の型にまとまりの階層がある文書は、フォルダ名から導く (`shared` のフォルダも
 * まとまり shared)。階層の無い場所 (person/requirements/・ai/specs/tasks/ の直下) は frontmatter の context (無記入は shared)。
 */
function contextOfV4(kind: string | null, docsRel: string, data: FrontmatterData): string {
  const fromFolder = kind === null ? null : matchPlacement(kind, docsRel).context;
  return fromFolder ?? readContext(kind, data);
}

const isDir = (path: string): boolean => {
  try {
    return statSync(path).isDirectory();
  } catch {
    return false;
  }
};

function listMarkdown(dir: string): string[] {
  const found: string[] = [];
  const walk = (current: string): void => {
    for (const entry of readdirSync(current, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
      const full = join(current, entry.name);
      if (entry.isDirectory()) {
        if (SKIP_DIR.has(entry.name) || entry.name.startsWith('.')) continue;
        walk(full);
        continue;
      }
      if (entry.name.endsWith('.md') && entry.name !== 'README.md') found.push(full);
    }
  };
  walk(dir);
  return found;
}

/** docsDir が無ければ null。 */
export function buildContextGraph(targetRoot: string, docsDir: string): ContextGraph | null {
  if (!isDir(docsDir)) return null;
  const v4 = detectLayout(docsDir) === 'v4';
  const docs: ContextDoc[] = [];
  const byId = new Map<string, ContextDoc>();
  for (const file of listMarkdown(docsDir)) {
    const docsRel = relative(docsDir, file).split(sep).join('/');
    if (v4 && OUTSIDE_BOUNDARY_PREFIXES.some((prefix) => docsRel.startsWith(prefix))) continue;
    const lines = readFileSync(file, 'utf8').split(/\r?\n/);
    if (lines[0]?.includes('AUTOGENERATED')) continue; // 生成物は索引であって設計書ではない
    const meta = parseFrontmatter(lines);
    const data: FrontmatterData = meta?.data ?? new Map();
    const bodyStart = meta?.bodyStart ?? 0;
    const kind = scalar(data, 'kind') ?? null;
    const id = scalar(data, 'id') ?? null;
    const context = v4 ? contextOfV4(kind, docsRel, data) : readContext(kind, data);
    const dependsOn = stringList(data, 'depends_on').filter((dep) => !dep.startsWith('external:'));
    const relPath = relative(targetRoot, file);
    const doc: ContextDoc = { relPath, docsRel, file, id, kind, context, dependsOn, lines, bodyStart };
    docs.push(doc);
    if (id !== null && id !== '' && !byId.has(id)) byId.set(id, doc);
  }
  return { docs, byId, v4 };
}

export interface ContextReference {
  readonly target: ContextDoc;
  readonly line: number;
}

const BODY_LINK_RE = /\[[^\]]*\]\(\s*<?([^)<>\s]+)>?(?:\s+"[^"]*")?\s*\)/g;
const QUALIFIED_ID_RE = /\b([a-z][a-z0-9-]*)\/([A-Z]+-\d{3})\b/g;

function resolveLinkTarget(fromFile: string, targetRoot: string, target: string): string | null {
  const stripped = (target.split('#')[0] ?? target).trim();
  if (stripped === '' || /^[a-z][a-z0-9+.-]*:/i.test(stripped)) return null; // 外部リンク
  const abs = stripped.startsWith('/') ? join(targetRoot, stripped.slice(1)) : join(dirname(fromFile), stripped);
  return abs;
}

/** doc の depends_on・本文リンク・修飾 ID から参照先 doc を解決する。解決できない参照は無視する (別検査の責務)。 */
export function extractReferences(doc: ContextDoc, graph: ContextGraph, targetRoot: string): readonly ContextReference[] {
  const refs: ContextReference[] = [];
  const byRelPath = new Map<string, ContextDoc>(graph.docs.map((d) => [d.file, d]));

  for (const dependency of doc.dependsOn) {
    const target = graph.byId.get(dependency);
    if (target === undefined || target === doc) continue;
    let line = 1;
    for (let i = 0; i < doc.bodyStart; i += 1) {
      if ((doc.lines[i] ?? '').includes(dependency)) {
        line = i + 1;
        break;
      }
    }
    refs.push({ target, line });
  }

  const kinds = classifyLines(doc.lines);
  for (let i = doc.bodyStart; i < doc.lines.length; i += 1) {
    if (kinds[i] !== 'body') continue;
    const line = doc.lines[i] ?? '';

    for (const matched of line.matchAll(BODY_LINK_RE)) {
      const raw = matched[1];
      if (raw === undefined) continue;
      const abs = resolveLinkTarget(doc.file, targetRoot, raw);
      if (abs === null) continue;
      const target = byRelPath.get(abs);
      if (target !== undefined && target !== doc) refs.push({ target, line: i + 1 });
    }

    for (const matched of line.matchAll(QUALIFIED_ID_RE)) {
      const docId = matched[1];
      if (docId === undefined) continue;
      const target = graph.byId.get(docId);
      if (target !== undefined && target !== doc) refs.push({ target, line: i + 1 });
    }
  }
  return refs;
}

// ---------------------------------------------------------------------------
// 新しい構成の、読む範囲 (B6)
// ---------------------------------------------------------------------------

/** まとまりの名前として使えるか。置き場所の表の `<c>` に当たる名前 (shared は全体共通のまとまり。tasks など固定のフォルダの名前は除く) */
function isContextName(name: string): boolean {
  if (name === SHARED_CONTEXT) return true;
  if (name.startsWith('.')) return false;
  // 約束 (context-contract) の `<c>` は、固定のフォルダ (shared・tasks) を除く。まとまりの名前の正本は置き場所の表
  return matchPlacement('context-contract', `ai/specs/${name}/contract.md`).ok;
}

/** まとまりのフォルダを持つ場所。まとまりの名前のフォルダが、この直下に並ぶ */
const CONTEXT_FOLDER_PARENTS: readonly string[] = ['person/design', 'ai/specs'];

/** まとまり `name` のフォルダ (person/design/<name>・ai/specs/<name>) が、どちらかにあるか (B6) */
export function hasContextFolder(docsDir: string, name: string): boolean {
  return isContextName(name) && CONTEXT_FOLDER_PARENTS.some((parent) => isDir(join(docsDir, parent, name)));
}

/** まとまりのフォルダの名前 (shared を除く) を、文字コード順に返す */
export function listContextFolders(docsDir: string): readonly string[] {
  const names = new Set<string>();
  for (const parent of CONTEXT_FOLDER_PARENTS) {
    const dir = join(docsDir, parent);
    if (!isDir(dir)) continue;
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (entry.isDirectory() && entry.name !== SHARED_CONTEXT && isContextName(entry.name)) names.add(entry.name);
    }
  }
  return [...names].sort();
}

/**
 * context-files・context-size が読む範囲 (B6): person/requirements/・person/design/shared/・person/design/<c>/・
 * ai/specs/shared/・ai/specs/<c>/ の文書 (README.md を除く)。加えて、自分のまとまり (context が <c>) の文書が参照する
 * 隣の約束 (context-contract)。--with-shared の有無で変わらない。決定の記録・手引き・提出物は含まない。
 */
export function readingSet(graph: ContextGraph, targetRoot: string, context: string): readonly ContextDoc[] {
  const folders = ['person/requirements/', 'person/design/shared/', `person/design/${context}/`, 'ai/specs/shared/', `ai/specs/${context}/`];
  const inRange = graph.docs.filter((doc) => folders.some((folder) => doc.docsRel.startsWith(folder)));
  const range = new Map<string, ContextDoc>(inRange.map((doc) => [doc.relPath, doc]));
  for (const doc of inRange) {
    if (doc.context !== context) continue;
    for (const ref of extractReferences(doc, graph, targetRoot)) {
      if (ref.target.kind === 'context-contract' && ref.target.context !== context) range.set(ref.target.relPath, ref.target);
    }
  }
  return [...range.values()];
}
