// kind: delivery-chapter の文書を由来の「塊」(既定は H2 節) に分ける。
// Spec: docs/explanation/04-provenance-and-agreement.md §3
//
// frontmatter・AUTOGEN 区間・export で落とす節 (既定「関連」) は塊にしない。export の
// `omitSections`/`stripFrontmatterAndAutogen` をそのまま再利用する (ゼロ変更、export 側は触らない)。

import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { omitSections } from '../export/OmitSections.js';
import type { StrippedLine } from '../export/MarkdownStrip.js';
import { UnclosedAutogenError, stripFrontmatterAndAutogen } from '../export/MarkdownStrip.js';
import { parseFrontmatter, scalar } from './Frontmatter.js';

/** 由来の既定粒度 (§3)。「関連」節は社内向けの上流/下流表であって由来を持たない。 */
export const DEFAULT_OMIT_SECTIONS: readonly string[] = ['関連'];

export interface DeliveryBlock {
  /** H2 見出しの生テキスト (連番も含む。例: "1. 予約の受付") */
  readonly anchor: string;
  /** 見出し行を除いた節の本文 (fingerprint の対象) */
  readonly text: string;
  /** 見出し行の元ファイル 1 始まり行番号 */
  readonly line: number;
}

export type BlockExtractionResult =
  | { readonly kind: 'ok'; readonly blocks: readonly DeliveryBlock[] }
  | { readonly kind: 'unclosed-autogen'; readonly message: string };

const FENCE_RE = /^\s*(```|~~~)/;
const H2_RE = /^##\s+(.*?)\s*$/;

/** 章 1 本の Markdown 全文から塊を取り出す。AUTOGEN が閉じられていなければ 'unclosed-autogen' を返す。 */
export function extractDeliveryBlocks(
  content: string,
  relPath: string,
  omitTitles: readonly string[] = DEFAULT_OMIT_SECTIONS,
): BlockExtractionResult {
  let filtered: readonly StrippedLine[];
  try {
    filtered = omitSections(stripFrontmatterAndAutogen(content, relPath), omitTitles);
  } catch (error) {
    if (error instanceof UnclosedAutogenError) return { kind: 'unclosed-autogen', message: error.message };
    throw error;
  }

  const blocks: DeliveryBlock[] = [];
  let current: { anchor: string; line: number; lines: string[] } | null = null;
  let inFence = false;
  const flush = (): void => {
    if (current !== null) blocks.push({ anchor: current.anchor, line: current.line, text: current.lines.join('\n') });
    current = null;
  };
  for (const sl of filtered) {
    if (FENCE_RE.test(sl.text)) inFence = !inFence;
    if (!inFence) {
      const matched = H2_RE.exec(sl.text);
      if (matched !== null) {
        flush();
        current = { anchor: (matched[1] ?? '').trim(), line: sl.line, lines: [] };
        continue;
      }
    }
    if (current !== null) current.lines.push(sl.text);
  }
  flush();
  return { kind: 'ok', blocks };
}

// --- delivery-chapter の一覧 (provenance-check/coverage の引数省略時に使う) ---
// ContextGraph.ts と同型のディレクトリ走査だが、別ファイルとして持つ (既存ファイルへの
// 変更を増やさないため。REQ-135 的な「cp しない」と同じ理由で、共通化のための既存ファイル
// 変更は今回のタスク範囲外)。

const SKIP_DIR = new Set(['node_modules', 'dist', 'coverage']);

function listMarkdown(dir: string): string[] {
  const found: string[] = [];
  const walk = (current: string): void => {
    for (const entry of readdirSync(current, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
      const full = join(current, entry.name);
      if (entry.isDirectory()) {
        if (SKIP_DIR.has(entry.name) || entry.name.startsWith('.')) continue;
        walk(full);
        continue;
      }
      if (entry.name.endsWith('.md') && entry.name !== 'README.md') found.push(full);
    }
  };
  walk(dir);
  return found;
}

const isDir = (path: string): boolean => existsSync(path) && statSync(path).isDirectory();

/** docsDir 以下から kind: delivery-chapter の文書 (絶対パス) を全部集める。docsDir が無ければ []。 */
export function findDeliveryChapters(docsDir: string): readonly string[] {
  if (!isDir(docsDir)) return [];
  return listMarkdown(docsDir).filter((file) => {
    const lines = readFileSync(file, 'utf8').split(/\r?\n/);
    if (lines[0]?.includes('AUTOGENERATED')) return false;
    const meta = parseFrontmatter(lines);
    return meta !== null && scalar(meta.data, 'kind') === 'delivery-chapter';
  });
}
