// node --test dist
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { collectRowDefinedTokens } from './IdDefinitions.js';

describe('collectRowDefinedTokens', () => {
  it('行頭セル (`| REQ-nnn | ...`) だけを定義として集め、本文中の言及は数えない', () => {
    const lines = [
      '## 1. 機能要件',
      '',
      '| ID | パターン | 要件文 | 対応業務 (REQ-0xx) | 受け入れ条件 |',
      '|---|---|---|---|---|',
      '| REQ-101 | Event | 予約を作成する | REQ-001 | 予約が作成されること |',
      '',
      '## 2. 前提',
      '',
      '他ファイルの REQ-999 を裸で言及するだけの段落 (定義ではない)。',
    ];
    assert.deepEqual(collectRowDefinedTokens(lines, 'REQ'), ['REQ-101']);
  });

  it('AUTOGEN 区間の行頭セルは定義に数えない (code-reviewer 実バグ #3)', () => {
    // decision-log の「仮置き一覧 (自動生成)」節を模した fixture。この索引は「仮置きマークが
    // どこにあるか」を示すだけで、OPEN-005 が §2 (未決) に実在する定義ではない。
    const lines = [
      '## 2. 未決 (OPEN)',
      '',
      '| ID | 論点 | 推奨案 | 仮置き値 | 影響する文書 |',
      '|---|---|---|---|---|',
      '| OPEN-001 | 未確定の値 | A 案 | 30 日 | requirements/REQ-201 |',
      '',
      '## 3. 仮置き一覧 (自動生成)',
      '',
      '<!-- AUTOGEN:tentative-index:start — generated by scripts/generate-docs-graph.mjs, do not edit by hand -->',
      '| OPEN | 場所 | 本文 |',
      '|---|---|---|',
      '| OPEN-005 | [product/02-tenancy.md:40](product/02-tenancy.md#L40) | 仮置きの値 (OPEN-005) |',
      '<!-- AUTOGEN:tentative-index:end -->',
    ];
    // §2 に本物の定義があるのは OPEN-001 だけ。OPEN-005 は AUTOGEN の索引行にしか現れないので
    // 「定義」に数えてはいけない。
    assert.deepEqual(collectRowDefinedTokens(lines, 'OPEN'), ['OPEN-001']);
  });

  it('AUTOGEN 区間の前後にある本物の定義行は数える (区間だけを除外する)', () => {
    const lines = [
      '| DEC-001 | 決定その1 |',
      '<!-- AUTOGEN:x:start -->',
      '| DEC-999 | 索引の行 (定義ではない) |',
      '<!-- AUTOGEN:x:end -->',
      '| DEC-002 | 決定その2 |',
    ];
    assert.deepEqual(collectRowDefinedTokens(lines, 'DEC'), ['DEC-001', 'DEC-002']);
  });
});
