// node --test dist
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { classifyLines, hasLiveMatch, hasLiveOccurrence, isNegatedOrHearsayAfter, isQuotedAt } from './LineClassifier.js';

describe('classifyLines', () => {
  it('コードフェンス内 (開始/終了行を含む) は code-fence', () => {
    const lines = ['本文1', '```', '仮置きで30日とする。', '```', '本文2'];
    assert.deepEqual(classifyLines(lines), ['body', 'code-fence', 'code-fence', 'code-fence', 'body']);
  });

  it('AUTOGEN 区間 (開始/終了行を含む) は autogen', () => {
    const lines = [
      '本文1',
      '<!-- AUTOGEN:tentative-index:start -->',
      '| OPEN-005 | 場所 | 仮置きの値 |',
      '<!-- AUTOGEN:tentative-index:end -->',
      '本文2',
    ];
    assert.deepEqual(classifyLines(lines), ['body', 'autogen', 'autogen', 'autogen', 'body']);
  });

  it('複数行 HTML コメント (開始/終了行を含む) は html-comment', () => {
    const lines = ['本文1', '<!--', '著者向けの注記: 仮置きで30日とする。', '-->', '本文2'];
    assert.deepEqual(classifyLines(lines), ['body', 'html-comment', 'html-comment', 'html-comment', 'body']);
  });

  it('単行 HTML コメント (開始と終了が同じ行) は html-comment', () => {
    const lines = ['本文1', '<!-- 例: REQ-101 は要件定義書由来 -->', '本文2'];
    assert.deepEqual(classifyLines(lines), ['body', 'html-comment', 'body']);
  });

  it('AUTOGEN の開始/終了マーカーは単行 HTML コメントでもあるが autogen が優先する', () => {
    // マーカー行自体が `<!-- ... -->` (単行コメント) の形をしているため、コメント判定を先に
    // 確定すると AUTOGEN のトグルが更新されない相互作用があった (code-reviewer 実バグ #1)。
    const lines = [
      '<!-- AUTOGEN:tentative-index:start — generated by scripts/generate-docs-graph.mjs, do not edit by hand -->',
      '| OPEN-005 | 場所 | 本文 |',
      '<!-- AUTOGEN:tentative-index:end -->',
      '本文 (AUTOGEN の外)',
    ];
    assert.deepEqual(classifyLines(lines), ['autogen', 'autogen', 'autogen', 'body']);
  });

  it('コードフェンス内の AUTOGEN/コメント風の例示はコードフェンスが優先する', () => {
    const lines = ['```', '<!-- AUTOGEN:x:start -->', '```', '本文'];
    assert.deepEqual(classifyLines(lines), ['code-fence', 'code-fence', 'code-fence', 'body']);
  });

  it('通常の本文行は body', () => {
    assert.deepEqual(classifyLines(['ただの本文。']), ['body']);
  });
});

describe('isQuotedAt / isNegatedOrHearsayAfter', () => {
  it('「」『』の対で開いた内側は引用と判定する', () => {
    const line = '前版は「仮置き」と書かれていた。';
    const index = line.indexOf('仮置き');
    assert.equal(isQuotedAt(line, index), true);
  });

  it('引用の外は引用と判定しない', () => {
    const line = '仮置きで30日とする。';
    assert.equal(isQuotedAt(line, line.indexOf('仮置き')), false);
  });

  it('直後が否定なら true', () => {
    const line = 'この値は仮置きではない。';
    const end = line.indexOf('仮置き') + '仮置き'.length;
    assert.equal(isNegatedOrHearsayAfter(line, end), true);
  });

  it('直後が伝聞なら true', () => {
    const line = 'メモには仮置きと書かれていた。';
    const end = line.indexOf('仮置き') + '仮置き'.length;
    assert.equal(isNegatedOrHearsayAfter(line, end), true);
  });

  it('直後が通常の文なら false', () => {
    const line = '仮置きで30日とする。';
    const end = line.indexOf('仮置き') + '仮置き'.length;
    assert.equal(isNegatedOrHearsayAfter(line, end), false);
  });
});

describe('hasLiveOccurrence', () => {
  it('引用でも否定でもない出現があれば true', () => {
    assert.equal(hasLiveOccurrence('猶予は仮置きで30日とする (OPEN-001)。', '仮置き'), true);
  });

  it('引用内だけの出現は false', () => {
    assert.equal(hasLiveOccurrence('前版は「仮置き」と書かれていた。', '仮置き'), false);
  });

  it('否定直後の出現は false', () => {
    assert.equal(hasLiveOccurrence('この値は仮置きではない。', '仮置き'), false);
  });

  it('否定の decoy を先に置いても後続の本物の出現を見逃さない (round 3 C2)', () => {
    assert.equal(hasLiveOccurrence('前者は仮置きではないが、後者は仮置きで30日とする。', '仮置き'), true);
  });

  it('出現が無ければ false', () => {
    assert.equal(hasLiveOccurrence('普通の文。', '仮置き'), false);
  });
});

describe('hasLiveMatch', () => {
  const patterns = [/CEO[^\n。、]{0,20}決定/];

  it('引用でも否定でもない出現があれば true', () => {
    assert.equal(hasLiveMatch('CEO が決定した内容。', patterns), true);
  });

  it('引用内だけの出現は false', () => {
    assert.equal(hasLiveMatch('出典を「CEO が決定」から訂正した。', patterns), false);
  });

  it('否定直後の出現は false', () => {
    assert.equal(hasLiveMatch('これは CEO が決定ではない。', patterns), false);
  });
});
