// 正規化 v3 のリンクの行き先の置き換え (docs/adr/0007-fingerprint-link-normalization.md 決定 1)。
// 「どの行き先をどう直すか」の表はここに 1 か所だけ持つ。パスから id を引く表は、buildSourceIndex が
// 持つ `SourceDoc.relPath` と `id` から作る (新しい索引は作らない)。
//
// | 行き先                                                                  | 直した後                                 |
// |-------------------------------------------------------------------------|------------------------------------------|
// | 外部 URL (`https://` 等)・アンカーだけ (`#節`)                           | そのまま (移行で変わらない)              |
// | 索引にある文書 (= frontmatter `id` を持つ)                               | `id:<id>` + `#アンカー`                  |
// | 索引に無い実在のパス (id の無い文書・README・docs/ の外のファイル等)     | repo 相対の正規パス + `#アンカー`        |
// | 存在しないパス                                                          | そのまま (リンク切れは docs-check が落とす) |
//
// 実在の確認はディスクを見るので、v3 の指紋は repo の状態 (索引と、リンク先の実在) に依存する。
// これは ADR-0007 の「代償」で、リンク先が無い → 有る (または id が変わる) と指紋が変わる。
//
// 既知の限界: README.md と AUTOGENERATED の文書は buildSourceIndex の対象外なので、id を持っていても
// 「索引に無い実在のパス」として repo 相対パスで数える (リンク先を動かすと指紋が変わる)。

import { existsSync } from 'node:fs';
import { join, posix, sep } from 'node:path';
import type { DestinationRewriter } from './Fingerprint.js';
import type { SourceIndex } from './SourceResolver.js';

/** `https://` `mailto:` など。`id:` は v3 が書く形なので、ここで止まる (直したものをもう一度直さない)。 */
const SCHEME_RE = /^[a-z][a-z0-9+.-]*:/i;

const toPosix = (path: string): string => path.split(sep).join('/');

/** リンクの行き先は百分率エンコードされうる。壊れた列 (`%` だけ等) は、そのまま使う。 */
function decodePath(path: string): string {
  try {
    return decodeURIComponent(path);
  } catch {
    return path;
  }
}

/** repo 相対の正規パス: `./`・`../` をたたみ、末尾の `/` を除く。 */
function canonicalPath(path: string): string {
  const normalized = posix.normalize(path);
  return normalized.length > 1 && normalized.endsWith('/') ? normalized.slice(0, -1) : normalized;
}

export interface LinkTable {
  /**
   * 本文がある文書 (repo 相対パス) を起点に、リンクの行き先を v3 の形へ直す関数を返す。
   * 正本の節なら正本の文書、章なら章の文書を渡す (リンクの相対パスはその文書から見たもの)。
   */
  rewriterFor(docRelPath: string): DestinationRewriter;
}

/** index が null (docs が無い) なら id の表は空。リンク先が実在するファイルかどうかだけで決まる。 */
export function buildLinkTable(targetRoot: string, index: SourceIndex | null): LinkTable {
  const idByPath = new Map<string, string>();
  for (const doc of index?.docs ?? []) {
    if (doc.id !== null && doc.id !== '') idByPath.set(toPosix(doc.relPath), doc.id);
  }
  return {
    rewriterFor(docRelPath) {
      const docDir = posix.dirname(toPosix(docRelPath));
      return (destination) => {
        if (SCHEME_RE.test(destination)) return destination;
        const hash = destination.indexOf('#');
        const pathPart = hash === -1 ? destination : destination.slice(0, hash);
        const fragment = hash === -1 ? '' : destination.slice(hash);
        if (pathPart === '') return destination; // アンカーだけ
        const decoded = decodePath(pathPart);
        // 先頭の `/` は repo 直下からのパス (docs-check の本文リンクの検査と同じ解釈)
        const repoPath = canonicalPath(decoded.startsWith('/') ? decoded.slice(1) : posix.join(docDir, decoded));
        const id = idByPath.get(repoPath);
        if (id !== undefined) return `id:${id}${fragment}`;
        return existsSync(join(targetRoot, repoPath)) ? `${repoPath}${fragment}` : destination;
      };
    },
  };
}
