// 由来 (`from`) の修飾 ID / 節指定を正本側で解決する。
// Spec: docs/explanation/04-provenance-and-agreement.md §4
//
// 形は 2 種:
//   - `<doc-id>/PREFIX-nnn`  … 行頭セル定義 (`| PREFIX-nnn | ... |`)。判定は core/IdDefinitions.ts の
//     「行頭セルだけを定義とする」規約と同じにする (ただし行番号・行テキストも要るため、この
//     ファイルに小さく複製する。既存ファイルへの変更は今回のタスクの対象外)
//   - `<doc-id>#<見出し>`    … 正本の H2 見出し (delivery-chapter の由来元は通常の設計書なので
//     export の omitSections は適用しない。見出しの生テキスト (連番含む) で一致させる —
//     core/DeliveryBlocks.ts の anchor と同じ形にして、由来元・章側の書き方を揃える)

import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';
import { classifyLines } from './LineClassifier.js';
import type { FrontmatterData } from './Frontmatter.js';
import { parseFrontmatter, scalar } from './Frontmatter.js';

const SKIP_DIR = new Set(['node_modules', 'dist', 'coverage']);

export interface SourceDoc {
  readonly relPath: string;
  readonly file: string;
  readonly id: string | null;
  readonly kind: string | null;
  readonly status: string | null;
  /** frontmatter `clientExempt: true` (source-coverage の文書単位の対象外) */
  readonly clientExempt: boolean;
  readonly lines: readonly string[];
  readonly bodyStart: number;
}

export interface SourceIndex {
  readonly docs: readonly SourceDoc[];
  readonly byId: ReadonlyMap<string, SourceDoc>;
}

function isDir(path: string): boolean {
  return existsSync(path) && statSync(path).isDirectory();
}

function listMarkdown(dir: string): string[] {
  const found: string[] = [];
  const walk = (current: string): void => {
    for (const entry of readdirSync(current, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
      const full = join(current, entry.name);
      if (entry.isDirectory()) {
        if (SKIP_DIR.has(entry.name) || entry.name.startsWith('.')) continue;
        walk(full);
        continue;
      }
      if (entry.name.endsWith('.md') && entry.name !== 'README.md') found.push(full);
    }
  };
  walk(dir);
  return found;
}

/** docsDir が無ければ null。 */
export function buildSourceIndex(targetRoot: string, docsDir: string): SourceIndex | null {
  if (!isDir(docsDir)) return null;
  const docs: SourceDoc[] = [];
  const byId = new Map<string, SourceDoc>();
  for (const file of listMarkdown(docsDir)) {
    const lines = readFileSync(file, 'utf8').split(/\r?\n/);
    if (lines[0]?.includes('AUTOGENERATED')) continue;
    const meta = parseFrontmatter(lines);
    const data: FrontmatterData = meta?.data ?? new Map();
    const bodyStart = meta?.bodyStart ?? 0;
    const doc: SourceDoc = {
      relPath: relative(targetRoot, file),
      file,
      id: scalar(data, 'id') ?? null,
      kind: scalar(data, 'kind') ?? null,
      status: scalar(data, 'status') ?? null,
      clientExempt: scalar(data, 'clientExempt') === 'true',
      lines,
      bodyStart,
    };
    docs.push(doc);
    if (doc.id !== null && doc.id !== '' && !byId.has(doc.id)) byId.set(doc.id, doc);
  }
  return { docs, byId };
}

export type SourceResolution =
  | { readonly kind: 'row' | 'section'; readonly doc: SourceDoc; readonly line: number; readonly text: string }
  | { readonly kind: 'missing' };

const ROW_FROM_RE = /^([a-z][a-z0-9-]*)\/([A-Z]+-\d{3})$/;
const SECTION_FROM_RE = /^([a-z][a-z0-9-]*)#(.+)$/;
const H2_RE = /^##\s+(.*?)\s*$/;
const FENCE_RE = /^\s*(```|~~~)/;

const escapeRegExp = (s: string): string => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

/** `| PREFIX-nnn | ... |` の行頭セル定義を探す。core/IdDefinitions.ts の collectRowDefinedTokens と同じ判定。 */
function findDefinedRow(lines: readonly string[], bodyStart: number, token: string): { line: number; text: string } | null {
  const kinds = classifyLines(lines);
  const rowRe = new RegExp(`^\\|\\s*${escapeRegExp(token)}\\s*\\|`);
  for (let i = bodyStart; i < lines.length; i += 1) {
    if (kinds[i] !== 'body') continue;
    if (rowRe.test((lines[i] ?? '').trim())) return { line: i + 1, text: lines[i] ?? '' };
  }
  return null;
}

/** H2 見出しの生テキストで一致する節の本文を返す (見出し行は含めない)。 */
function findSection(lines: readonly string[], bodyStart: number, heading: string): { line: number; text: string } | null {
  let inFence = false;
  let current: { line: number; heading: string; body: string[] } | null = null;
  let matched: { line: number; text: string } | null = null;
  const settle = (): void => {
    if (current !== null && current.heading === heading) matched = { line: current.line, text: current.body.join('\n') };
  };
  for (let i = bodyStart; i < lines.length; i += 1) {
    const line = lines[i] ?? '';
    if (FENCE_RE.test(line)) inFence = !inFence;
    if (!inFence) {
      const h2 = H2_RE.exec(line);
      if (h2 !== null) {
        settle();
        if (matched !== null) return matched;
        current = { line: i + 1, heading: (h2[1] ?? '').trim(), body: [] };
        continue;
      }
    }
    if (current !== null) current.body.push(line);
  }
  settle();
  return matched;
}

/** `from` (修飾 ID または `<doc-id>#<見出し>`) を正本側で解決する。 */
export function resolveSource(index: SourceIndex, from: string): SourceResolution {
  const rowMatch = ROW_FROM_RE.exec(from);
  if (rowMatch !== null) {
    const doc = index.byId.get(rowMatch[1] ?? '');
    if (doc === undefined) return { kind: 'missing' };
    const found = findDefinedRow(doc.lines, doc.bodyStart, rowMatch[2] ?? '');
    if (found === null) return { kind: 'missing' };
    return { kind: 'row', doc, line: found.line, text: found.text };
  }
  const sectionMatch = SECTION_FROM_RE.exec(from);
  if (sectionMatch !== null) {
    const doc = index.byId.get(sectionMatch[1] ?? '');
    if (doc === undefined) return { kind: 'missing' };
    const found = findSection(doc.lines, doc.bodyStart, (sectionMatch[2] ?? '').trim());
    if (found === null) return { kind: 'missing' };
    return { kind: 'section', doc, line: found.line, text: found.text };
  }
  return { kind: 'missing' };
}
