// node --test scripts/*.test.mjs
// 章別索引 (docs/README.md と docs/design/README.md) の生成だけを検証する。
// 一時ツリーを DOCS_GRAPH_ROOT で差し替えて実際にスクリプトを起動する。
import { spawnSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { after, beforeEach, describe, it } from 'node:test';
import assert from 'node:assert/strict';

const SCRIPTS_DIR = dirname(fileURLToPath(import.meta.url));
const SCRIPT = join(SCRIPTS_DIR, 'generate-docs-graph.mjs');
const workspaces = [];

function writeDoc(root, rel, lines) {
  const target = join(root, 'docs', rel);
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, `${lines.join('\n')}\n`);
}

const doc = (id, type, kind, arc42, title) => [
  '---', `id: ${id}`, `title: ${title}`, `type: ${type}`, `kind: ${kind}`,
  `arc42: ${arc42}`, 'status: active', 'owners: [eng]', 'depends_on: []', 'relates_to: []', '---',
  '', `# ${title}`, '',
];

function makeRoot() {
  const root = mkdtempSync(join(tmpdir(), 'yatsu-graph-'));
  workspaces.push(root);
  writeDoc(root, 'product/requirements.md', doc('requirements', 'design', 'requirements', 1, '要件定義書'));
  writeDoc(root, 'adr/0001-x.md', [
    '---', 'id: adr-0001-x', 'title: ADR-0001 x', 'type: adr', 'kind: adr', 'arc42: 9',
    'status: accepted', 'owners: [eng]', 'depends_on: []', 'relates_to: []', '---', '', '# ADR-0001 x', '',
  ]);
  writeDoc(root, 'adr/README.md', [
    '---', 'id: adr-index', 'title: ADR — 索引', 'type: index', 'status: active', 'owners: [eng]', '---',
    '', '# adr', '', '## 索引', '',
    '<!-- AUTOGEN:adr-index:start — generated by scripts/generate-docs-graph.mjs, do not edit by hand -->',
    '<!-- AUTOGEN:adr-index:end -->', '',
  ]);
  writeDoc(root, 'design/basic/function-list.md', doc('function-list', 'design', 'function-list', 1, '機能一覧'));
  return root;
}

const run = (root, arg) =>
  spawnSync(process.execPath, [SCRIPT, arg], {
    encoding: 'utf8',
    env: { ...process.env, DOCS_GRAPH_ROOT: root },
  });

after(() => {
  for (const dir of workspaces) rmSync(dir, { recursive: true, force: true });
});

describe('generate-docs-graph の arc42 章別索引', () => {
  let root;
  beforeEach(() => {
    root = makeRoot();
  });

  it('別ディレクトリに実在する章はディレクトリ README へのリンクで示し、本当に無い章だけ _未作成_', () => {
    const result = run(root, '--write');
    assert.equal(result.status, 0, `${result.stdout}${result.stderr}`);
    const index = readFileSync(join(root, 'docs', 'design', 'README.md'), 'utf8');

    // §9 (ADR) は design/ の外にあるので、ディレクトリ README へのリンク 1 個で示す
    assert.match(index, /\*\*§9 Architecture Decisions\*\*.*→ \[adr\/\]\(\.\.\/adr\/README\.md\)/);
    // §1 は design/ 内 (機能一覧) と外 (要件定義書) の両方にあるので、両方出す
    assert.match(index, /\*\*§1 Introduction and Goals\*\*.*機能一覧.*→ \[product\/\]\(\.\.\/product\/README\.md\)/);
    // §11 はツリーのどこにも無いので未作成
    assert.match(index, /\*\*§11 Risks and Technical Debt\*\*[^|]*\|\s*_未作成_\s*\|/);
    // 「他所にある」ことを未作成と誤表示していないこと
    assert.doesNotMatch(index, /\*\*§9 Architecture Decisions\*\*[^|]*\|\s*_未作成_\s*\|/);
  });

  it('新規ツリーは --write 2 回で不動点になる (1 回目で README が増えるため)', () => {
    assert.equal(run(root, '--write').status, 0);
    // 1 回目の --write が docs/README.md などを新規作成し、それ自体がグラフのノードになる。
    // 既存リポでは README が揃っているので 1 回で収束する。新規ツリーだけ 2 回必要。
    assert.equal(run(root, '--write').status, 0);
    const checked = run(root, '--check');
    assert.equal(checked.status, 0, `${checked.stdout}${checked.stderr}`);
  });
});
