// node --test scripts/*.test.mjs
// 章別索引 (docs/README.md と docs/design/README.md) の生成だけを検証する。
// 一時ツリーを DOCS_GRAPH_ROOT で差し替えて実際にスクリプトを起動する。
import { spawnSync } from 'node:child_process';
import { appendFileSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { after, beforeEach, describe, it } from 'node:test';
import assert from 'node:assert/strict';

const SCRIPTS_DIR = dirname(fileURLToPath(import.meta.url));
const SCRIPT = join(SCRIPTS_DIR, 'generate-docs-graph.mjs');
const workspaces = [];

function writeDoc(root, rel, lines) {
  const target = join(root, 'docs', rel);
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, `${lines.join('\n')}\n`);
}

const doc = (id, type, kind, arc42, title) => [
  '---', `id: ${id}`, `title: ${title}`, `type: ${type}`, `kind: ${kind}`,
  `arc42: ${arc42}`, 'status: active', 'owners: [eng]', 'depends_on: []', 'relates_to: []', '---',
  '', `# ${title}`, '',
];

function makeRoot() {
  const root = mkdtempSync(join(tmpdir(), 'yatsu-graph-'));
  workspaces.push(root);
  writeDoc(root, 'product/requirements.md', doc('requirements', 'design', 'requirements', 1, '要件定義書'));
  writeDoc(root, 'adr/0001-x.md', [
    '---', 'id: adr-0001-x', 'title: ADR-0001 x', 'type: adr', 'kind: adr', 'arc42: 9',
    'status: accepted', 'owners: [eng]', 'depends_on: []', 'relates_to: []', '---', '', '# ADR-0001 x', '',
  ]);
  writeDoc(root, 'adr/README.md', [
    '---', 'id: adr-index', 'title: ADR — 索引', 'type: index', 'status: active', 'owners: [eng]', '---',
    '', '# adr', '', '## 索引', '',
    '<!-- AUTOGEN:adr-index:start — generated by scripts/generate-docs-graph.mjs, do not edit by hand -->',
    '<!-- AUTOGEN:adr-index:end -->', '',
  ]);
  writeDoc(root, 'design/basic/function-list.md', doc('function-list', 'design', 'function-list', 1, '機能一覧'));
  return root;
}

const run = (root, arg) =>
  spawnSync(process.execPath, [SCRIPT, arg], {
    encoding: 'utf8',
    env: { ...process.env, DOCS_GRAPH_ROOT: root },
  });

after(() => {
  for (const dir of workspaces) rmSync(dir, { recursive: true, force: true });
});

describe('generate-docs-graph の arc42 章別索引', () => {
  let root;
  beforeEach(() => {
    root = makeRoot();
  });

  it('別ディレクトリに実在する章はディレクトリ README へのリンクで示し、本当に無い章だけ _未作成_', () => {
    const result = run(root, '--write');
    assert.equal(result.status, 0, `${result.stdout}${result.stderr}`);
    const index = readFileSync(join(root, 'docs', 'design', 'README.md'), 'utf8');

    // §9 (ADR) は design/ の外にあるので、ディレクトリ README へのリンク 1 個で示す
    assert.match(index, /\*\*§9 Architecture Decisions\*\*.*→ \[adr\/\]\(\.\.\/adr\/README\.md\)/);
    // §1 は design/ 内 (機能一覧) と外 (要件定義書) の両方にあるので、両方出す
    assert.match(index, /\*\*§1 Introduction and Goals\*\*.*機能一覧.*→ \[product\/\]\(\.\.\/product\/README\.md\)/);
    // §11 はツリーのどこにも無いので未作成
    assert.match(index, /\*\*§11 Risks and Technical Debt\*\*[^|]*\|\s*_未作成_\s*\|/);
    // 「他所にある」ことを未作成と誤表示していないこと
    assert.doesNotMatch(index, /\*\*§9 Architecture Decisions\*\*[^|]*\|\s*_未作成_\s*\|/);
  });

  it('新規ツリーは --write 2 回で不動点になる (1 回目で README が増えるため)', () => {
    assert.equal(run(root, '--write').status, 0);
    // 1 回目の --write が docs/README.md などを新規作成し、それ自体がグラフのノードになる。
    // 既存リポでは README が揃っているので 1 回で収束する。新規ツリーだけ 2 回必要。
    assert.equal(run(root, '--write').status, 0);
    const checked = run(root, '--check');
    assert.equal(checked.status, 0, `${checked.stdout}${checked.stderr}`);
  });
});

describe('generate-docs-graph の本文リンク検査', () => {
  let root;
  // 索引が収束した状態から本文だけを書き換える (索引 drift と混ざらないようにするため)
  const converge = (r) => {
    assert.equal(run(r, '--write').status, 0);
    assert.equal(run(r, '--write').status, 0);
    assert.equal(run(r, '--check').status, 0);
  };
  const appendBody = (rel, lines) => appendFileSync(join(root, 'docs', rel), `${lines.join('\n')}\n`);

  beforeEach(() => {
    root = makeRoot();
    converge(root);
  });

  it('正例: 実在する相対リンク・外部 URL・アンカーのみ・コードフェンス内・AUTOGEN 区間は通る', () => {
    appendBody('design/basic/function-list.md', [
      '本文: [要件定義書](../../product/requirements.md) と [ADR](../../adr/0001-x.md#decision)。',
      '外部: [arc42](https://arc42.org/overview/) / アンカー: [上へ](#機能一覧)。',
      'インラインコード: `[x](./nope.md)` は本文リンクではない。',
      '',
      '```markdown',
      '[コードフェンス内の例](./absolutely-missing.md)',
      '```',
      '',
      '<!-- AUTOGEN:sample:start -->',
      '[生成区間](./generated-missing.md)',
      '<!-- AUTOGEN:sample:end -->',
    ]);
    const result = run(root, '--check');
    assert.equal(result.status, 0, `${result.stdout}${result.stderr}`);
  });

  it('負例: 解決できない相対リンクは ERROR (exit 1) で file:line 付きで報告される', () => {
    appendBody('design/basic/function-list.md', ['下流: [画面設計](./screens/README.md) を参照。']);
    const result = run(root, '--check');
    assert.equal(result.status, 1);
    assert.match(result.stderr, /\[link\] docs\/design\/basic\/function-list\.md:\d+ → \.\/screens\/README\.md/);
  });

  it('doc を直接持たず子ディレクトリだけのディレクトリにも索引 README を作る', () => {
    writeDoc(root, 'design/detail/domain/overview.md', doc('domain-overview', 'design', 'domain-overview', 5, 'ドメイン概要'));
    converge(root);
    const readme = join(root, 'docs', 'design', 'detail', 'README.md');
    assert.ok(existsSync(readme), 'design/detail/README.md が生成されていない');
    assert.match(readFileSync(readme, 'utf8'), /\[domain\/\]\(domain\/README\.md\)/);
  });

  it('arc42 未割当の doc は warning になる', () => {
    writeDoc(root, 'design/basic/nonfunctional.md', [
      '---', 'id: nonfunctional', 'title: 非機能要件', 'type: design', 'kind: nonfunctional',
      'status: active', 'owners: [eng]', 'depends_on: []', 'relates_to: []', '---', '', '# 非機能要件', '',
    ]);
    const result = run(root, '--write');
    assert.equal(result.status, 0, `${result.stdout}${result.stderr}`);
    assert.match(result.stderr, /docs\/design\/basic\/nonfunctional\.md に frontmatter arc42 が無い/);
  });

  it('ADR が 1 本も無いツリーでは docs/adr/README.md を要求しない', () => {
    rmSync(join(root, 'docs', 'adr'), { recursive: true, force: true });
    converge(root);
    assert.equal(existsSync(join(root, 'docs', 'adr')), false, 'docs/adr/ を勝手に作っている');
    const result = run(root, '--check');
    assert.equal(result.status, 0, `${result.stdout}${result.stderr}`);
  });

  it('負例: ADR があるのに docs/adr/README.md が無ければ落ちる (索引を黙って捨てない)', () => {
    rmSync(join(root, 'docs', 'adr', 'README.md'));
    const result = run(root, '--write');
    assert.notEqual(result.status, 0);
    assert.match(result.stderr, /docs\/adr\/README\.md/);
  });

  it('docs/design/ が無いツリーでは design/README.md を作らない', () => {
    rmSync(join(root, 'docs', 'design'), { recursive: true, force: true });
    converge(root);
    assert.equal(existsSync(join(root, 'docs', 'design')), false, 'docs/design/ を勝手に作っている');
    const result = run(root, '--check');
    assert.equal(result.status, 0, `${result.stdout}${result.stderr}`);
  });

  it('arc42 を持つ文書が 1 本も無いツリーでは docs/README.md を章別ではなくファイル一覧にする (12 行の _未作成_ を出さない)', () => {
    for (const d of ['product', 'design', 'adr']) rmSync(join(root, 'docs', d), { recursive: true, force: true });
    writeDoc(root, 'guides/how-to.md', [
      '---', 'id: how-to', 'title: 手引き', 'type: guide', 'kind: guide',
      'status: active', 'owners: [eng]', 'depends_on: []', 'relates_to: []', '---', '', '# 手引き', '',
    ]);
    converge(root);
    const index = readFileSync(join(root, 'docs', 'README.md'), 'utf8');
    assert.doesNotMatch(index, /_未作成_/);
    assert.match(index, /\| ファイル \| タイトル \|/);
    assert.match(index, /\[guides\/\]\(guides\/README\.md\)/);
  });

  it('ディレクトリ索引は <context>.md を <context>-<aspect>.md より先に並べる', () => {
    writeDoc(root, 'design/detail/domain/catalog.md', doc('domain-catalog', 'design', 'domain-model', 5, 'catalog'));
    writeDoc(root, 'design/detail/domain/catalog-pricing.md', doc('domain-catalog-pricing', 'design', 'domain-model', 5, 'catalog / 料金'));
    converge(root);
    const index = readFileSync(join(root, 'docs', 'design', 'detail', 'domain', 'README.md'), 'utf8');
    assert.ok(index.indexOf('[catalog.md]') < index.indexOf('[catalog-pricing.md]'), index);
  });

  it('ディレクトリ索引に各文書の TL;DR を「説明」列として出す (強調・リンク・コードは剥がす)', () => {
    writeDoc(root, 'design/detail/domain/catalog.md', [
      ...doc('domain-catalog', 'design', 'domain-model', 5, 'catalog'),
      '> **TL;DR**: 「何を貸すか」を持つ。**在庫の個体は持たない** (それは [索引](./README.md))。`Item` が集約。',
      '',
    ]);
    writeDoc(root, 'design/detail/domain/README.md', [
      '---', 'id: domain-index', 'title: domain — 索引', 'type: index', 'status: active', 'owners: [eng]', '---', '',
      '# domain', '', '> このディレクトリの目的: ドメインクラス図。1 コンテキスト 1 ファイル。', '', '## 索引', '',
      '<!-- AUTOGEN:dir-index:start — generated by scripts/generate-docs-graph.mjs, do not edit by hand -->',
      '<!-- AUTOGEN:dir-index:end -->', '',
    ]);
    converge(root);
    const domain = readFileSync(join(root, 'docs', 'design', 'detail', 'domain', 'README.md'), 'utf8');
    assert.match(domain, /\| ファイル \| タイトル \| 説明 \|/);
    assert.match(domain, /\[catalog\.md\]\(catalog\.md\) \| catalog \| 「何を貸すか」を持つ。在庫の個体は持たない \(それは 索引\)。Item が集約。 \|/);
    // 親 (detail/) の索引では、子ディレクトリの行に README の「目的」を出す
    const detail = readFileSync(join(root, 'docs', 'design', 'detail', 'README.md'), 'utf8');
    assert.match(detail, /\[domain\/\]\(domain\/README\.md\) \| domain — 索引 \| ドメインクラス図。1 コンテキスト 1 ファイル。 \|/);
  });
});
