// 新しい repo の骨格を置く。Spec: docs/design/test/specs/06-init-scaffold.md の I1〜I11。
//
// 置くもの (I1): .igeta-version / docs/README.md (入口の 3 行と索引の区間) / 人の文書 3 本 (地図・要件・決定台帳。雛形から) /
// docs/person/decisions/README.md / markdownlint の設定 2 本 / AGENTS.md と .github/CODEOWNERS (ApprovalFilesModule) /
// package.json の scripts と依存。置いた後に索引を生成する。
// 何も書かずに終わる場合: --owner が無い・形が違う (I5) / docs/ に README.md 以外の文書がある (I6) /
// 置くファイルが既にある・承認の割り当てを足せない (I7・I8)。
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, dirname, join, resolve } from 'node:path';
import { DocGraphCheck } from '../../checks/DocGraphCheck.js';
import { AUDIENCE_ENTRANCE } from '../../core/Audience.js';
import { idOf, isDecisionTable } from '../../core/DecisionRows.js';
import { isDirectory, listDocFiles } from '../../core/DocFiles.js';
import type { CheckContext } from '../../core/Check.js';
import { ExitCode } from '../../core/ExitCode.js';
import { parseFrontmatter, scalar } from '../../core/Frontmatter.js';
import { classifyLines } from '../../core/LineClassifier.js';
import { findTables } from '../../core/MarkdownTable.js';
import type { Violation } from '../../core/Report.js';
import { Report } from '../../core/Report.js';
import { IGETA_VERSION_FILE, readIgetaVersion } from '../../core/Version.js';
import { ApprovalFilesModule, isOwnerForm } from '../../generators/ApprovalFilesModule.js';
import { ArgParseError, parseArgs } from '../Args.js';
import type { CommandContext } from '../Command.js';
import { Command } from '../Command.js';

interface PlannedFile {
  readonly relPath: string;
  readonly content: string;
  /** 'update' は、あるファイルに足りない分を足すこと (承認の割り当てのファイルだけ) */
  readonly action?: 'create' | 'update';
}

/** init が対象リポジトリへ入れる npm script。中身は igeta CLI を呼ぶだけで、実体は複製しない。 */
const SCRIPTS: Readonly<Record<string, string>> = {
  'docs:graph': 'igeta docs-graph',
  'docs:check': 'igeta docs-check',
  'docs:template-check': 'igeta template-check --require-kind --require-human-review',
  scaffold: 'igeta scaffold',
};

/**
 * 旧い docs がある repo への案内 (I6)。移行コマンドが入る版 (0.6.0) では、「`igeta docs-migrate` を実行する」に替える。
 * 0.5.0 は、移行コマンドがまだ無い。
 */
const MIGRATION_GUIDANCE = '旧い docs がある repo は、新しい構成にしてから使う。移行コマンド `igeta docs-migrate` は次の版で入る';

const DOCS_README = [
  '# ドキュメント',
  '',
  '> このディレクトリの目的: 設計書のルート。直下は確定させる人で分けた `person/`・`ai/`・`client/` の 3 つ。文書の種類と置き場所は、Igeta の版に固定した文書体系の手引き (`node_modules/igeta/templates/docs/ai/handbook/how-to/01-document-taxonomy.md`) が正典。',
  '',
  // 入口の 3 行は AUTOGEN 索引区間の外に置く (再生成で消えない)。文言の正本は src/core/Audience.ts の AUDIENCE_ENTRANCE
  // (templates/docs/README.md と同じ。I11)。
  '## 読み手別の入口',
  '',
  ...AUDIENCE_ENTRANCE,
  '',
  '## 索引',
  '',
  '<!-- AUTOGEN:dir-index:start — generated by scripts/generate-docs-graph.mjs, do not edit by hand -->',
  '<!-- AUTOGEN:dir-index:end -->',
  '',
].join('\n');

/** 雛形から置く文書 (templates/docs/ と docs/ は同じ階層。I3)。実装順序の文書は置かない (上流の文書がまだ無い) */
const TEMPLATE_DOCS: readonly string[] = [
  'person/design/shared/00-map.md',
  'person/requirements/01-requirements.md',
  'person/decisions/01-decisions.md',
  'person/decisions/README.md',
];

/** 記入例の行を持つ表の、見出しの最初のセル: ID の表 (要件・決定台帳)・「決めてほしいこと」 */
const EXAMPLE_TABLE_HEADS: ReadonlySet<string> = new Set(['ID', '問い']);

/** 最初の業務要件の行 (番号 001) の状態 (I3) */
const FIRST_ROW_STATE = '未決';

const MARKDOWNLINT = [
  '# igeta init が置いた既定。プロジェクト固有の緩和はこのファイルに足す。',
  'default: true',
  'MD013: false',
  'MD024:',
  '  siblings_only: true',
  'MD033: false',
  'MD041: false',
  '',
].join('\n');

const MARKDOWNLINT_CLI2 = [
  '# igeta init が置いた既定。',
  'globs:',
  '  - "docs/**/*.md"',
  '  - "*.md"',
  'ignores:',
  '  - "node_modules/**"',
  '  - "dist/**"',
  '',
].join('\n');

/** 索引を書いて確かめる回数の上限。新しく作った README.md は、その回の依存グラフに入らないので、1 回では書き終わらない */
const INDEX_PASSES = 2;

/** 終わりに出す次の手順 (I10) */
const NEXT_STEPS: readonly string[] = [
  'npm install && npm run docs:check',
  'GitHub の保護の設定 (PR 必須・持ち主のレビュー必須など) と、`igeta doctor` での確認',
  'AI への指示や実行に効くほかのファイル (`.mcp.json` など) を使うなら、`.igeta.json` の `humanPaths` に足す',
];

interface PackagePlan {
  readonly content: string;
  readonly conflicts: readonly string[];
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/** 今日の日付 (手元の時刻で YYYY-MM-DD) */
function today(): string {
  const now = new Date();
  const pad = (n: number): string => String(n).padStart(2, '0');
  return `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())}`;
}

/** 雛形の frontmatter の、id の無記入 (`<kebab-slug>`) を kind 名に、`created` の無記入 (`YYYY-MM-DD`) を今日の日付にする */
function fillFrontmatter(lines: readonly string[], created: string): string[] {
  const meta = parseFrontmatter(lines);
  if (meta === null) return [...lines];
  const kind = scalar(meta.data, 'kind');
  return lines.map((line, index) => {
    if (index >= meta.bodyStart) return line;
    if (/^created:\s*YYYY-MM-DD\b/.test(line)) return `created: ${created}`;
    if (kind !== undefined && /^id:\s*<[^>]*>/.test(line)) return `id: ${kind}`;
    return line;
  });
}

/**
 * 記入例の行を外す (I3)。ID の表と「決めてほしいこと」の表の行を全部外し、最初の決まりの表 (見出しの最後の列が `状態`) の
 * 最初の行だけは、状態を `未決` にして残す (最初の業務要件の行)。ほかの表 (誰が使うか・詳細への入口・関連) は変えない。
 */
function withoutExampleRows(lines: readonly string[], bodyStart: number): string[] {
  const dropped = new Set<number>();
  const kept = new Set<number>();
  let keptFirstRow = false;
  for (const table of findTables(lines, classifyLines(lines), bodyStart)) {
    if (!EXAMPLE_TABLE_HEADS.has(table.headers[0] ?? '')) continue;
    for (const row of table.rows) {
      if (!keptFirstRow && isDecisionTable(table) && idOf(row.cells[0]) !== null) {
        keptFirstRow = true;
        kept.add(row.line - 1);
      } else {
        dropped.add(row.line - 1);
      }
    }
  }
  return lines
    .map((line, index) => (kept.has(index) ? line.replace(/\|[^|]*\|\s*$/, `| ${FIRST_ROW_STATE} |`) : line))
    .filter((_, index) => !dropped.has(index));
}

/** frontmatter の depends_on・relates_to から、置いていない文書 (id が placedIds に無い。`external:` は文書でない) を指すものを外す */
function withoutAbsentRefs(lines: readonly string[], bodyStart: number, placedIds: ReadonlySet<string>): string[] {
  return lines.map((line, index) => {
    const matched = index < bodyStart ? /^(depends_on|relates_to):\s*\[(.*)\]\s*$/.exec(line) : null;
    if (matched === null) return line;
    const refs = (matched[2] ?? '')
      .split(',')
      .map((ref) => ref.trim())
      .filter((ref) => ref !== '' && (ref.startsWith('external:') || placedIds.has(ref)));
    return `${matched[1] ?? ''}: [${refs.join(', ')}]`;
  });
}

/** 人の文書 3 本と decisions/README.md を、雛形から作る (I3) */
function templateDocs(igetaRoot: string): readonly PlannedFile[] {
  const created = today();
  const filled = TEMPLATE_DOCS.map((relPath) => {
    const lines = fillFrontmatter(readFileSync(join(igetaRoot, 'templates', 'docs', relPath), 'utf8').split('\n'), created);
    const bodyStart = parseFrontmatter(lines)?.bodyStart ?? 0;
    return { relPath, lines: withoutExampleRows(lines, bodyStart) };
  });
  const placedIds = new Set(filled.map(({ lines }) => scalar(parseFrontmatter(lines)?.data ?? new Map(), 'id') ?? ''));
  return filled.map(({ relPath, lines }) => ({
    relPath: join('docs', relPath),
    content: withoutAbsentRefs(lines, parseFrontmatter(lines)?.bodyStart ?? 0, placedIds).join('\n'),
  }));
}

/** 索引を生成する。書いた後に検査して、ずれが無くなるまで (INDEX_PASSES 回まで) 繰り返す。返すのは、残った違反 (空なら、docs-check の索引の検査が通る) */
async function generateIndexes(ctx: CheckContext): Promise<readonly Violation[]> {
  let remaining: readonly Violation[] = [];
  for (let pass = 1; pass <= INDEX_PASSES; pass += 1) {
    const written = await new DocGraphCheck({ write: true }).run(ctx);
    if (written.length > 0) return written;
    remaining = await new DocGraphCheck({}).run(ctx);
    if (remaining.length === 0) return [];
  }
  return remaining;
}

/**
 * package.json は「作る」のではなく「足りない分だけ足す」。
 * 既存キーが違う値で埋まっていたら衝突として扱い、こちらの値で塗り潰さない。
 */
function planPackageJson(path: string, dependencySpec: string, fallbackName: string): PackagePlan {
  const conflicts: string[] = [];
  let pkg: Record<string, unknown>;

  if (existsSync(path)) {
    const parsed: unknown = JSON.parse(readFileSync(path, 'utf8'));
    if (!isRecord(parsed)) throw new Error('package.json が JSON オブジェクトではない');
    pkg = parsed;
  } else {
    pkg = { name: fallbackName, version: '0.0.0', private: true, type: 'module' };
  }

  const scriptsValue = pkg['scripts'];
  const scripts: Record<string, unknown> = isRecord(scriptsValue) ? { ...scriptsValue } : {};
  for (const [key, value] of Object.entries(SCRIPTS)) {
    const existing = scripts[key];
    if (existing === undefined) scripts[key] = value;
    else if (existing !== value) conflicts.push(`package.json scripts.${key}`);
  }

  const devDepsValue = pkg['devDependencies'];
  const devDeps: Record<string, unknown> = isRecord(devDepsValue) ? { ...devDepsValue } : {};
  const existingDep = devDeps['igeta'];
  if (existingDep === undefined) devDeps['igeta'] = dependencySpec;
  else if (existingDep !== dependencySpec) conflicts.push('package.json devDependencies.igeta');

  return {
    content: `${JSON.stringify({ ...pkg, scripts, devDependencies: devDeps }, null, 2)}\n`,
    conflicts,
  };
}

export class InitCommand extends Command {
  readonly name = 'init';
  readonly summary = '対象リポジトリに Igeta の検査配線と、3 フォルダの docs 骨格・承認の割り当てを入れる';
  override readonly usage = [
    '  --owner <持ち主>   承認する人 (必須)。@user・@org/team・メールアドレス。CODEOWNERS に書く',
    '  --root <dir>       対象リポジトリ (既定: カレントディレクトリ)',
  ];

  override async run(argv: readonly string[], ctx: CommandContext): Promise<ExitCode> {
    const args = parseArgs(argv, { valueOptions: ['root', 'owner'] });
    const owner = args.get('owner');
    if (owner === undefined) throw new ArgParseError('--owner が要る (承認する人。@user・@org/team・メールアドレス)');
    if (!isOwnerForm(owner)) {
      throw new ArgParseError(`--owner の形が違う: ${JSON.stringify(owner)} (@user・@org/team・メールアドレスのどれか)`);
    }
    const targetRoot = resolve(args.get('root') ?? ctx.cwd);
    const version = readIgetaVersion(ctx.igetaRoot);

    // 旧い docs がある repo は、I7 の衝突より先にここで止める (I6)
    const docsDir = join(targetRoot, 'docs');
    const legacyDocs = isDirectory(docsDir) ? listDocFiles(docsDir).filter((file) => basename(file) !== 'README.md') : [];
    if (legacyDocs.length > 0) {
      ctx.stderr(`STOP docs/ に README.md 以外の文書がある (例: docs/${legacyDocs[0] ?? ''})。何も書いていない。`);
      ctx.stderr(MIGRATION_GUIDANCE);
      return ExitCode.Violation;
    }

    const files: readonly PlannedFile[] = [
      { relPath: IGETA_VERSION_FILE, content: `${version.toString()}\n` },
      { relPath: join('docs', 'README.md'), content: DOCS_README },
      ...templateDocs(ctx.igetaRoot),
      { relPath: '.markdownlint.yaml', content: MARKDOWNLINT },
      { relPath: '.markdownlint-cli2.yaml', content: MARKDOWNLINT_CLI2 },
    ];

    const packagePath = join(targetRoot, 'package.json');
    const packagePlan = planPackageJson(
      packagePath,
      `github:SakakitaniJunya/Igeta#v${version.toString()}`,
      basename(targetRoot),
    );

    const approval = new ApprovalFilesModule(targetRoot).plan(owner);
    const conflicts = [
      ...files.filter((file) => existsSync(join(targetRoot, file.relPath))).map((file) => file.relPath),
      ...packagePlan.conflicts,
    ];
    const stops = 'stops' in approval ? approval.stops : [];
    if (conflicts.length > 0 || stops.length > 0) {
      for (const conflict of conflicts) ctx.stderr(`CONFLICT ${conflict} は既にある`);
      for (const stop of stops) ctx.stderr(`STOP ${stop}`);
      ctx.stderr(`\n${conflicts.length + stops.length} 件で止めた。1 ファイルも書いていない。`);
      return ExitCode.Violation;
    }

    const approvalFiles: readonly PlannedFile[] = 'writes' in approval ? approval.writes : [];
    for (const file of [...files, ...approvalFiles]) {
      const destination = join(targetRoot, file.relPath);
      mkdirSync(dirname(destination), { recursive: true });
      writeFileSync(destination, file.content);
      ctx.stdout(`${file.action === 'update' ? 'UPDATE' : 'WRITE'} ${file.relPath}`);
    }
    writeFileSync(packagePath, packagePlan.content);
    ctx.stdout('WRITE package.json');

    // 索引が無いと直後の docs:check が drift で落ちるため、ここで生成しておく
    const generated = new Report();
    generated.addAll(await generateIndexes({ targetRoot, igetaRoot: ctx.igetaRoot }));
    if (!generated.isEmpty) {
      ctx.stderr(generated.format());
      return generated.exitCode;
    }

    ctx.stdout('');
    for (const step of NEXT_STEPS) ctx.stdout(`NEXT  ${step}`);
    return ExitCode.Ok;
  }
}
