import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, dirname, join, resolve } from 'node:path';
import { DocGraphCheck } from '../../checks/DocGraphCheck.js';
import { ExitCode } from '../../core/ExitCode.js';
import { IGETA_VERSION_FILE, readIgetaVersion } from '../../core/Version.js';
import { parseArgs } from '../Args.js';
import type { CommandContext } from '../Command.js';
import { Command } from '../Command.js';

interface PlannedFile {
  readonly relPath: string;
  readonly content: string;
}

/** init が対象リポジトリへ入れる npm script。中身は igeta CLI を呼ぶだけで、実体は複製しない。 */
const SCRIPTS: Readonly<Record<string, string>> = {
  'docs:graph': 'igeta docs-graph',
  'docs:check': 'igeta docs-check',
  'docs:template-check': 'igeta template-check --require-kind',
  scaffold: 'igeta scaffold',
};

const DOCS_README = [
  '# ドキュメント',
  '',
  'この索引は `npm run docs:graph` が生成する。手で編集しない。',
  '',
  '<!-- AUTOGEN:dir-index:start — generated by scripts/generate-docs-graph.mjs, do not edit by hand -->',
  '<!-- AUTOGEN:dir-index:end -->',
  '',
].join('\n');

const MARKDOWNLINT = [
  '# igeta init が置いた既定。プロジェクト固有の緩和はこのファイルに足す。',
  'default: true',
  'MD013: false',
  'MD024:',
  '  siblings_only: true',
  'MD033: false',
  'MD041: false',
  '',
].join('\n');

const MARKDOWNLINT_CLI2 = [
  '# igeta init が置いた既定。',
  'globs:',
  '  - "docs/**/*.md"',
  '  - "*.md"',
  'ignores:',
  '  - "node_modules/**"',
  '  - "dist/**"',
  '',
].join('\n');

interface PackagePlan {
  readonly content: string;
  readonly conflicts: readonly string[];
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/**
 * package.json は「作る」のではなく「足りない分だけ足す」。
 * 既存キーが違う値で埋まっていたら衝突として扱い、こちらの値で塗り潰さない。
 */
function planPackageJson(path: string, dependencySpec: string, fallbackName: string): PackagePlan {
  const conflicts: string[] = [];
  let pkg: Record<string, unknown>;

  if (existsSync(path)) {
    const parsed: unknown = JSON.parse(readFileSync(path, 'utf8'));
    if (!isRecord(parsed)) throw new Error('package.json が JSON オブジェクトではない');
    pkg = parsed;
  } else {
    pkg = { name: fallbackName, version: '0.0.0', private: true, type: 'module' };
  }

  const scriptsValue = pkg['scripts'];
  const scripts: Record<string, unknown> = isRecord(scriptsValue) ? { ...scriptsValue } : {};
  for (const [key, value] of Object.entries(SCRIPTS)) {
    const existing = scripts[key];
    if (existing === undefined) scripts[key] = value;
    else if (existing !== value) conflicts.push(`package.json scripts.${key}`);
  }

  const devDepsValue = pkg['devDependencies'];
  const devDeps: Record<string, unknown> = isRecord(devDepsValue) ? { ...devDepsValue } : {};
  const existingDep = devDeps['igeta'];
  if (existingDep === undefined) devDeps['igeta'] = dependencySpec;
  else if (existingDep !== dependencySpec) conflicts.push('package.json devDependencies.igeta');

  return {
    content: `${JSON.stringify({ ...pkg, scripts, devDependencies: devDeps }, null, 2)}\n`,
    conflicts,
  };
}

export class InitCommand extends Command {
  readonly name = 'init';
  readonly summary = '対象リポジトリに Igeta の検査配線と docs 骨格を入れる';
  override readonly usage = ['  --root <dir>   対象リポジトリ (既定: カレントディレクトリ)'];

  override async run(argv: readonly string[], ctx: CommandContext): Promise<ExitCode> {
    const args = parseArgs(argv, { valueOptions: ['root'] });
    const targetRoot = resolve(args.get('root') ?? ctx.cwd);
    const version = readIgetaVersion(ctx.igetaRoot);

    const files: readonly PlannedFile[] = [
      { relPath: IGETA_VERSION_FILE, content: `${version.toString()}\n` },
      { relPath: join('docs', 'README.md'), content: DOCS_README },
      { relPath: '.markdownlint.yaml', content: MARKDOWNLINT },
      { relPath: '.markdownlint-cli2.yaml', content: MARKDOWNLINT_CLI2 },
    ];

    const packagePath = join(targetRoot, 'package.json');
    const packagePlan = planPackageJson(
      packagePath,
      `github:SakakitaniJunya/Igeta#v${version.toString()}`,
      basename(targetRoot),
    );

    const conflicts = [
      ...files.filter((file) => existsSync(join(targetRoot, file.relPath))).map((file) => file.relPath),
      ...packagePlan.conflicts,
    ];
    if (conflicts.length > 0) {
      for (const conflict of conflicts) ctx.stderr(`CONFLICT ${conflict} は既にある`);
      ctx.stderr(`\n${conflicts.length} 件が衝突。1 ファイルも書いていない。`);
      return ExitCode.Violation;
    }

    for (const file of files) {
      const destination = join(targetRoot, file.relPath);
      mkdirSync(dirname(destination), { recursive: true });
      writeFileSync(destination, file.content);
      ctx.stdout(`WRITE ${file.relPath}`);
    }
    writeFileSync(packagePath, packagePlan.content);
    ctx.stdout('WRITE package.json');

    // 索引が無いと直後の docs:check が drift で落ちるため、ここで 1 度生成しておく
    await new DocGraphCheck({ write: true }).run({ targetRoot, igetaRoot: ctx.igetaRoot });

    ctx.stdout('');
    ctx.stdout('NEXT  npm install && npm run docs:check');
    return ExitCode.Ok;
  }
}
